### ISSUE TITLE
Improve View function call

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#1015]
1. View function calls (non signed) should be able to take `originator_id` and `public_key`, and pretend it acts on the behalf of the `originator_id`.

2. Additional argument can be passed to allow state modifications during this view function call. These modifications are not going to be committed, but they would not result in the error.

**Comment by ilblackdragon** [comment]
Interestingly, Ethereum for view calls assumes `signer_id` is 0x0

**Comment by evgenykuzyakov** [comment]
@bowenwang1996 fixed it by prohibiting context access during view calls
