### ISSUE TITLE
Networking AccountId tracking

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#1043]
Currently when node joins, if they have a `validator_key` they will provide an account id into the network as part of handshake.

This is incorrect for two reasons:
 - This account may not exist yet or this key is not added yet. (normal case when just started a node)
 - Node can not have possession of the account it claims it has.

Instead, we should have next procedure:
 - Node in handshake doesn't send AccountId.
 - When node becomes validator for the epoch, they announce their account via AccountAnnounce, which is a signed message with validator key.
 - On receival of AccountAnnounce, other nodes perform next actions:
   - Check that indeed this account is validator and that signatures match
   - Gossip to others this validator's AccountAnnounce, recording routing table in it as well.
 - On gossip of validator's AccountAnnounce, either connect or record routing table based on received peer.

**Comment by mfornet** [comment]
Design changed. Read specifications at https://github.com/nearprotocol/NEPs/pull/12 and new design progress at #1363.
