### ISSUE TITLE
Block production failed (Invalid Block Time: block time) in unit test docker

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/nearcore#1045]
To repro: 
python ./scripts/start_unittest.py 
check http://localhost:3030/status.

node logs have this:

[2019-06-28T20:20:39Z ERROR near_client::client] Block production failed: Chain(Error { inner: 

Other Error: Error { inner: 

Invalid Block Time: block time 2019-06-28 20:20:39.983046100 UTC before previous 2019-06-28 20:20:40.006225 UTC } })
[2019-06-28T20:20:39Z ERROR near_client::client] Block production failed: Chain(Error { inner: 

Other Error: Error { inner: 

Invalid Block Time: block time 2019-06-28 20:20:39.994789200 UTC before previous 2019-06-28 20:20:40.006225 UTC } })
[2019-06-28T20:20:40Z ERROR near_client::client] Block production failed: Chain(Error { inner: 

Other Error: Error { inner: 

Invalid Block Time: block time 2019-06-28 20:20:40.006140500 UTC before previous 2019-06-28 20:20:40.006225 UTC } })

**Comment by ilblackdragon** [comment]
We never managed to reproduce this. We also added extra check to prevent timing issues when making blocks.
Possible there was some time misconfiguration.
