### ISSUE TITLE
consider different name for transaction

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#105]
i think this has been cargo culted from bitcoin (where all records on each block are financial transactions).. and i think it becomes confusing when we can define transaction as the following:
1) data that is being written to blocks (sending money, contract deployment, creating an account, etc.)
2) financial transaction
3) database transaction/commit

**Comment by azban** [comment]
what about `Record`?

**Comment by azban** [comment]
i don't think this should be closed. i still think this is an issue.. also we now have another notion of a transaction which is a transaction + a receipt, with no differentiation from `SignedTransaction` or `TransactionBody`  https://github.com/nearprotocol/nearcore/blob/eab903d3eb4710908e31ef221fee729c00bb1854/core/primitives/src/types.rs#L321

**Comment by ilblackdragon** [comment]
@azban do you have suggestions at this point?

**Comment by ilblackdragon** [comment]
I don't think at this point we going to change the name.
