### ISSUE TITLE
Additional error checks and tests for StateSync

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#1052]
More tests for edge cases in StateSync, for example when node doesn't have the requested state.

**Comment by Kouprin** [comment]
test_all_chunks_accepted_1000 related from https://github.com/nearprotocol/nearcore/pull/1975

**Comment by Kouprin** [comment]
https://github.com/nearprotocol/nearcore/pull/1979 is related to "having no state" case
