### ISSUE TITLE
Index transactions by account and serve via RPC

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#1054]

**Comment by janedegtiareva** [comment]
Can we get this prioritized for staking experience UX?

**Comment by nearmax** [comment]
I think for staking experience we should start with the spec of use cases. Then based on the use cases we can decide whether any RPC changes are required.

**Comment by ilblackdragon** [comment]
I'm going to close this, as we now have explorer backend that can serve this data.
