### ISSUE TITLE
refactor network client

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#107]
should probably be moved out of the network and it definitely needs to be renamed, because it is prohibitively confusing to implement `Client` for `Client`, and actually causes conflicts on IDE understanding what is going on when there are naming conflicts when they are both supposed to be in scope.

it seems like this is a trait for a blockchain, that network should rely on.

cc: @bowenwang1996 @ilblackdragon

**Comment by bowenwang1996** [comment]
I agree. What about something like "BlockChainBackend" Or "ChainBackend"?
