### ISSUE TITLE
/status endpoint shouldn't return success when node is stuck

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/nearcore#1078]
E.g. node is out of free space and clearly has detected an error:

```
Other Error: IO error: No space left on deviceWhile appending to file: testdir/data/043974.log: No space left on de
vice } })
[2019-07-17T22:32:06Z ERROR near_client::client] Block production failed: Chain(Error { inner: 
```

but `/status` still returns success:
```
http http://34.94.13.241:3030/status

HTTP/1.1 200 OK
content-length: 331
content-type: application/json
date: Wed, 17 Jul 2019 22:34:32 GMT

{
    "chain_id": "test-chain-J1UGb",
    "rpc_addr": "0.0.0.0:3030",
    "sync_info": {
        "latest_block_hash": "FVWgbBM7QM3HZaEJCTpvBW9wpN8NTExjGRyF2kiFBZif",
        "latest_block_height": 9292465,
        "latest_block_time": "2019-07-17T19:36:46.817254235Z",
        "latest_state_root": "98AnTyWc2opjeeTDtsHZEgs6XvcfBotJrmTGi7FmSo8i",
        "syncing": false
    },
    "validators": [
        "test.near"
    ]
}
```

**Comment by ilblackdragon** [comment]
The issue is that client is running, it just can't store anything in this case. 
We can return a number of errors client observed, because it's possible that the client will recover from this errors. What do you think?

**Comment by vgrichina** [comment]
@ilblackdragon I think we should return error while client still cannot write even if it can be recovered. Can we keep status somewhere of how up to date writing is and e.g. if we didn't write for a minute return fail?

**Comment by ilblackdragon** [comment]
Actually it's simpler, we should just query latest block and see how long ago if was. If it was longer then max_block_time ago - node is stuck or out of sync.

**Comment by vgrichina** [comment]
@ailisp may you look into this given you already dealing with status check?

**Comment by vgrichina** [comment]
@ailisp nvm, Illia already has fix
