### ISSUE TITLE
View State returns success even if account doesn't exist

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#1106]
We should return error that account doesn't exist.

**Comment by fckt** [comment]
You mean this https://github.com/nearprotocol/nearcore/blob/4773873b3cd680936bf206cebd56bdc3701ddca9/runtime/runtime/src/state_viewer.rs#L31
?

**Comment by fckt** [comment]
Checked. `near-shell` prints:
```
Error:  TypedError: [-32000] Server error: account test.neardd does not exist while viewing
```
