### ISSUE TITLE
Get rid of usize, at least in runtime

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1114]
The actual size of `usize` depends on the target it is compiled to. On 32-bit targets it is 32 bits, on 64-bit targets it is 64 bits. In the places that use `usize` and influence the result of state computation we should get rid of it to avoid forks.

**Comment by nearmax** [comment]
Example of the place that would create a fork if we have nodes compiled to both 64 and 32 bit targets.
https://github.com/nearprotocol/nearcore/blob/master/runtime/wasm/src/runtime.rs#L48

**Comment by evgenykuzyakov** [comment]
We need to check all critical parts that are serialized or WASM executor.

**Comment by nearmax** [comment]
This looks fixed now.
