### ISSUE TITLE
start_localnet + account id not specified, test.near key is generated but doesn't work

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/nearcore#1127]
steps to repro: 

from nearcore: 
python ./scripts/start_localnet.py --local
skip entering account id

from some other empty dir : 
export NODE_ENV=local  //set node environment to local 
near new_project
near create_account testcontract --initialBalance 10000 --masterAccount test.near

Get Error:  Error: [-32000] Server error: Transaction is not signed with a public key of the originator "test.near"

**Comment by janedegtiareva** [comment]
Looks like if I enter test.near when prompted for account id, it also doesn't work afterwards.

**Comment by ilblackdragon** [comment]
Seems to work now.
