### ISSUE TITLE
Handle the case of storage failure

### ISSUE THREAD

**Issue by mikhailOK** [nearprotocol/nearcore#1131]
If storage fails during contract execution, we want to handle it as node failure rather than contract call error (current behavior).

**Comment by nearmax** [comment]
In other words if during normal execution of the contract (not as part of challenge verification) we encounter inconsistent or corrupted storage this should be treated as node failure (that should be causing panic outside the runtime), rather than the failure of the contract.

**Comment by evgenykuzyakov** [comment]
We're removing iterators from `RuntimeExt` (issue #2276, PR #2278)

**Comment by fckt** [comment]
Right now, the tracking issue is https://github.com/nearprotocol/nearcore/issues/2055
