### ISSUE TITLE
Expensive tests are broken

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1156]
Our expensive tests are broken and were not run on CI.
To reproduce:
* Checkout the most recent `master`/`staging` branch;
* Run
```bash
  cargo test --all --features expensive_tests
```

Observe ~30 broken tests.

It seems like expensive tests were not run by the CI pipeline because there were configured to run daily on schedule (oppose to on each branch commit) but now the schedule was removed somehow from the Gitlab dashboard and we were not running them for a while.

**Comment by nearmax** [comment]
Cause: contract encoded with base58 but decoded with base64

**Comment by nearmax** [comment]
Working branch https://github.com/nearprotocol/nearcore/pull/1157

**Comment by nearmax** [comment]
@bowenwang1996 Is this fixed?

**Comment by bowenwang1996** [comment]
We run them in nightly tests now
