### ISSUE TITLE
Network tests are flaky

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1190]
Network test fails here: https://gitlab.com/near-protocol/nearcore/-/jobs/275426091
But when re-run succeeds: https://gitlab.com/near-protocol/nearcore/-/jobs/275435789

**Comment by mfornet** [comment]
@nearmax I don't see this error locally. I guess this is due to network overhead (there are several tests trying to open ports and running heavy logic at the same time). The fix should be wrap them with `heavy_tests`.
