### ISSUE TITLE
Can I run a node in my browser?

### ISSUE THREAD

**Issue by breck7** [nearprotocol/nearcore#1194]
I understand the contracts run in WASM.

Is there a WASM target of the node client as well?

I think it would make it easier (for me at least) to grok the testnet and future mainnet if I could run a node (even if slow) in my browser without installing anything (no docker, etc).

**Comment by evgenykuzyakov** [comment]
No we currently don't have plans to support node in the browser. At least until we start developing light clients.

**Comment by breck7** [comment]
Thanks @evgenykuzyakov. Sorry if that’s a dumb question, I’m trying to simplify things in my head as much as possible.

What would the challenges be with doing something like that? Do any of the block chains currently do that?

**Comment by vgrichina** [comment]
@breck7 AFAIK Coda targets running in browser:
https://codaprotocol.com

It's somewhat unique approach though with it's own trade-offs. Like everything has to be represented as zk-SNARKS (means that cannot really have Turing-complete contracts, etc.)

**Comment by breck7** [comment]
Interesting, thanks.

What about viewing a web page that launches a docker instance on the backend running a node, and when you close the page the instance shuts down? But when open the page it does launch an actual new node and runs computation(either that happens in the browser or on the server and the results/progress are streamed to browser) so people get “a feel” for how it all works.

I’m thinking of how you can make the whole thing explainable and accessible to the novice, without requiring an install. More of an educational/marketing feature than a practical way to scale, but like decision trees, might offer good explainability.

**Comment by bowenwang1996** [comment]
@vgrichina recursive snarks exist :)
@breck7 I don't think the point is to explain how the underlying node runs but rather to enable people to develop/use decentralized apps. Ideally users/developers should not even be aware that they are using a blockchain. I am not entirely sure what you mean by running computation, but if you mean how the underlying node works, that is too much to ask. Even for those of us who develop nearcore, we might not understand entirely how each module works.

**Comment by breck7** [comment]
Thanks @bowenwang1996.

> I don't think the point is to explain how the underlying node runs but rather to enable people to develop/use decentralized apps. Ideally users/developers should not even be aware that they are using a blockchain.

I really love the quality of what you are doing and design decisions (like WASM). A I think a great weakness of bitcoin/blockchain is the *unnecessary* complexity. I wonder if you could go further: "we've made the blockchain so _simple_ that even users can understand how it works". I think first blockchain to pull off high quality and simplicity could beat bitcoin or ethereum (I got in both of those early but yet have to admit I don't understand them and think they are unnecessarily complicated). Anyway, I don't really know what I'm talking about but just trying to express some gut feeling.

Is there some dashboard page for the current testnet? Something like: https://www.blockchain.com/en/stats

**Comment by evgenykuzyakov** [comment]
We're working on blockchain explorer: https://explorer.nearprotocol.com/
It's a work in progress, so something might not work or display incorrect info.

**Comment by breck7** [comment]
@evgenykuzyakov this is great! this is the type of thing I was looking for.
nit: the link to it is broken on your website (https://github.com/nearprotocol/docs/issues/52)
