### ISSUE TITLE
One failure in txflow test

### ISSUE THREAD

**Issue by mfornet** [nearprotocol/nearcore#123]
There is a tricky case failing, and as far as I see can be unrelated to tests tracked on #99 

`generated_endorse_kickout_fork`

Bob create two messages (a fork) B1 and B2. 
+ B1 approve representative message from Alice A in epoch 0 and becomes representative message in epoch 1.
+ B2 don't approve message A but is in epoch 1 so its a kickout message.

Further messages approving both B1 and B2 must discard B2 kickout message and endorse representative B1.

**Comment by nearmax** [comment]
Blocked on https://github.com/nearprotocol/nearcore/issues/125

**Comment by nearmax** [comment]
TxFlow is getting removed.
