### ISSUE TITLE
Ban the right originator for invalid messages

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#1259]
Currently if we receive relayed messages, and message content is invalid - we will try to ban the relay node. Instead we should ensure banning the original sender.

**Comment by mfornet** [comment]
@ilblackdragon I don't where we had such issue, but I think it is solved or at least will work that way when we finish networking.

**Comment by ilblackdragon** [comment]
@mfornet should we close this issue now then?

**Comment by mfornet** [comment]
Yes
