### ISSUE TITLE
Unhelpful error message when creating an account, sign with non-full access key

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/nearcore#1265]
Error message that is currently returned:
Error:  Error: [-32000] Server error: Transaction has more than 1 actions and is using function call access key

instead, it should mention something about insufficient privileges or something like that.

**Comment by ilblackdragon** [comment]
@mikhailOK did you error refactor fixed this issue?

**Comment by nearmax** [comment]
This seems WAI. We need to have a better documentation in terms of why we do not allow transactions like this instead of explaining it in high detail in the error message. Assigning to @amgando

**Comment by nearmax** [comment]
@fckt Could you provide an explanation to @amgando why this does not work?

**Comment by fckt** [comment]
Changed the message: https://github.com/nearprotocol/nearcore/blob/fckt/rpc-errors/core/primitives/src/errors.rs#L278

And renamed the error. CC @evgenykuzyakov

**Comment by fckt** [comment]
must be fixed by now
