### ISSUE TITLE
Remove ethash_provider from Runtime

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#1271]
Having Eth support in Runtime, but not in WASM creates additional security challenges and ties protocol to Eth natively. This is bad in a long term if Eth changes the protocol or get compromised. Instead we should implement Eth light-client completely on the smart contract level using MapReduce for validation.

**Comment by k06a** [comment]
@evgenykuzyakov but we need ETHASH for Near<>Ethereum bridge. Do you think storing dozens of megabytes inside a smart contract is fine?

**Comment by evgenykuzyakov** [comment]
This needs to be discussed, but currently Ethash is huge security issue for Runtime.
I and @nearmax suggest to use map-reduce style with multiple contract to build a Ethhash verification. It will remove the burden from validators having to compute this on demand. They need to agree on the valid latest blocks from Eth which requires consensus.

**Comment by evgenykuzyakov** [comment]
@ilblackdragon @SkidanovAlex

**Comment by k06a** [comment]
@evgenykuzyakov you mean the problem is the depending on Ethereum block headers?

**Comment by k06a** [comment]
@evgenykuzyakov so even storing Merkle root of the ethash dataset will not solve the issue?
