### ISSUE TITLE
Unhelpful error message: Invalid promise index

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/nearcore#1288]
It would be helpful to print out what's the promise index that was invalid.

**Comment by nearmax** [comment]
In a broader scope, errors like `InvalidPromiseIndex` should have payload, e.g. `InvalidPromiseIndex(u64)`.

**Comment by nearmax** [comment]
@fckt Could you take a look?

**Comment by fckt** [comment]
It must print https://github.com/nearprotocol/nearlib/blob/master/src.ts/res/error_messages.json#L12 now.
