### ISSUE TITLE
Better `tx` RPC API

### ISSUE THREAD

**Issue by frol** [nearprotocol/nearcore#1299]
https://github.com/nearprotocol/NEPs/pull/1

RPC API of the transaction (`tx`) should be restructured according to the conversation https://github.com/nearprotocol/docs/pull/55#discussion_r322392316

NOTE: It is a breaking change. ~Do we have consumers of this API (except Explorer)?~ It seems that the only consumer is Explorer and I can fix it.

The issues to address in the RPC API:

* [x] Expose more information on the `tx` RPC (there should not be less information than in the `block` RPC response)
* [x] Align the structure of the `block` (the `transactions` section) and `tx` responses
* [x] Transaction should have:
  * [x] block hash
  * [ ] ~shard id (?)~
  * [x] fees (Total fees denominated in NEAR, Gas used (units of gas), Gas price (price per unit in NEAR))
* [x] ~`CreateAccount` action should expose the account id~
* [x] ~Cover the public API with extensive tests, so it gets apparent when something gets changed when it should not.~ (track separately)

**Comment by frol** [comment]
`block` RPC currently returns transactions list with a structure that is completely different from the `tx` RPC:

```javascript
$ http post http://rpc.nearprotocol.com/ jsonrpc=2.0 id=dontcare method=block 'params:=[173592]'

{
    "id": "dontcare",
    "jsonrpc": "2.0",
    "result": {
        "header": {
            "approval_mask": [
                false,
                true
            ],
            "approval_sigs": [
                "ed25519:5tn8MtX8yQ2qzdRs8W6Homz4KWS2kQcoEnLXBXEa9qRUczAfYqUD3R3QxRAoWA9AwM1niauyt6VaQFn8sijEqkhS"
            ],
            "epoch_hash": "Di12sDSYsUH6ocaMf9NPKcBrUikEiCRPNkydKgZgEi8u",
            "hash": "BZnGxodahyU3Ssuh5dVNbAeBt3wqXTu8f8mLeo5cb4cH",
            "height": 173592,
            "prev_hash": "HhH72gqstfm5KGW6wf8nFa1tVjfeGjhsmv1NSxLutAdQ",
            "prev_state_root": "ABh7ZArZtVvEghH8SNXrDaTAMCFYzEayFFkg61j1qzc9",
            "signature": "ed25519:3CA8HwcmPDSdUuCdjBeFWP8AvK36yQ1PhDRz4PgF8RLT3fgQm4GoH242j5QNJvXrdws8ASygWJtaAqrUkHjug52X",
            "timestamp": 1568047128577482804,
            "total_weight": 208940,
            "tx_root": "11111111111111111111111111111111",
            "validator_proposals": []
        },
        "transactions": [
            {
                "actions": [
                    "CreateAccount",
                    {
                        "Transfer": {
                            "deposit": "10000000000000000000"
                        }
                    },
                    {
                        "AddKey": {
                            "access_key": {
                                "nonce": 0,
                                "permission": "FullAccess"
                            },
                            "public_key": "ed25519:J2Jrr74mgHxL5AmHeRSesWPgCA8jqcGqcEGKC2EEu59t"
                        }
                    }
                ],
                "hash": "2ZBygTrowP7MTeRQ8rXp8v84benMTaYbHhwFw5w85CTS",
                "nonce": 110,
                "public_key": "ed25519:oNCFEmRotRHTySKqmAwifNZ8VRpYS973p8cL61y7eiE",
                "receiver_id": "studio-n5ubb8npy",
                "signature": "ed25519:54uxKxJz5N4nzjYbeAuMKZVqUUwj2i9wXgjEeVNYx79mYXQr9bmfysDE5hGo2Smc1NNsTZ8Q6W62uymxq94TEy8J",
                "signer_id": "test"
            }
        ]
    }
}
```

```javascript
$ http post http://rpc.nearprotocol.com/ jsonrpc=2.0 id=dontcare method=tx 'params:=["2ZBygTrowP7MTeRQ8rXp8v84benMTaYbHhwFw5w85CTS"]'

{
    "id": "dontcare",
    "jsonrpc": "2.0",
    "result": {
        "status": "Completed",
        "transactions": [
            {
                "hash": "2ZBygTrowP7MTeRQ8rXp8v84benMTaYbHhwFw5w85CTS",
                "result": {
                    "logs": [],
                    "receipts": [
                        "CdbagwttuZnTcjGT3R8Qs9fsv8GFuFeUtJVnVZeAjoop"
                    ],
                    "result": null,
                    "status": "Completed"
                }
            },
            {
                "hash": "CdbagwttuZnTcjGT3R8Qs9fsv8GFuFeUtJVnVZeAjoop",
                "result": {
                    "logs": [],
                    "receipts": [],
                    "result": "",
                    "status": "Completed"
                }
            }
        ]
    }
}
```

Notice that there is no information about the actions.

**Comment by evgenykuzyakov** [comment]
For `CreateAccount action should expose the account id`, transaction has the receiver which exposes the newly created account_id

**Comment by frol** [comment]
@evgenykuzyakov Yeap, Illia has already pointed that out to me, so crossing it out from the list.

**Comment by evgenykuzyakov** [comment]
Why not just build standard API that is copies the inner structure using View conversion. E.g. expose Receipt with ActionReceipt structure, and also associated TransactionResult.

**Comment by evgenykuzyakov** [comment]
So we have a `ReceiptView` struct that we can serialize towards JSON. It has all the information about what actions are there, who is the predecessor and the signer.
For every executed receipt, we have a `TransactionResult`, which contain genereated `receipt_id`s that can be used to retrieve `ReceiptView`s.

To get the first ReceiptId from the signed transaction we can use `TransactionResult` of the `SignedTransaction` hash.

**Comment by ilblackdragon** [comment]
@frol do we still need to do something in this issue?

**Comment by frol** [comment]
@ilblackdragon Yes, we still need to provide more information on the transaction, but it is not blocking Explorer, so it is not high priority.

**Comment by frol** [comment]
It seems that most of the items are already addressed.
