### ISSUE TITLE
TxFlow protocol violations

### ISSUE THREAD

**Issue by mfornet** [nearprotocol/nearcore#131]
List of all possible actions that represent a violation of TxFlow and hence need to be reported as adversarial behavior through MisbehaviorReporter. 

- [x] **BadEpoch**: Message has incorrect epoch.
- [ ] **Missing endorsement**: There is no BLS signature for representative when there must be one.
- [ ] **Invalid endorsement**: Invalid part of the BLS signature.
- [x] **Fork Detection**: Two (or more) message from the same participant are not approved by each other.

Suspicious behavior:
- [ ] **Invalid message signature**: Message has invalid signature. Someone pretending to be another participant? [We can't slash in this case because anyone could create this message.]

**Comment by mfornet** [comment]
**Fork detection** addressed at #144.

**Comment by nearmax** [comment]
TxFlow is getting removed.
