### ISSUE TITLE
Panics in Rust contracts cause process crash with EXC_BAD_INSTRUCTION

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1319]
To reproduce:
* Checkout https://github.com/nearprotocol/near-bindgen/tree/make_fail
* Copy `examples/status-message/res/status_message.wasm` into `/tmp/`;
* Copy these files into `/tmp`:
https://www.dropbox.com/s/c9mpa3fcfwg9f3r/config.json?dl=0
https://www.dropbox.com/s/1v7ov4ghwmsgf4q/context.json?dl=0
* Checkout master on nearcore and run:
```
cargo run --color=always --package near-vm-runner-standalone --bin near-vm-runner-standalone -- --context-file=/tmp/context.json --config-file=/tmp/config.json --method-name=make_fail --wasm-file=/tmp/status_message.wasm --input='{}'
```

Observe that entire process (not just Wasmer thread) fails with:
```
Exception: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
```

This happens because Rust tries to serialize an unsupported structure into JSON which causes panic inside Rust contract on unwrap, but this panic instead of being propagated as an error causes a process crash.

Assigning to @mikhailOK since he is working on errors and cc-ing @fckt

**Comment by mikhailOK** [comment]
Tried this on `errors` branch with different backends, didn't reproduce the crash
VMOutcome is always
`{"balance":0,"storage_usage":0,"return_data":"None","burnt_gas":7641,"used_gas":7641,"logs":[]}`
- wasmer 0.5.7 with cranelift backend returns `FunctionCallError(WasmTrap("unknown"))`
- wasmer 0.5.7 with singlepass backend returns `WasmerRuntimeError::Error` of unknown type, seems like a bug
- wasmer 0.7.0 with both backends returns `FunctionCallError(WasmTrap("unknown"))`

Going to update to 0.7.0 with singlepass backend

**Comment by nearmax** [comment]
For the record, we discussed it offline, it looks like Clion debugger makes it look like the process is stopped when this happens, but it is actually not.

**Comment by nearmax** [comment]
@mikhailOK Is this fixed?

**Comment by nearmax** [comment]
@fckt Could you take a look?

**Comment by nearmax** [comment]
AFAIR this only happens in debugging, just a CLion quirk.
