### ISSUE TITLE
After some loadtest, memory issue and cannot deploy contract

### ISSUE THREAD

**Issue by ailisp** [nearprotocol/nearcore#1343]
After some loadtester running, especially heavy_storage type tests (using benchmark_storage_10kib under the hood), memory usage increase significantly:
![image](https://user-images.githubusercontent.com/13259400/65540676-b0a1ed80-dec0-11e9-9e78-a0925daa4fcf.png)
Memory usage doesn't go down an hour after tps go back to 0. So there's likely a memory leak.

Also deploy contract after always timeout, and the transaction used for deploying contract stuck in "Started/Unknown" status without a reason:
![image](https://user-images.githubusercontent.com/13259400/65542073-5a827980-dec3-11e9-8a53-a1720fccf8fd.png)

**Comment by ilblackdragon** [comment]
@ailisp this should be fixed now with memory leaks fixed? Can you re-test it?

**Comment by ilblackdragon** [comment]
Close this given staleness.
