### ISSUE TITLE
Runtime error: wasm async call execution failed with error: PrepareError("Gas instrumentation failed.")

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/nearcore#1344]
See https://github.com/nearprotocol/assemblyscript/issues/73 for context

When floats are detected error should be explicit about floats. Same goes for any other banned instruction type. Parity's gas metering injection code is relatively easy to fix to return specific error instead of general one.

it should be possible to return detailed error from here:
https://github.com/paritytech/wasm-utils/blob/c9cdef4c517b4da997d8ed518575a5524b3f3a86/src/rules.rs#L294

looks like https://github.com/paritytech/wasm-utils/blob/c9cdef4c517b4da997d8ed518575a5524b3f3a86/src/rules.rs#L308 tracks instruction types

**Comment by bowenwang1996** [comment]
It is not trivial. We basically have to patch the library the same way we are doing the error propagation in nearcore. It might involve a lot of work.

**Comment by vgrichina** [comment]
@bowenwang1996 maybe I don't understand something with Rust, but why is it any more complex than instead of having empty payload in `Err(())`we give payload with more info about specific error?

**Comment by bowenwang1996** [comment]
The problem is that every error inside that library is consumed. So it is hard to get the error we want without properly propagating the errors. But actually I think it might not be too hard if we just want to see whether it is caused by floats, although it feels like a hack

**Comment by vgrichina** [comment]
> But actually I think it might not be too hard if we just want to see whether it is caused by floats, although it feels like a hack

no need to do some beautiful solution, we just need to have reasonable error message for developers for this specific case (and maybe other common cases).

**Comment by nearmax** [comment]
Floats are now enabled.
