### ISSUE TITLE
Skip 15 test should work

### ISSUE THREAD

**Issue by Kouprin** [nearprotocol/nearcore#1346]
An important test to check that receipts work properly even in cases of losing some OneParts and epoch changing.

**Comment by Kouprin** [comment]
Fix routing and un-ignore tests `test_catchup_receipts_sync_last_block`, `test_catchup_random_single_part_sync_skip_15` and `test_catchup_random_single_part_sync_send_15`.

**Comment by ilblackdragon** [comment]
@Kouprin is this addressed now?

**Comment by Kouprin** [comment]
It was a routing issue when we lose all transactions in the last block of the epoch. @SkidanovAlex said he will fix it.

**Comment by SkidanovAlex** [comment]
Most likely related to #1484
