### ISSUE TITLE
Garbage collection for information stored in memory

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#1370]
The current testnet at 1.6 million blocks uses 1.7G of memory, which seems to have caused the slowdown of block speed. We should do proper garbage collection to avoid unreasonable memory usage.

**Comment by ilblackdragon** [comment]
@bowenwang1996 this was just memory leak, right? should be fixed now?

**Comment by bowenwang1996** [comment]
Yes fixed for now
