### ISSUE TITLE
More near-vm-logic tests

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1412]
We need tests for the following bindings API:

* Miscellaneous API, e.g. we are accepting both utf8 and utf16 with nul-terminated and not nul-terminated versions of the API. We should make sure they work correctly and we should make sure it returns a correct error message when strings are not encoded correctly;

* Math API, we need to make sure sha256 works correctly;

* Economics API, we need to make sure the variables that we set in context and returned correctly through Economics API.

* Using registers instead of guest memory. According to https://nearprotocol.github.io/nomicon/Runtime/BindingsSpec/RegistersAPI.html one should be able to set `*_len` to `u64::MAX` and then pass register id into `*_ptr` which will tell the host to read the data from the register instead of the guest memory. We should test that this functionality works.

**Comment by fckt** [comment]
> Using registers instead of host memory. According to https://nearprotocol.github.io/nomicon/Runtime/BindingsSpec/RegistersAPI.html one should be able to set *_len to u64::MAX and then pass register id into *_ptr which will tell the host to read the data from the register instead of the guest memory. We should test that this functionality works.

Looks like this functionality is not implemented..

Btw, by "host memory" you mean a guest memory (the memory Wasm code have access to), right?

**Comment by nearmax** [comment]
> Looks like this functionality is not implemented yet..

Correct. Could you please implement it?

> Btw, by "host memory" you mean a guest memory (a memory Wasm code has access to), right?

Yes, it is typo.

**Comment by fckt** [comment]
Note that for `get_utf8_string` we already use parameter `len=std::u64::MAX` to signal that it's null-terminated already so we can't use it as a discriminator for reading string from register.

**Comment by nearmax** [comment]
> Note that for `get_utf8_string` we already use parameter `len=std::u64::MAX` to signal that it's null-terminated already so we can't use it as a discriminator for reading string from register.

Correct, log_* is an exception.

**Comment by nearmax** [comment]
This looks done.
