### ISSUE TITLE
Memory allocation failure

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#1414]
On both staging testnet and master testnet, sometimes the node crashes with memory allocation failure (it tries to allocate more than 1GB of memory). This seems to only have happened to the node that receives rpc request. So it is possible that some kind of rpc request would crash the node.

**Comment by ailisp** [comment]
Is there any error log I can look? Thanks.
Also i'm considering, since you've mentioned rpc. log rpc call in code then see what rpc cause this crash, then try to reproduce

**Comment by bowenwang1996** [comment]
There is no log because gcloud just shuts down the instance

**Comment by ailisp** [comment]
Hmm. I'm going to add persistent "log to stackdriver" first. Is it suddenly try to allocate more than 1GB of memory once, or gradually increasing memory that caused failure?

**Comment by bowenwang1996** [comment]
It suddenly tries to allocate a large chunk of memory and gcloud just kills the process with no log

**Comment by mikhailOK** [comment]
was a bug in borsh
