### ISSUE TITLE
Implement proper utf-16 string reading for log_utf16

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#1419]
Right now it's based on assembly script string format.

**Comment by nearmax** [comment]
Why is it based on AS format? Looks generic to me.

**Comment by evgenykuzyakov** [comment]
Before #1420 fix, log_utf16 was using `get_utf16` which uses AS string length read from `ptr - 4`, see https://github.com/nearprotocol/nearcore/blob/ba0815679765851b45e59d6fb173c67672875119/runtime/near-vm-logic/src/logic.rs#L1337

**Comment by nearmax** [comment]
@fckt FYI.
