### ISSUE TITLE
Same contract code is not getting de-duplicated when stored in trie

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1431]
It is still not clear whether it is WAI or a bug, but when I create a trie with a very large number of accounts, where each account has the same contract code this code is not getting de-duplicated on trie-level.

To reproduce:
```bash
rm -rf /tmp/data2
cargo run --package near --bin near -- --home /tmp/data2 init --chain-id= --test-seed=alice.near --account-id=test.near --fast
cargo run --package genesis-populate --bin genesis-populate -- --additional-accounts-num=1000000 --home /tmp/data2
ls -alh /tmp/data2/state_dump
```
Observe that it is 880M.
Then comment out https://github.com/nearprotocol/nearcore/blob/0677512a9c9c33d1013a151a251fd3b6a45ea57f/genesis-tools/genesis-populate/src/main.rs#L30
and run the above code again. Observe 340M. This indicates that we have duplicated a ~440bytes contract 1M times in the trie.

@mikhailOK explained that de-duplication in the trie only happens when:
**There is a subtrie A and a subtrie B such that they are equivalent if we ignore some prefix of keys in A and some prefix of keys in B.**

So if we have two accounts that have the same smart contract code their code is stored in key-values that have different keys but the same values. Why won't they be de-duplicated? 

CC @ilblackdragon 

If it is WAI should we fix it anyway? I would expect us to have a large number of accounts deploying the same ERC20 (or similar) contract code once we go mainnet.

**Comment by ilblackdragon** [comment]
I don't fully understand, I would expect our dedup method work here. Why are the contracts not ending up having the same value under different keys @mikhailOK ?

**Comment by nearmax** [comment]
This should be fixed.
