### ISSUE TITLE
Add overflow checks for Runtime

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#1461]
Current Runtime implementation doesn't handle overflows cause it assumes certain fields can't overflow, e.g. it assumes `account.amount + account.locked` can't overflow, because the total supply should fit into u128.

It can overflow if the Runtime operates on top of a given proof. For example a malicious node gives a proof to challenge something or gives an invalid chunk root with partial state with values that exceed u128. All valid nodes would just panic with u128 overflows. Instead we should handle overflow gracefully and propagate this overflow error up.

**Comment by nearmax** [comment]
We talked with Trail of Bits, their fuzz testers are catching overflows in our runtime. We discussed that we should fix it soon, e.g. next week, so that their tooling is not getting distracted by arithmetic overflows and be able to catch more subtle bugs.

**Comment by evgenykuzyakov** [comment]
There are still some places that we missed with the #1662. E.g. storage compute
I'll add a TODO in the code

**Comment by evgenykuzyakov** [comment]
I think we should rerun fuzzer from trail bits, now as the math is fixed.
I also need to look into VMLogic itself

**Comment by nearmax** [comment]
* Reduced the priority to P1 since what is left is to run fuzzer and manually scrutinize the code;
*  It seems like @evgenykuzyakov is not working on it actively, so I am moving it back to the Backlog.
