### ISSUE TITLE
GET RPC for query method 

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#1515]
Currently queries like `account/account_id` and `validators` don't require any parameters and can be served with GET request.

For example `https://localhost:3030/account/account_id`.

**Comment by frol** [comment]
@ilblackdragon Why do we need this? It will force us to maintain two sorts of APIs (REST-like and jsonrpc).

**Comment by ilblackdragon** [comment]
Just convenience - I frequently use HTTP /status on my phone for example.

But I think we can close this as it's indeed probably not worse time right now.
