### ISSUE TITLE
Implement state dividing methods in Trie

### ISSUE THREAD

**Issue by Kouprin** [nearprotocol/nearcore#1523]
The last part of https://github.com/nearprotocol/nearcore/issues/1237.

### Understanding the part and proving

The part is `(shard_id, part_id, data)` and called StatePart.
All StateParts are merklizable and their Merkle Root is equal to the hash of StateRoot.
`let (state_hash, proofs) = merklize(&parts)`
It's easy to prove part validity in RuntimeAdapter::accept_state_part by executing:
`verify_path(state_root.hash, &merkle_proof, part)`

### What should be done in Trie

1. Building StateRoot by understanding size of Trie and number of parts it will be divided. Currently it's in TrieUpdate::finalize to demonstrate the idea and please implement it in a proper way.
2. Methods get_state_part_and_proof, prove_state_part and accept_state_part are under Trie impl. They should be implemented according to the logic described above.
3. Replacing Trie in RuntimeAdapter::confirm_state according to https://github.com/nearprotocol/nearcore/pull/1492#discussion_r337160064.

### Useful things

Try to grep `TODO #1523` after https://github.com/nearprotocol/nearcore/pull/1492. It shows you all necessary locations where should be updated.

**Comment by Kouprin** [comment]
Trie parts: https://github.com/nearprotocol/nearcore/pull/1592

**Comment by mikhailOK** [comment]
#1603 for future improvements
