### ISSUE TITLE
Collect metrics related with networks.

### ISSUE THREAD

**Issue by mfornet** [nearprotocol/nearcore#1543]
Collect all networking data and save it for further exploration and analysis of network behavior.
This will allow us to know what type of messages and nodes are generating more traffic, network topology, and where to put some of the efforts for further improvements.

Since we are already using prometheus and grafana (#1416) it seems like a good idea using them for this type of reports. Prometheus by default use polling strategy which doesn't fit well for this case, since we want to post all messages received and not only aggregated data. They offer [Pushgateway](https://prometheus.io/docs/instrumenting/pushing/) in order to use push strategy instead of polling.

It would be really nice to graph the current network topology, live changes (old edges), and metadata for each node, such as if they are current validators, their shards, etc...

This is also a step towards the goal proposed in #1480.

**Comment by damons** [comment]
Could all of this be included in Explorer?  Seems so to me.  

Also, is this really needed for mainnet?  i.e., is it a blocker?

**Comment by mfornet** [comment]
@damons this is WIP in #2239. It can be easily added to the explorer, it will be behind a feature flag, but a node compiled with this feature will be compatible with other nodes.

**Comment by ilblackdragon** [comment]
@mfornet What is the status of this issue?
