### ISSUE TITLE
sync_after_sync_nodes has a weird behaviour

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#1570]
Verbose log shows that it gets stuck on syncing for awhile, even though it's a starightforward sync without chunks:

https://pastebin.com/uV8rk49c

**Comment by Kouprin** [comment]
Is it still actual? I cannot reproduce it on actual staging (commit `a2324edd`).

**Comment by SkidanovAlex** [comment]
@Kouprin can you confirm one more time there's no repro and close?

Would also be good to confirm with Illia what particular part of the log is in question, because the log dump is pretty large.

**Comment by Kouprin** [comment]
I've executed it several times with Debug level tracing:
1. no `[2019-10-26T01:08:18Z DEBUG near_client::client_actor] Epoch out of bound for header Epoch Out Of Bounds` message
2. no stacktrace appeared
3. execution log is pretty short
4. test takes ~5 seconds to complete

I guess the issue isn't actual for now.
