### ISSUE TITLE
CI for backward compatibility

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#1573]
Going forward (very soon) we must be backward compatible with existing nodes.

To ensure this, we will adopt next CI tests for new PRs:
 - checkout `master` branch (or just get latest released binary)
 - start node with `master` branch, run it for a period of time.
 - start a node from `staging` on the same home folder.
 - start another node with `master` branch, and boot node that first staging node.
 - make sure blocks are produced and tx get processed

Probably the best way to do this via `pytest` script.

Additional check can be added that if PR contains "HARDFORK" in the name, this test doesn't run.

**Comment by ailisp** [comment]
I happens to impl infra for doing this, for a remote node, it has a change_version method, which checkout to commit or branch and rebuild.

**Comment by ilblackdragon** [comment]
Tests are added to pytest/test/sanity/backward_compatible.py.
Now, @ailisp must add it to CI as a non-failing test to indicate when we break the protocol.

**Comment by ailisp** [comment]
:+1 Sure

**Comment by ilblackdragon** [comment]
Implemented.
