### ISSUE TITLE
[Runtime stability] Wrap arithmetic operations into recoverable error checks

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1577]
Runtime can be used when validating the proofs. Someone can construct a proof such that when we run it through the runtime we get overflows/underflow with arithmetic operations which cause panic in Rust. For instance this place: https://github.com/nearprotocol/nearcore/blob/af08ba913ff8a6a8fbd5622c8bdda8ee91df79aa/runtime/runtime/src/balance_checker.rs#L132
We should wrap all arithmetic operations into recoverable alternatives and pipe the error check all the way up, similarly to how we pipe `StorageError`.

**Comment by evgenykuzyakov** [comment]
Merge with #1461
