### ISSUE TITLE
Replace kvdb* dependencies

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1578]
Upd 2018-11-18: After a thorough investigation by @ailisp we have decided to replace kvdb* dependencies with our own code that will be wrapping https://github.com/rust-rocksdb/rust-rocksdb directly.

Our current RocksDB configuration is random. We should make sure it does not do anything stupid and also that we are utilizing it correctly for our case. Allegedly, the performance of RocksDB can vary a lot depending on how well it is tuned for the specific application that uses it.

**Comment by ailisp** [comment]
Assume still use kvdb-rocksdb, the only thing it can configured is memory_budget, which currently we se default, only 128M. After figuring out #1607 unreasonable high memory usage I can get more knowledge to experiment a good option for this.
If we plan to use raw rocksdb there's a lot more configuration options

**Comment by nearmax** [comment]
We should also get rid of several layers of indirection that we use in there. 
We use the following crates on the top of rocksdb that we could get rid of:
`kvdb`
`kvdb-rocksdb`
`kvdb-memorydb`
`paritytech/rust-rocksdb` which is a fork of `rust-rocksdb/rust-rocksdb`

We should replace the first three modules with our own code (not necessarily encapsulated in  separate crates) and use `rust-rocksdb/rust-rocksdb` instead. We have already encountered bugs with parity libraries, so we should keep these dependencies to the minimum.

**Comment by nearmax** [comment]
Another thing to take a look at is `pingcap/rust-rocksdb` as a replacement for `rust-rocksdb/rust-rocksdb` it should be faster when values are >16kb which might be our case because of the chunks.

**Comment by ailisp** [comment]
For the dependency, I feel the same. it's likely we need fork and maintain a rust-rocksdb. Will have a look at pingcap fork too. Which would be a good bench mark on different configs of rocksdb, I think  your runtime benchmark is a nice choice?

**Comment by nearmax** [comment]
> it's likely we need fork and maintain a rust-rocksdb

Why this would be the case?

>  Which would be a good benchmark on different configs of rocksdb, I think your runtime benchmark is a nice choice?

Yes, I think it should be good enough for now, but we should do two things to make it more realistic:
* Use large trie with ~1M accounts;
* Disable cache here https://github.com/nearprotocol/nearcore/blob/6a0087568dec565aa29a059cd8166257aa7e6031/runtime/near-vm-runner/src/cache.rs#L13 and here https://github.com/nearprotocol/nearcore/blob/1ccd5d99dcb4a0043e61171ad3a066cc97d7f982/runtime/runtime/src/cache.rs#L12
because in real life I think it will be relatively rare that we hit the same smart contract repeatedly.

**Comment by ailisp** [comment]
For benchmark, sounds good! For fork I think you are right, I was
speculating because they forked so it’s likely the vanilla rust-rocksdb
didn’t meet their requirements.

**Comment by nearmax** [comment]
> speculating because they forked so it’s likely the vanilla rust-rocksdb
didn’t meet their requirements.

Discussed offline.

**Comment by nearmax** [comment]
This is done, closing.
