### ISSUE TITLE
[Runtime] Transaction ordering

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1579]
Our current transaction ordering is not specified. The ordering scheme is now more complex than on conventional blockchains because we have nonces on each access key. Suppose we have transactions coming from three access keys (`A, B, C`, where `hash(A) < hash(B) < hash(C)` ): `A0, A1, A2, ...`; `B0, B1, B2, ...`; `C0, C1, C2, ...`.
We cannot be ordering them as `A0, A1, A2, ..., B0, B1, B2, ..., C0, C1, C2, ...` , because `A` will be privileged over `B` and `C` which might open an abuse vector or make DevX/UX suboptimal.
Therefore we should be ordering them as:
`A0, B0, C0, A1, B1, C1, A2, B2, C2, ...` but this requires changes. AFAIK this ordering is currently not implemented CC @evgenykuzyakov .

Also, the ordering is currently decided outside the runtime and then the runtime receives transactions and receipts that were already ordered as slices: https://github.com/nearprotocol/nearcore/blob/af08ba913ff8a6a8fbd5622c8bdda8ee91df79aa/runtime/runtime/src/lib.rs#L920
We should either:
* pass `HashSet<SignedTransaction>` to the runtime;
* or reorder the slice inside the runtime.

The first one looks easier to read and understand since `HashSet` implies the absence of ordering. However, placing transactions into `HashSet` will likely cause an unnecessary large allocation. The second one requires careful documentation since someone reading `Runtime` API might incorrectly assume that the `transactions: &[SignedTransaction]` determines the order of transactions.

**Comment by evgenykuzyakov** [comment]
Runtime should take a draining iterator from mempool for transaction filtering and choose up to a given gas block limit.

Mempool should have sorting logic inside. Since Node has an authority to decide which TXs to reject or accept, we can't really influence them. We also have a check in Runtime to reject entire `apply` function if any of the input transactions fails, so it's required to preorder TXs to satisfy the following rule.

**Comment by evgenykuzyakov** [comment]
Ref #1507

**Comment by bowenwang1996** [comment]
Will we respect topological ordering on transactions? The validator rotation relies implicitly on that.

**Comment by nearmax** [comment]
> Will we respect topological ordering on transactions with respect to accounts? The validator rotation relies implicitly on that.

@bowenwang1996 What topological order are yout talking about? The only place where I remember we talked about topological ordering is parallelization of the runtime.

**Comment by bowenwang1996** [comment]
I meant whether the ordering will be such that the transaction with larger nonce for given account will always be processed later than the transaction with lower nonce for the same account.

**Comment by nearmax** [comment]
> Runtime should take a draining iterator from mempool for transaction filtering and choose up to a given gas block limit.

In general, implementing your own iterator is a hard thing in Rust, because of the lifetimes. In this case, it is even harder because mempool lives in a different thread. So we will need to have some locking inside the iterator and mempool, this makes thread synchronization more complex. The whole point of actors was to avoid using syncrhonization primitives as much as possible to avoid deadlocks.

> Mempool should have sorting logic inside. Since Node has an authority to decide which TXs to reject or accept, we can't really influence them. 

You are conflating two things: deciding on the set of transactions and deciding on how to order them. The blockchain layer decides on the set of transactions. The runtime should decide on their order. There is no added benefit to have transaction ordering before transactions arrive to the runtime.

> We also have a check in Runtime to reject entire apply function if any of the input transactions fails, so it's required to preorder TXs to satisfy the following rule.

I disagree, if the check is consistent (which it is) then all nodes will reject the set of transactions consistently.

**Comment by nearmax** [comment]
> I meant whether the ordering will be such that the transaction with larger nonce for a given account will always be processed later than the transaction with lower nonce for the same account.

What you describe seems to be a linear ordering (which is technically a special case of topological ordering). We order transactions by two dimensions (x, y): x= hash of the access key, and y =nonce. If we use topological ordering than some access keys will be too privileged. The ordering that I suggested above in the issue description is *diagonal matrix traversal*.

**Comment by bowenwang1996** [comment]
[Linear order](https://en.wikipedia.org/wiki/Total_order) would mean you can compare the order of any two transactions (from potentially different account), which is not what I am interested in. Anyways it seems what you proposed does respect the order I want.

**Comment by evgenykuzyakov** [comment]
> There is no added benefit to have transaction ordering before transactions arrive to the runtime.

We don't want to include invalid transactions in the chunk to avoid being able to fill the block with invalid transactions. This means we need to pre-filter them before we put them into the chunk. If we pre-filtering them, then we need to order them. It doesn't matter if we order them in runtime or not as long as the order is the same.

**Comment by nearmax** [comment]
> > There is no added benefit to have transaction ordering before transactions arrive to the runtime.
> 
> We don't want to include invalid transactions in the chunk to avoid being able to fill the block with invalid transactions. This means we need to pre-filter them before we put them into the chunk. If we pre-filtering them, then we need to order them. It doesn't matter if we order them in runtime or not as long as the order is the same.

You are right.

**Comment by evgenykuzyakov** [comment]
Challenge for the order will be covered by #1702
