### ISSUE TITLE
Unreasonable memory and cpu usage

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#1607]
After running for a while, testnet node can have sudden increase of memory and cpu usage (from 1 GB to 7 GB in minutes and cpu usage from 10% to 100%), which slows down block production speed. It also receives and sends unreasonable amount of data on the network (around 1.5MB/s), which could be related to the high memory and cpu usage, especially given that most blocks are empty.

**Comment by bowenwang1996** [comment]
@frol how much data is explorer pulling from the node? Might be related

**Comment by frol** [comment]
@bowenwang1996 It pulls the whole network... like every chunk in every block. I have recently reset Explorer (it had not been reset after the hard fork).

**Comment by bowenwang1996** [comment]
@frol it always pulls from one node right? That seems problematic. Chunks are huge and doing so might cause very high network usage.

**Comment by frol** [comment]
@bowenwang1996 Right, that is what I have. Do we have a pool of public RPC endpoints, so I can balance between them? Should we have RPC exposed from another (non-block-producing node)?

**Comment by ailisp** [comment]
For now staging url is a load balancer of three nodes, you can try that and
let me see the load. We don’t know if there is any issue on having a load
balancer over more than one nodes yet. If it goes well I can also set
maintest net like this

**Comment by bowenwang1996** [comment]
@frol we can. We just need to adjust some nodes to also track shards. But actually the high network usage I saw is unrelated to rpc.

**Comment by frol** [comment]
Also, the load Explorer produces is limited to 1000 concurrent connections pulling the blocks sequentially (from newest to oldest), and it is heavy only for the first synchronization time.

**Comment by ailisp** [comment]
1000 get isn’t a lot, likely as Bowen said is node to node traffic

**Comment by ailisp** [comment]
Some new findings on this (dumped from staging-node3 of a totally 1.1gb ram usage, perhaps need to wait for a higher mem usage. From here it's not cause of rocksdb, store, and chain, likely because of shards.
![image](https://user-images.githubusercontent.com/13259400/68253225-3d6dba00-ffdc-11e9-80c1-c91ca9f332a1.png)
If expand mouse onto the tree in right side bar, actually both yellow, orange and red part is point to near_chunks::ShardsManager::process_chunk_one_part, which takes more than 80% of memory.

**Comment by ilblackdragon** [comment]
@bowenwang1996 This is fixed now, right?

**Comment by bowenwang1996** [comment]
I believe memory usage is fixed, but sometimes I still see high cpu usage and we need to better understand what happened there.

**Comment by ailisp** [comment]
In run 100 node test, cpu usage become 100% after about just one hour of running, and it's remain at 100% level since then.

**Comment by bowenwang1996** [comment]
Close this issue as it is obsolete. Will open new ones regarding performance.
