### ISSUE TITLE
run_nodes_4_4_2 fails in CI regularly

### ISSUE THREAD

**Issue by Kouprin** [nearprotocol/nearcore#1626]
Warning! Reproduces not every time.
Tested on actual staging, commit `a2324eddbe625c5812bdf4ef9278a2d4f8c60c8a`.
The problem appears in State Sync, trying to call `self.network_adapter.send(NetworkRequests::StateRequest)` in sync.rs:
<img width="820" alt="Screenshot 2019-11-02 at 18 45 24" src="https://user-images.githubusercontent.com/5685493/68073411-095a8500-fda1-11e9-8d8f-4d66e895db6a.png">
then trying to get it in client_actor:
<img width="727" alt="Screenshot 2019-11-02 at 18 46 44" src="https://user-images.githubusercontent.com/5685493/68073426-31e27f00-fda1-11e9-91d7-5ab8a32fdaa8.png">
Debug output contains of "@@@" and doesn't contain of "$$$":
<img width="801" alt="Screenshot 2019-11-02 at 18 47 50" src="https://user-images.githubusercontent.com/5685493/68073446-5e969680-fda1-11e9-9ca1-62fb78a75c3f.png">
Possible problem: something weird on network level, no other node can get the data.

**Comment by bowenwang1996** [comment]
Yes we are aware of this issue. @mfornet is debugging it.

**Comment by ilblackdragon** [comment]
Fixed in #1589
