### ISSUE TITLE
Validators RPC should show details about current assignment

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#1637]
Currently it's unclear who is assigned to which shard and order of block production.

Also we should have just a separate end point to query validators instead of using `query`.
```
http post http://localhost:3030/ method:=validators params:="" id=dontcare jsonrpc=2.0
```

Additionally, let's surface the information about how much missing blocks / chunks each validator has.

**Comment by ilblackdragon** [comment]
#1699 addresses most of the things.
The only missing part is to show shard assignment.

**Comment by frol** [comment]
@ilblackdragon Please, help me understand how shard assignment should be exposed. Currently, here is what I get when I do the RPC call:

```
$ http post https://staging-rpc.nearprotocol.com/ 'method=validators' 'params:=["Cc2vWJFvrRTSgxBbF5Fz1aA4AY7H8bYkZN1HGw62udRf"]' id=dontcare jsonrpc=2.0

{
    "id": "dontcare",
    "jsonrpc": "2.0",
    "result": {
        "current_proposals": [],
        "current_validators": [
            {
                "account_id": "far",
                "is_slashed": false,
                "num_missing_blocks": 0,
                "stake": "200839539809943853280832"
            }
        ],
        "next_validators": [
            {
                "account_id": "far",
                "amount": "200840937130310980675162",
                "public_key": "ed25519:7rNEmDbkn8grQREdTt3PWhR1phNtsqJdgfV26XdR35QL"
            }
        ]
    }
}
```

**Comment by nearmax** [comment]
@ilblackdragon  Is this fully implemented by https://github.com/nearprotocol/nearcore/pull/1962 ?

**Comment by frol** [comment]
This seems to be completely resolved and documented.
