### ISSUE TITLE
Stop using sodiumoxide

### ISSUE THREAD

**Issue by abacabadabacaba** [nearprotocol/nearcore#1656]
We are currently using libsodium (via sodiumoxide crate). I see a number of reasons against it:
* libsodium is written in C and doesn't fully conform to Rust conventions. For example, we have to call [init()](https://docs.rs/sodiumoxide/0.2.5/sodiumoxide/fn.init.html) (do we?), or some of its functions will not be thread-safe.
* libsodium only provides a high-level API. We cannot use it to implement a VRF (#1653), or randomness (nearprotocol/NEPs#22), or anything else that requires low-level cryptography.
* We only use a small subset of libsodium's functionality. When I searched through the code, I only found uses of SHA-256 hash function and Ed25519 signature scheme. Yet, we compile and link the entire library.

I propose to use these crates instead of sodiumoxide:
* For SHA-256: [sha2](https://github.com/RustCrypto/hashes). Also, consider switching to a more modern hash function, such as BLAKE2.
* For Ed25519: [ed25519-dalek](https://github.com/dalek-cryptography/ed25519-dalek).

**Comment by ailisp** [comment]
I'm going to ensure every c/c++ dependency doesn't use too new instruction set (which cause some validator with old cpus report: illegal instructions). This is better done before examine them so I'll take this
