### ISSUE TITLE
Properly handle epoch transitions when computing finality

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#1675]
Currently the FG doesn't handle epoch switches at all.

1. Make the finality gadget aware of BP switches (probably by just ignoring approvals beyond the epoch switch and stopping early).
2. Remember the first block at which the epoch switch is planned to occur, and only actually switch the epoch once it is final.

**Comment by ilblackdragon** [comment]
@SkidanovAlex is this done now?

**Comment by bowenwang1996** [comment]
I suggest we remove the `self.config.num_block_producers < 4` check
