### ISSUE TITLE
Add a timestamp field in Transaction

### ISSUE THREAD

**Issue by fckt** [nearprotocol/nearcore#1686]
We should have a timestamp field in Transaction.

**Comment by bowenwang1996** [comment]
Why?

**Comment by evgenykuzyakov** [comment]
We can't rely on the given timestamp cause it's client generated, so there are no need to add it to Transaction.
If we only need it for the pool than we can add it in the pool directly when the transaction is added. Or just a TX index.

**Comment by fckt** [comment]
Right.. Let's assume `tx timespamp` == `block_timestamp`
