### ISSUE TITLE
Introduce unstaking transaction action

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1713]
Currently in order to unstake one needs to create a staking transaction with `amount=0` and pass any sequence of bytes in place of the public key because it is ignored. This should be changed, since asking user to enter "whatever" in one of the interface parameters is a bad interface. It requires users to either come up with a fake public key just to unstake something or lookup the previously used public key which requires an additional RPC.

I am assigning it to @frol because this requires changes to RPC and runtime which he is working with. CC @bowenwang1996 and @evgenykuzyakov

**Comment by nearmax** [comment]
Relevant: https://stackoverflow.com/questions/58906180/why-does-unstaking-require-a-staking-public-key

**Comment by bowenwang1996** [comment]
If you are a validator and you want to unstake, you know the public key that you stake with. I don't see why you need additional rpc to look it up.

**Comment by nearmax** [comment]
> If you are a validator and you want to unstake, you know the public key that you stake with. I don't see why you need additional rpc to look it up.

Sure, one does not need to do any RPC lookups, because this argument takes anything if `amount=0`. We can pretend and write in the documentation that during ustaking this should be a previous key or a new key or whatever other specific sequence of bytes, but we will be just pretending that this interface expects something which it does not, this makes it a bad interface.

**Comment by nearmax** [comment]
If an argument is not used, then it should not be there.

**Comment by bowenwang1996** [comment]
Right now unstaking uses the same interface as staking, so it would weird if we only drop the requirement for public key if the amount is 0. If we want to do that we can add another command called `unstake`.
Also I don't see why this requires change in rpc. There are two ways to change this: we either change the transaction itself to make public key optional, or in the cli tool add some default value when constructing the transaction.

**Comment by nearmax** [comment]
> so it would weird if we only drop the requirement for public key if the amount is 0.

Why would it be weird?

> If we want to do that we can add another command called unstake.

This does not solve it for the smart contract developers or anyone who does not use or nearlib. 
What you are suggesting is to patch it in: nearlib, near_bindgen, near_runtime_ts, and pretend in the documentation of RPC like this argument is being used. That's a lot of patching for the benefit of not adding another action to our list of actions.

> Also I don't see why this requires change in rpc.

*RPC documentation.

> There are two ways to change this: we either change the transaction itself to make public key optional, or in the cli tool add some default value when constructing the transaction.

The third way is adding unstaking action. Making public key optional is also not a perfect interface, because this will also create a confusing interface -- now one can construct a staking action with non-zero amount and no public key (are we going to resue the previous key in this case?); The second way requires patchin everywhere in the applayer.

**Comment by bowenwang1996** [comment]
> Why would it be weird?

Because you can then do `near stake 100 <public_key>` and `near stake 0` at the same time, which is not consistent.



> The third way is adding unstaking action. Making public key optional is also not a perfect interface, because this will also create a confusing interface -- now one can construct a staking action with non-zero amount and no public key (are we going to resue the previous key in this case?); The second way requires patchin everywhere in the applayer.

We can do that. The downside I see is that: we need to add in applayer the support for this. In addition, we now have two ways of unstaking: either sending a unstaking transaction or a staking transaction with 0 amount.

**Comment by nearmax** [comment]
> Because you can then do `near stake 100 <public_key>` and `near stake 0` at the same time, which is not consistent.

I am not sure I understand what consistency is getting broken here. We can send "create account" and "delete account" at the same time too, and it is going to work just fine.

> We can do that. The downside I see is that: we need to add in applayer the support for this. In addition, we now have two ways of unstaking: either sending a unstaking transaction or a staking transaction with 0 amount.

I have not thought of that downside. At this moment I see two viable candidates (both with downsides): add an unstaking action or making public key optional. @fckt  and @evgenykuzyakov what do you think about that?

Also another argument in having a more explicit staking is how we already do account creation. Account creation action has no arguments, and in fact we could derive whether an account should be created instead of failing on when it is not. But we don't do it and make it more explicit.

**Comment by bowenwang1996** [comment]
The inconsistency that I was referring to is that the same command can have different number of arguments based on the value of some arguments. `create_account` and `delete account` are different because they are different commands.

**Comment by frol** [comment]
*Disclaimer: I am not familiar with the topic.* Why staing=0 does not require a public key while staing any other value requires the key? Is it sane from the security point of view? I would expect to either the key being required for the both or none of the transaction types.

**Comment by bowenwang1996** [comment]
So for amount=0 you don't have to put a public key there because it is not possible for you to be selected as validator if your stake is 0. On the other hand, if you stake any positive amount, there is a possibility that you will be selected, which means that you have to have a public key. But I agree that we should have the same interface to reduce confusion.

**Comment by frol** [comment]
*The above disclaimer applies here.* Can we drop the requirement of providing a public key for stake > 0?

**Comment by nearmax** [comment]
> _The above disclaimer applies here._ Can we drop the requirement of providing a public key for stake > 0?

Nope. The public key is used by the validator to sign things during the validation. But if you stake `0` you are not a validator anymore so there is no point of providing a public key.

**Comment by nearmax** [comment]
Here is another argument to have unstaking as an explicit action. Consider action of creating an access key https://github.com/nearprotocol/nearcore/blob/9e30d8cbd30cbb79ce84380642e4066308960e82/core/primitives/src/transaction.rs#L43 specifically the field `AccessKeyPermission` https://github.com/nearprotocol/nearcore/blob/b34e15c1157d9002a784b2d35d84b7bbff186b55/core/primitives/src/account.rs#L52 it allows creating both full key and non-full key.
We could have avoided having an enum there and always use `FunctionCallPermission` https://github.com/nearprotocol/nearcore/blob/b34e15c1157d9002a784b2d35d84b7bbff186b55/core/primitives/src/account.rs#L66 so that when someone passes `method_names==vec![]` we know they are requesting a full access key instead of a restricted access key. However we do not do it and instead leverage the strict type system of Rust because it improves readability and reduces potential mistakes.

Similarly, in `FunctionCallPermission` we could have had `allowance: Balance` instead of `allowance: Option<Balance>`  and if someone passes `allowance==0` we would know that they ask for no allowance, but instead we leverage strict type system and make optionality explicit through `Option<T>`.

**Comment by frol** [comment]
I would then forbid stake=0 (just as you said, you cannot stake 0, so it is treating it as an unstaking operation) and only allow an unstake transaction to make things clear.

> The public key is used by the validator to sign things during the validation.

I hope you meant that the public key is used by the remote entities to validate that the validator signed things with the relevant secret key.

**Comment by nearmax** [comment]
> I hope you meant that the public key is used by the remote entities to validate that the validator signed things with the relevant secret key.

Correct. What I meant is "The secret key associated with that public key is used by the validator to sign things during the validation."

> I would then forbid stake=0 (just as you said, you cannot stake 0, so it is treating it as an unstaking operation) and only allow an unstake transaction to make things clear.

I agree, currently, it looks like the most intuitive interface.

**Comment by ilblackdragon** [comment]
I'm actually not sure where we end up here. 
Seems like we are not implementing this for MainNet? 
I'll close this then, because post MainNet we should revisit the whole EpochManager construct.
