### ISSUE TITLE
In a ViewCall the sender and the receiver might be different.

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#172]

**Comment by evgenykuzyakov** [comment]
Contracts now have access to the context. E.g. who's the sender of current call. It can be used for checking who send the transaction with money. So viewcall code might want to use sender to implicitly  return some values. E.g. get_token_balance(token_name) wouldn't need to receive the explicit account_id.

**Comment by ilblackdragon** [comment]
Hm, I'm still not convinced this makes sense.
Read only functions should not rely on who sent the transaction. It's not enforcable in any way.
If this a view function for specific info - it should be done via argument
