### ISSUE TITLE
Non-action/op fees

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1723]
* The [Balance](https://github.com/nearprotocol/nearcore/blob/1f4359b33bdc30690da1e10ca1aa37e227bd6b0b/core/primitives/src/types.rs#L26) is measured in yocto-Near (10**-24 Near);
  * This allows us to have up to~340 Trillion Near in the system;
* On the moment of launch, we are going to have 1B Near in the system, therefore [GenesisConfig::total_supply](https://github.com/nearprotocol/nearcore/blob/d0a40bd42aa5a19faf4e2ebcc850b32521831dbc/near/src/config.rs#L414) will be initially assigned to be 10**(9+24) = 10**33 yNear.
* On the moment of launch we are going to estimate as [GenesisConfig::num_blocks_per_year](https://github.com/nearprotocol/nearcore/blob/d0a40bd42aa5a19faf4e2ebcc850b32521831dbc/near/src/config.rs#L416) to be `365*24*3600` by assuming that one block roughly takes 1 sec.

* The [Gas](https://github.com/nearprotocol/nearcore/blob/1f4359b33bdc30690da1e10ca1aa37e227bd6b0b/core/primitives/src/types.rs#L28) at the moment of launch will roughly correspond to 1 femtosecond worth of computation to the network;

* We will assign initial [GenesisConfig::gas_price](https://github.com/nearprotocol/nearcore/blob/d0a40bd42aa5a19faf4e2ebcc850b32521831dbc/near/src/config.rs#L392) to be 5000. Which means 1 Gas costs 5000 yNear;

* We will assign [GenesisConfig::gas_limit](https://github.com/nearprotocol/nearcore/blob/d0a40bd42aa5a19faf4e2ebcc850b32521831dbc/near/src/config.rs#L390) be 10**15 gas which will roughly cap 1 block at 1 sec computation time. Later, when we split `gas_limit` into two limits: per block and per receipt we will equally divide this value in two.

* We will assign [RuntimeConfig::storage_cost_byte_per_block](https://github.com/nearprotocol/nearcore/blob/9b66d2b4231a2607f2ace3a4d44be6ab46e28cf9/runtime/runtime/src/config.rs#L18) to be 5*10^6 yNear per byte per block;

* We will assign [RuntimeConfig::poke_threshold](https://github.com/nearprotocol/nearcore/blob/9b66d2b4231a2607f2ace3a4d44be6ab46e28cf9/runtime/runtime/src/config.rs#L20) 24*3600 which if we take 1 sec per block will allow 1 day removal period for an account.

* @evgenykuzyakov what we should assign `RuntimeConfig::account_length_baseline_cost_per_block` to?

**Comment by bowenwang1996** [comment]
why do we split gas limit equally between transactions and receipts?

**Comment by nearmax** [comment]
We need to have different gas limiter for receipts and transactions because both of them will have to be dynamically adjusted based on the load. Currently, we cannot tell if the load between transactions and receipts will be 20:80, 50:50 or 80:20. It will also change through several days and weeks after the launch. So we need to have these two thresholds dynamically adjusted by the system. Initially, we make them equal to each other because this is the best guess.

On a relevant topic. I was thinking whether allowing these thresholds to be adjusted independently in each shard is a good idea or not. Ideally, we would want these thresholds to be adjusted independently in each shard because some shards will be doing a lot of cross-shard receipt processing, e.g. shards hosting exchanges and bridges. While other shards will have fewer receipts; WDYT @bowenwang1996 ?

**Comment by frol** [comment]
@nearmax Can't we just normalize the prices instead of migration from atto- to yocto-? This change will lead to a huge wave of changes throughout the codebase: RPC (?), App layer (Wallet, Explorer), documentation (this is the most painful, I believe), and I am sure we will miss quite a few places...

/cc @potatodepaulo @ilblackdragon @janedegtiareva

**Comment by nearmax** [comment]
> @nearmax Can't we just normalize the prices instead of migration from atto- to yocto-? 

Some of our fees are too small to be expressed in atto-Near. Plus to allow enough precision we need the smallest fee to have at least 6 decimal digits (so that it is granular enough to be easily adjusted later).

**Comment by nearmax** [comment]
Here is some quick math:

### Gas <-> Seconds
* We expect a block to take approximately 1 sec;
* The fastest operation in the smart contract is reading bytes from a register. It takes approximately 63637 femtoseconds per byte to read a blob of data from the register;
* We roughly equate 1 Gas = 1 femtosecond of execution time (since our runtime is not parallelizable).
  * The reason why we are not setting 1 Gas = 1 attosecond, because it will push the lowest denomination of Near even further down from yocto-Near;
  * The reason why we are not setting 1 Gas = 1 picosecond is that then the above fee will be 63 Gas which does not allow enough precision if the future this operations suddenly becomes many times cheaper;

### Gas <-> Apples
* Suppose it costs 0.0005 Apples (here and below I will use a fictional asset to express the cost of running hardware) to produce 1 shard chunk.
  * Therefore 1 Gas is 0.0005*10^-15 Apples = 5*10^-19 Apples;

### Tokens <-> Apples
* Initially, we are going to have 10^9 Near tokens in our system;
* Suppose 1 Near is 100 Apples;

### Gas <-> Tokens
* Therefore 1 Near is 1.8*10^20 Gas
* If we pick our lowest denomination of Near to be yocto-Near. Then according to our hardcoded formula of how we convert Gas to Near we can price 1 Gas as ~5000 yocto-Near, which allows enough precision in case our gas prices change drastically.

**Comment by nearmax** [comment]
For the reference: https://docs.google.com/spreadsheets/d/1CXUQLlfGWXAO1l5qbHhwylc4JIUIrQB4BDaACagMYEU/edit

**Comment by evgenykuzyakov** [comment]
RuntimeConfig::account_length_baseline_cost_per_block is (3^8) multiplied by whatever we should charge an account for 10 letter character account per block. Let's do 1N per year for 10 letter character, so at a rate of 1 block per second (31556952 seconds). (10^24 / 31556952 * 3^8) = 207909813343189798558
