### ISSUE TITLE
actions.rs uses `RuntimeFeesConfig::default().storage_usage_config`

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#1744]
Instead it should use fees config from Runtime.

**Comment by mikhailOK** [comment]
same for trie memory costs in `near-store`

**Comment by mikhailOK** [comment]
also if we ever change storage related configs we have to recompute the state

**Comment by fckt** [comment]
FIxed in https://github.com/nearprotocol/nearcore/pull/1797

**Comment by mikhailOK** [comment]
Tracking trie config in #1804, this can be closed
