### ISSUE TITLE
Review c/c++ dependencies build which cause illegal inst in old cpu

### ISSUE THREAD

**Issue by ailisp** [nearprotocol/nearcore#1746]
We have some c/c++ dependencies required by rust libs, which are not in control by RUSTC_FLAGS. Some of these dependency, like parity-rocksdb-sys causes illegal instruction when build binary in a newer CPU and run it in older CPU. This is solvable by passing some c/c++ flags when build them. However other c/c++ dependencies need to be reviewed and build in a portable way as well

**Comment by nearmax** [comment]
@ailisp Is this fixed now?

**Comment by ailisp** [comment]
Not yet

**Comment by ailisp** [comment]
reed-solomon is using pure rust now. I was always lack a way to test illegal instructions. Today find a very handy tool: https://software.intel.com/en-us/articles/intel-software-development-emulator

**Comment by ailisp** [comment]
parity-rust-rocksdb-sys support pass a portable flag, but rust-rocksdb-sys does not, which is the major blocker prevent us build a portable binary: https://github.com/rust-rocksdb/rust-rocksdb/issues/363

**Comment by ailisp** [comment]
checklist:
 - [] cexpr-0.3.6
 - [] reed-solomon-erasure-3.1.1
 - [] brotli-sys-0.3.2
 - [] jemalloc-sys-0.3.2
 - [] ring-0.16.9
 - [] librocksdb-sys-6.2.4
 - [] ipconfig-0.2.1
 - [] backtrace-sys-0.1.32
 - [] sysinfo-0.10.2
 - [] sysinfo-0.9.5
 - [] miniz-sys-0.1.12
 - [] ring-0.14.6
 - [] parity-secp256k1-0.7.0
 - [] wabt-sys-0.7.0
 - [] reed-solomon-erasure-4.0.1
 - [] clang-sys-0.28.1

**Comment by nearmax** [comment]
How about we just submit a fix from parity-rust-rocksdb-sys to rust-rocksdb-sys which is just an optional env variable?

**Comment by ailisp** [comment]
Sounds good

**Comment by nearmax** [comment]
@ailisp Is this fixed?

**Comment by ailisp** [comment]
@nearmax not yet. i'm making pr to rust-rocksdb now.

**Comment by ailisp** [comment]
@nearmax rust-rocksdb completely skip rocksdb's CMakeLists.txt, it instead use https://docs.rs/cc crate and manually play with dependency and build flags. I think this is suboptimal though i still made flags that mimic rocksdb's PORTABLE cmake option. However i wasn't able to run intel sdk tool to verify it's fixed (always coredumped). will verify when back office with mac mini

**Comment by ailisp** [comment]
Today run a skylake compiled binary to run on sandy bridge and ivy bridge without illegal instruction (weird :thinking:, it was illegal instruction immediately when `sde -ivb -- target/release/near run` and `sde -snb --`) 
So it isn't a blocker to release binary/binary inside docker now

**Comment by ailisp** [comment]
Close as our binary releases went well both in practice and in sde emulator
