### ISSUE TITLE
Use rational numbers for percentages in `GenesisConfig`

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1747]
We should use rational numbers for the following:
`developer_reward_percentage`, `protocol_reward_percentage`, and `max_inflation_rate`.

It is much harder to upgrade the code than the value of the `GenesisConfig`. Therefore we should not rely on the fact that we can easily make `developer_reward_percentage`, `protocol_reward_percentage`, and `max_inflation_rate` rational in the future and instead do it now.

**Comment by nearmax** [comment]
Relevant: https://github.com/nearprotocol/nearcore/issues/1739

**Comment by ilblackdragon** [comment]
@nearmax by rational numbers, you mean to have `Fraction { nominator: 90, denominator: 100 }` ?

**Comment by nearmax** [comment]
Yes.
