### ISSUE TITLE
Tests should use injectable fake timer

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1770]
Currently, our tests use a real system timer. This is partly because our prod code cannot be injected with a fake timer. Real timers in tests have several issues:
* Tests might become non-deterministic: flaky or non-reproducible failures;
* It is hard to step through these tests with the debugger, because between the debugger steps the real timer still runs making e.g. some blocks invalid, see: chain/chain/tests/simple_chain.rs

**Comment by ilblackdragon** [comment]
@SkidanovAlex is this fixed with your Doomslug work or still needed?

**Comment by bowenwang1996** [comment]
We pass `cur_time: Instant` as an argument to `process_timer`. I think it is good enough.
