### ISSUE TITLE
Remote mode for python tests

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#1776]
Currently `init_cluster` / `start_cluster` have a `config` parameter that describes whether the test should run locally, or in the cloud, and in the latter case has some parameters for the remote invocation.

The parameter needs to be removed, and instead assume `local` by default. The remote execution should be configured by passing an environment variable `NODES_CONFIG`, that would contain all the information necessary for the remote run.

The following features should also work with the remote execution:

- [x] Shutting down network (`lib/network.py`)
- [x] Log tracker (`lib/utils.py`)

**Comment by ailisp** [comment]
above features and load config from NEAR_PYTEST_CONFIG env var is done. Most sanity tests are passed. stress test is failed locally. Will back to run remote stress test when local stress test works well
