### ISSUE TITLE
Expose gas price via RPC

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#1779]
Would be good to know the gas price for upcoming block (or a few).
This is useful to show the prices for transaction in the UX and for programmatical operating.

**Comment by bowenwang1996** [comment]
Do you mean the current gas price? It is updated every block so not sure how you know the gas price in the future.

**Comment by ilblackdragon** [comment]
Given previous block - you can calculate what will be the gas price for upcoming block.
For few blocks in front - one can give the bounds.
