### ISSUE TITLE
test_validator_kickout is flaky

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1784]
https://gitlab.com/near-protocol/nearcore/-/jobs/362041885

**Comment by ailisp** [comment]
Currently cargo test tries to run all tests in parallel. I suspect some of tests can't be run with other. Do we have ways to mark certain test shouldn't be run together with another test? Or manually schedule them

**Comment by nearmax** [comment]
Cargo does not have a way to run tests sequentially. We solve it using: https://github.com/nearprotocol/nearcore/blob/93667aad1496c66adc4afd0b506379fa85a5b7aa/test-utils/testlib/src/test_helpers.rs#L12

**Comment by ailisp** [comment]
I see. Is this work when test is comming from different binaries? I suspect it's probably not. If you do
`cargo test --workspace --no-run`, you got a lot of binary of tests in target/debug:
![image](https://user-images.githubusercontent.com/13259400/69997238-898f1a00-1508-11ea-80d4-200c59cfaae4.png)
Run tests are in fact running these binaries, e.g. run one of them, and you'd something like:
![image](https://user-images.githubusercontent.com/13259400/69997339-c9560180-1508-11ea-907e-0858b5a4f459.png)

**Comment by nearmax** [comment]
Probably not, you would have to write some cross-process version.

**Comment by nearmax** [comment]
`process_blocks` is also flaky https://github.com/nearprotocol/nearcore/pull/1910#issuecomment-576063871

**Comment by ilblackdragon** [comment]
@SkidanovAlex Is these tests still flaky?

**Comment by ilblackdragon** [comment]
Seems not flaky.
