### ISSUE TITLE
misspelling nit in developer facing error message

### ISSUE THREAD

**Issue by amgando** [nearprotocol/nearcore#1793]
`Account {:?} doesn't` _exists_ should be `Account {:?} doesn't` **exist**

https://github.com/nearprotocol/nearcore/blob/7cd0ab607edaa116dd93dfd3c97747ffc8bc8596/runtime/runtime/src/state_viewer.rs#L90-L91

**Comment by fckt** [comment]
done in https://github.com/nearprotocol/nearcore/commit/08e2ca5c1e44cb604aefb9c7239d9b20915c7d98#diff-5d0e62b92f5eee7e2ee11e44042cc1f6R91
