### ISSUE TITLE
Storage fixes and cleanups

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1795]
- [x] Bug: Missing `StorageError` upon trie iteration https://github.com/nearprotocol/nearcore/blob/f5fa12e60a77a9739f6c9ece49e3966bafde52b1/core/store/src/trie/update.rs#L265 We should be throwing storage error instead of swallowing it. 

- [x] Dead code: `RcTrieNode` is not used, it has a definition with fields, but these fields are never used. Only class methods `encode` and `decode_raw` [are used](https://github.com/nearprotocol/nearcore/blob/6736bf3221a683657e7707065983b75d37c4a2f5/core/store/src/trie/mod.rs#L383), but they do not use the structure or its fields. 

- [x] Dead code: `Trie::delete` does not use [deleted](https://github.com/nearprotocol/nearcore/blob/6736bf3221a683657e7707065983b75d37c4a2f5/core/store/src/trie/insert_delete.rs#L325);

**Comment by nearmax** [comment]
CC @mikhailOK

**Comment by fckt** [comment]
> Dead code: Trie::delete does not use deleted;

@mikhailOK what is was for and why it's not used anymore?
