### ISSUE TITLE
Fix StorageUsageConfig

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1810]
Currently `StorageUsageConfig` expresses in gas what it costs to store a byte of data for each kind of data stored in an account, like: cost of storing an account, cost of storing key/values, cost of storing contract. There is an issue with that:

The storage cost cannot be expressed in `Gas`, because storage rent is deducted directly in tokens without going through gas cost (gas cost is a dynamic variable that changes depending on the load of the given shard). For instance `StorageUsageConfig::key_cost_per_byte` is expressed in `Gas` (per byte), it gets multiplied by the number of bytes, then gets multiplied by `storage_cost_byte_per_block` expressed in `Balance` (tokens) and deducted from the account balance. It is an incorrect arithmetics. 

What `StorageUsageConfig` is actually trying to express is an upper bound on the storage overhead in bytes. It is a syntactic fix: we should rename fields in `StorageUsageConfig` to express that these are upper bounds on the overhead, and use `u64` instead of `Gas` for them.

There is however another issue, expressing overhead like this for `key_cost_per_byte`, `value_cost_per_byte`, `code_cost_per_byte` does not make sense since it does not allow granularity. Currently, it can express either no overhead (`1`), 2x overhead (`2`), 3x overhead (`3`), etc. We should get rid of these fields altogether.

**Comment by fckt** [comment]
> The storage cost cannot be expressed in Gas, because storage rent is deducted directly in tokens without going through gas cost (gas cost is a dynamic variable that changes depending on the load of the given shard).

Right. So the base unit here is `byte`, not `gas`. So here we shouldn't use a `gas_price`, but  a `byte_price` (which is `storage_cost_byte_per_block`).

> What StorageUsageConfig is actually trying to express is an upper bound on the storage overhead in bytes

Wy the costs are even different? 

```
pub struct StorageUsageConfig {
    /// Base storage usage for an account
    pub account_cost: Gas,
    /// Base cost for a k/v record
    pub data_record_cost: Gas,
    /// Cost per byte of key
    pub key_cost_per_byte: Gas,
    /// Cost per byte of value
    pub value_cost_per_byte: Gas,
    /// Cost per byte of contract code
    pub code_cost_per_byte: Gas,
}
```

```rust
fn cost_per_block(
    account_id: &AccountId,
    account: &Account,
    runtime_config: &RuntimeConfig,
) -> Balance {
    let account_length_cost_per_block = if account_id.len() > 10 {
        0
    } else {
        runtime_config.account_length_baseline_cost_per_block
            / 3_u128.pow(account_id.len() as u32 - 2)
    };

    let storage_cost_per_block = u128::from(total_account_storage(account_id, account))
        * runtime_config.storage_cost_byte_per_block;

    account_length_cost_per_block + storage_cost_per_block
}
```

There is also a weird heuristic (`account_length_cost_per_block` calculation), I don't really understand how it relates to an idea of `paying for resource`.

**Comment by mikhailOK** [comment]
The weird heuristic implements this NEP: `https://github.com/nearprotocol/NEPs/pull/6/files`

**Comment by nearmax** [comment]
@evgenykuzyakov Did you fix it with your limiters?
