### ISSUE TITLE
AccountView should return computed balance as balance

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#1811]
Currently returned `balance` from RPC doesn't account for non subtracted yet storage rent.
We should rename that into something like `onchain_balance` and make `balance` = `onchain_balance - storage_price * storage_usage * (height - storage_last_updated_at)`.

See section 4.3 of https://near.ai/economics for details on storage rent and `charge_rent` for actual function of how rent is updated.

CC: @kcole16

**Comment by fckt** [comment]
When client be able to [read config trough RPC](https://github.com/nearprotocol/nearcore/issues/2007), then it'll be able to compute spendable balance on `nearlib` side and save unnecessary PRC call for the actual_amount for each time client want to send a transaction. I think also client would want to use not the current `block_height` for this, but `block_height` + `genesis.transaction_validity_period` to cover risk of TX being included with a delay.

@frol @nearmax @ilblackdragon

**Comment by nearmax** [comment]
Talked to our customers that requested this feature, they actually suggested to compute the real balance on the front-end side.

Also, @frol had a concern that if we expose this through RPC it will create an intense RPC traffic, because real balance will be changing every second and so front-ends will be querying it frequently.

Closing this issue in favor of https://github.com/nearprotocol/nearcore/issues/2007

**Comment by ilblackdragon** [comment]
I don't fully agree with reasoning that ppl will keep calling RPC for recent balance in case if it is computed. They will keep calling it whenever they needed.

We still should return the lazy computed balance to allow frontends to compute the current balance at any block in the future (which is just an approximation always, as money can be added or sent from another place).

Also we should add issues tracking to nearlib and near she'll to show current balance if we are deciding to compute it on the front end.

**Comment by fckt** [comment]
Ok, what if instead of changing of the meaning of the `amount` property we add a `spendable_amount` or even better add a `unpaid_rent` to make more clear?

**Comment by frol** [comment]
In any case, let me first finish #2007 (the PR will be ready today), which will make genesis and runtime configs available in jsonrpc.

**Comment by frol** [comment]
This is blocked on the decision for #2272.

**Comment by ilblackdragon** [comment]
Closed due to #2272
