### ISSUE TITLE
Progressive slashing for double signing

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#1830]
Currently we slash 100% of the stake right away.
Discussion of pros and cons of 100% slashing: https://forums.solana.com/t/100-slashing-a-proposal-discussion/256/3

Double signing blocks has largest risk on misconfiguration and software issues.
Suggestion for double sign to slash in next way:
 - As soon as double sign challenge is recorded, the validator is jailed.
 - At the end of epoch, slashing happens is 3x the total value of the stake that double signed within that epoch.

This means that if 33% of stake double signed - all 33% get slashed. If only 1% of stake has double signed - only 3% of it will be slashed.

**Comment by nearmax** [comment]
> This means that if 33% of stake double signed - all 33% get slashed.

Is this a typo? It should be:

This means that if 33% of stake double signed - all 100% get slashed.

**Comment by bowenwang1996** [comment]
I think it meant all of that 33% stake is slashed, but it could be more clear.

**Comment by ilblackdragon** [comment]
Correct, all 100% of that 33% should be slashed.

**Comment by ilblackdragon** [comment]
Implemented.
