### ISSUE TITLE
Investigate check_blocks_on_same_chain

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#1836]
@nearmax has concerns about `check_blocks_on_same_chain`

**Comment by bowenwang1996** [comment]
What is the concern?

**Comment by evgenykuzyakov** [comment]
It's in https://github.com/nearprotocol/nearcore/pull/1756

**Comment by nearmax** [comment]
https://github.com/nearprotocol/nearcore/pull/1756#discussion_r353460037

**Comment by SkidanovAlex** [comment]
We need to significantly improve our bug reporting skill, it easily took me at least five minutes to even find what Max was concerned about.

Max was concerned that the test calls to `check_blocks_on_same_chain` in place where we need to check that a particular block is in the ancestry of another block. Indeed, this is what `check_blocks_on_same_chain` does, so there's no issue (besides somewhat confusing naming).
