### ISSUE TITLE
near login have an error 

### ISSUE THREAD

**Issue by wetezos** [nearprotocol/nearcore#1860]
near version:near-shell@0.16.0

login error:

Please enter the accountId that you logged in with:wetez
Error: Querying access_key/wetez/ed25519:6HfPNi9CCv3a2cEbskxwsWAuSGVxLknsDzYn2CF7hW4u failed: access key ed25519:6HfPNi9CCv3a2cEbskxwsWAuSGVxLknsDzYn2CF7hW4u does not exist while viewing.
{
  "block_height": 102120,
  "error": "access key ed25519:6HfPNi9CCv3a2cEbskxwsWAuSGVxLknsDzYn2CF7hW4u does not exist while viewing",
  "logs": []
}
    at JsonRpcProvider.query (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/lib/providers/json-rpc-provider.js:40:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by ilblackdragon** [comment]
Issue moved to [nearprotocol/near-shell #242](https://github.com/nearprotocol/near-shell/issues/242) via [**ZenHub**](https://www.zenhub.com/)
