### ISSUE TITLE
100 node block production test

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#1870]
We want to test cross-region 100 block producing nodes setup.

As the first step we just want to make sure the nodes collectively can even produce blocks.
We should spin up 100 nodes, wait for some time, and then collect the info about approvals and chunks.

For that at the end we should query an arbitrary node for status, the status would contain the latest block hash, from there we should be querying blocks from that hash traversing `prev_hash`-es, and collecting approvals (they are in the output of `/block`), and chunks if we have an endpoint for that, as well as the heights of the blocks to understand how many blocks are skipped.

**Comment by ailisp** [comment]
In #1876

**Comment by ilblackdragon** [comment]
I'm assuming this is done. If don't agree, feel free to reopen and clarify what is missing.
