### ISSUE TITLE
start_testnet script very slow after restart

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#1872]
Node gets stuck if we stop the node and restart using `./scripts/start_testnet.py`. It looks like the node gets stuck when reading data from database.

**Comment by ailisp** [comment]
Looks like it only happens to docker

**Comment by ailisp** [comment]
view_client sounds not like something that should stuck. did we make some breaking changes there?

**Comment by ailisp** [comment]
After profiling from topdown , this function takes too long, it's been called ~ 5000 times each shard when do the insert ~ 5000 times, which takes about 30 seconds. So eight shard total about 4 minutes. Other functions are takes almost no time to finish
```
    pub fn retrieve_rc(&self, hash: &CryptoHash) -> Result<u32, StorageError> {
        let mut guard = self.cache.lock().expect(POISONED_LOCK_ERR);
        if let Some(val) = (*guard).cache_get(hash) {
            Self::vec_to_rc(val)
        } else {
            let val = self
                .store
                .get(ColState, hash.as_ref())
                .map_err(|_| StorageError::StorageInternalError)?;
            let rc = Self::vec_to_rc(&val);
            (*guard).cache_set(*hash, val);
            rc
        }
    }
```
too slow

**Comment by ailisp** [comment]
more profile shows all times spent in cache miss branch. so get 5k times is expensive. probably should batch get

**Comment by ailisp** [comment]
Since not really caused by script, close and open a more relevant issue in #1883
