### ISSUE TITLE
Very slow in retrieve_rc when restart testnet node

### ISSUE THREAD

**Issue by ailisp** [nearprotocol/nearcore#1883]
It takes ~8 minute to restart a testnet node, as profile, almost all time spent in retrieve_rc. And within retrieve_rc, all time is spent in store.get (452.527806346s). This is the total time of about `5000*8*2` get. Batch get maybe save time here (unsure), but rust-rocksdb also doesn't have multiget:
https://docs.rs/rocksdb/0.13.0/rocksdb/?search=multiget
https://github.com/facebook/rocksdb/wiki/Basic-Operations#reads-and-writes

**Comment by ailisp** [comment]
@mikhailOK Steps to reproduce:
1. remove `~/.near`, `scripts/start_testnet.py --nodocker`, this starts reasonably fast
2. exit, `script/start_testnet.py --nodocker` again, this time it's very slow, takes about 8 minutes.

It doesn't related to script, it's same if you replace step 1-2 with `target/debug/near run --boot-nodes one-of-testnet-node`. if run without boot-nodes it's fast.

Some initial investigation:
https://github.com/nearprotocol/nearcore/tree/profile-restart

I put some print, some counter, which shows all time is spent in retrieve_rc's store.get branch.

Hope above can save you some time.

**Comment by nearmax** [comment]
5.7ms per store.get is very significant. It is known that we can do 1k-2k tps with financial transactions since each transaction requires at least two store.get the base overhead of reading from storage is much less than 5.7ms.

Is it possible that we missinterpret the profiler something else is happening? E.g. is it possible that we are waiting for rocksdb to startup (it uses subprocesses) and first few store.get are just blocked on it, resulting at the average time per store.get to be high?

**Comment by ilblackdragon** [comment]
Yeah, I thought it’s related to the rocks db starting - because it feels like this started since we switched to our own rocks-db wrapper.

But! it seems like it takes long time both times when Client and ViewClient start (both create Chain / ChainStore object).

**Comment by nearmax** [comment]
Assigning to @ailisp since it is more likely to be a problem of a rust-rocksdb startup rather than the implementation of the trie.

**Comment by ailisp** [comment]
It's probably misread of benchmark and start time, but one fact likely shows not this case: the retrieve_rc is called ~5000 times per shard. All shards saved in same rocksdb column family. I was separately benchmark these 8 shards one by one. Every shard takes ~30s for 5000 retrieve_rc. If, it's related to start time, in the first, or first few shard it should have been slower than later shards. What do you think?

**Comment by ailisp** [comment]
I also suspect it doesn't happen likely because of these two reasons:
1) testnet initial accounts were not that many (this was firstly happened after last time testnet genesis update)
2) I poorly configured rust-rocksdb

**Comment by ailisp** [comment]
Some updates on this, I add trace to DB::get:
```
impl Database for RocksDB {
    fn get(&self, col: DBCol, key: &[u8]) -> Result<Option<Vec<u8>>, DBError> {
        let t = Instant::now();
        let r =
            unsafe { Ok(self.db.get_cf_opt(&*self.cfs[col as usize], key, &self.read_options)?) };
        let e = t.elapsed();
        println!("db get {:?} {:?} -> {:?}", col, key, e);
        r
    }
```
In the first run after cleaning ~/.near, every get takes only several mu seconds, so it boot fast. But second run get is 20-30ms, and time/get does not decrease as time increase. The reason is unknown yet.

**Comment by nearmax** [comment]
Is this fixed now?

**Comment by ailisp** [comment]
I think so, but in testnet node would be fix at next release
