### ISSUE TITLE
Use HashSet<obj> instead of HashMap<hash, obj> for structs that have hash as a field

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#189]
This is more efficient and less error-prone, because we don't have to deal with the keys explicitly. See discussion here: https://github.com/nearprotocol/nearcore/pull/159#discussion_r240836710

**Comment by bowenwang1996** [comment]
I don't think this can be done because `HashSet::remove` does not return the value removed, which is needed here https://github.com/nearprotocol/nearcore/blob/b9b729c27090f3bb18f1a5262d4d4a07b2a7b83f/node/client/src/lib.rs#L376

**Comment by nearmax** [comment]
Use `take` for that.
