### ISSUE TITLE
Total peers pass 40

### ISSUE THREAD

**Issue by ailisp** [nearprotocol/nearcore#1893]
In a 100 node test I saw:

![image](https://user-images.githubusercontent.com/13259400/71317339-13f5da00-2434-11ea-951b-2f5ad0e9a728.png)

**Comment by ailisp** [comment]
seems not off one:
![image](https://user-images.githubusercontent.com/13259400/71318762-1bc07900-244a-11ea-9bb0-da4a389c129a.png)

**Comment by bowenwang1996** [comment]
@mfornet is it possible that we don't prevent other peers from connecting to us even if we have reached maximum number of peers?

**Comment by mfornet** [comment]
Solved in #1897
