### ISSUE TITLE
Smart Contract bug: `NEAR Error: ActionError::FunctionCallError / PrepareError: Gas instrumentation failed.")`

### ISSUE THREAD

**Issue by kaiba42** [nearprotocol/nearcore#1901]
Steps to reproduce:
*assumes setup of near-shell*

- Start local testnet
    1. `git clone https://github.com/nearprotocol/nearcore`
    2. `git checkout locked_balance`
    3. `python ./scripts/start_localnet.py`
    4. Enter your desired accountId: `master123`

- Deploy contract code
    1. `git clone https://gitlab.com/rainbolt-labs/rainbolt-near.git`
    2. `git checkout ka.updating_deps`
    3. `cargo +nightly build --target=wasm32-unknown-unknown --release`
    4. *setup near-shell*
    5. `near create_account escrow_test8 --masterAccount=master123 --initialBalance=1000000000000000000000`
    6. `near deploy --accountId escrow_test8 --masterAccount master123 --wasmFile "../rainbolt-near/target/wasm32-unknown-unknown/release/rainbolt_near.wasm"`

- Call contract method via Rust client
    1. `git clone https://gitlab.com/rainbolt-labs/rainboltd`
    2. `git checkout ka.updating_deps`
    3. `cargo b`
    4. Edit the file in *rainboltd*/config.json:
    ```json
    {
        "chains": [{
            "chain_id": "near",
            "account_id": "master123",
            "secret_key": "<PASTE KEY FROM ~/.near/validator_key.json> e.g. ed25519:3kftAGfFgvE5AZ6Jevh99qgb77xLynd3xf86P7HRkqfk6ajPyCo7mnhU8QpTfSFYzrqennEGeL25WmJtaCzKF9y8"
        }],
        "channel_ip": "http://localhost:3031"
    }
    ```
    5. Run the client using `./target/debug/rainboltd -c ./config.json `
    5. Use Postman or curl to make a GET request to `http://127.0.0.1:3031/maker/init/1/near`

- Observe output
`Unhandled rejection: ChainErr("NEAR Error: ActionError::FunctionCallError / PrepareError: Gas instrumentation failed.")`

**Comment by nearmax** [comment]
I cannot access the repo
```
% git clone https://gitlab.com/rainbolt-labs/rainbolt-near.git
Cloning into 'rainbolt-near'...
Username for 'https://gitlab.com': nearmax
Password for 'https://nearmax@gitlab.com': 
remote: You are not allowed to download code from this project.
fatal: unable to access 'https://gitlab.com/rainbolt-labs/rainbolt-near.git/': The requested URL returned error: 403
```

but you should try again. This time checkout `staging` branch and run `./scripts/start_localnet.py --local`
