### ISSUE TITLE
test_cargo fails because of cached nearcore/chain/jsonrpc/src/lib.rs

### ISSUE THREAD

**Issue by Kouprin** [nearprotocol/nearcore#1902]
<img width="856" alt="Screenshot 2019-12-27 at 20 07 01" src="https://user-images.githubusercontent.com/5685493/71541113-15536500-2954-11ea-8fb3-ff3405512a9f.png">

Example: https://gitlab.com/near-protocol/nearcore/-/jobs/389881785

**Comment by nearmax** [comment]
cargo fmt failed and it tell exactly what is wrong. This is not a bug of CI, please run cargo fmt --all on your code.

**Comment by Kouprin** [comment]
> cargo fmt failed and it tell exactly what is wrong. This is not a bug of CI, please run cargo fmt --all on your code.

OK, got it. I didn't familiar with cargo fmt and the fact that it's blocking CI execution.
