### ISSUE TITLE
cross shard state verify

### ISSUE THREAD

**Issue by rabbitHX** [nearprotocol/nearcore#1906]
hi:
  I read through near src code, there is a key point I didn't get that how receiver verify sender's state ? 
example:
alice on shard A
bob on shard B
A new receipt R1 is alice transfer 1 token to bob, so shard A sub 1 token of alice and generate a cross shard receipt R2 to add 1 token of bob, when shard B processing R2 how it know shard A has sub 1 token of alice correctly? As I know shard B has no alice's state data. I search src code and there only verify receipt_root but no sender's state data, so how this problem resolved?

**Comment by bowenwang1996** [comment]
Because the validators in shard A have committed the state root into the shard header and have signed on it. If you are talking about the case where the entire shard is corrupted, we then rely on fishermen to challenge the invalid state transition.

**Comment by rabbitHX** [comment]
Assuming ignore fishermen mechanism, we just trust shard A's validators,this is the answer?

**Comment by bowenwang1996** [comment]
Yes
