### ISSUE TITLE
P2P should not be blocking node

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1914]
On 2019-01-02 at about 10AM PST we had a situation where an RPC of the node was irresponsive. Upon closer examination of the testnet node we have observed two things:
* The node was consuming 100% of a single core;
* There were large spikes of outgoing traffic from the testnet node towards some other node over p2p port. The spikes were in 15sec intervals see: https://www.dropbox.com/s/gp0hnhehgb0kjjx/Screenshot%202020-01-02%2014.55.20.png?dl=0

After we blocked this other node through iptables the RPC became responsive again and the cpu load dropped to ~10% for a single core. This is indicative of our testnet node being somehow abused from p2p network in such way that it causes it to send large amounts of data to some other node while simultaneously blocking RPC. This should not be allowed.

**Comment by mfornet** [comment]
Was the other node intentionally attacking the network or was running our code?

**Comment by nearmax** [comment]
> Was the other node intentionally attacking the network or was running our code?

Unclear.

**Comment by bowenwang1996** [comment]
No they are just running our code :)

**Comment by Kouprin** [comment]
https://github.com/nearprotocol/nearcore/issues/1926 is related to the issue

**Comment by Kouprin** [comment]
@bowenwang1996 is it solved now?

**Comment by bowenwang1996** [comment]
Should be
