### ISSUE TITLE
migrate-from-0.3.py is broken

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1920]
As reported by @evgenykuzyakov it is inconsistent with `testnet.json`
It uses
```
q['runtime_config']['wasm_config']['runtime_fees']['ext_costs'] = ext_costs
```
But we don’t have runtime_fees anymore

**Comment by bowenwang1996** [comment]
Is it a huge concern? The script is used to migrate from 0.3.* to 0.4.0 but we are already at 0.4.11

**Comment by evgenykuzyakov** [comment]
I'm going to start a new mega-migration script that moves from 0.4.* to 0.* by introducing a new `minor_config_version` that is only used for migrations (in addition to `protocol_version`)

**Comment by evgenykuzyakov** [comment]
Part of https://github.com/nearprotocol/nearcore/pull/1913

**Comment by ilblackdragon** [comment]
I think we should be removing the previous migration script when we are creating one for the next version. So let's remove this `migrate-from-0.3.py` file. @nearmax

**Comment by nearmax** [comment]
It is now a part of https://github.com/nearprotocol/nearcore/pull/1913. Closing.
