### ISSUE TITLE
BlockHeader should depend on challenges

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#1921]
If yes, feel free to close the issue.
Otherwise reassign to KPR.

**Comment by bowenwang1996** [comment]
It should but doesn't right now

**Comment by Kouprin** [comment]
> It should but doesn't right now

But it still depends on challenges of previous block, right? There is `challenges_result` in `BlockHeaderInnerRest`.

**Comment by bowenwang1996** [comment]
@Kouprin I don't think it is enough. There should not be two different blocks with the same hash.

**Comment by SkidanovAlex** [comment]
So effectively the scope of the task:

1. Add some sort of hash of challenges to the block header (doesn't need to be merklized, but I don't think we lose anything if we make it a merkle hash).
2. Add validation in `process_block` that verifies the hash matches the challenges.
