### ISSUE TITLE
Block fork question

### ISSUE THREAD

**Issue by rabbitHX** [nearprotocol/nearcore#1924]
Hi:
According to src code, we assume a block contain a invalid chunk (produced by a evil cp), this block then received by two validators in different shard. cp_A (in shard A) care about this invalid chunk and apply it but failed(because chunk is invalid), so block won't be added by cp_A. On the other hand, cp_B(in shard B) don't care about this invalid chunk(so cp_B just skip check invalid chunk), so block will added by cp_B. Now is the problem : cp_A's block chain is different with cp_B.
Is this a problem? If it is, how to resolve it (by challenge) ?

**Comment by bowenwang1996** [comment]
If there is an invalid chunk included in a block, an honest validator or fishermen will send a challenge and after the challenge is verified, the challenged block will be marked as invalid and the fork choice rule will not respect the chain that contains an invalid block.

**Comment by rabbitHX** [comment]
> If there is an invalid chunk included in a block, an honest validator or fishermen will send a challenge and after the challenge is verified, the challenged block will be marked as invalid and the fork choice rule will not respect the chain that contains an invalid block.

Thank you, another question, the chain contains an invalid block will be reverted so is there a guarantee to ensure a transaction in final state (irreversible) ? if no irreversible mechanism, any block may reverted due to challenge, the chain's usability is low, how this problem treated?
@bowenwang1996

**Comment by bowenwang1996** [comment]
The finality gadget guarantees that a block which is finalized cannot be reverted unless 1/3 stake is slashed. Are you talking about the case when there are more than 1/3 malicious actors?

**Comment by rabbitHX** [comment]
No, I just want to know if there have finality (irreversible) mechanism, so when the block finality triggered ?

**Comment by bowenwang1996** [comment]
There is a finality gadget that finalizes blocks based on approvals. Under normal circumstances a block should be finalized after 3 blocks.

**Comment by rabbitHX** [comment]
Thank you very much, so this is mean a challenge for a block must be done in 3 blocks ?
