### ISSUE TITLE
Only instantiate ReedSolomon once

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#1925]
Now that `num_data_parts` and `num_total_parts` don't have any arguments in `runtime_adapter`, we should remove the instantiation of `rs` from `EncodedShardChunkBody::reconstruct`, and only instantiate it once when `Client` is instantiated.

It is OK to still instantiate `rs` from scratch in tests, where there's no client, and I think there's one place in challenges that doesn't have access to the `client`, where it's also OK to create the `rs` on the spot.

In all other places `rs` should come from the caller. Whenever we pass `rs` we should remove `total_parts` and `data_parts` arguments, and get them from `rs`.

**Comment by ailisp** [comment]
Fixed in #1929
