### ISSUE TITLE
Invalid block chain should be banned

### ISSUE THREAD

**Issue by Kouprin** [nearprotocol/nearcore#1936]
For reproducing the issue, check test `malicious_chain.py` from https://github.com/nearprotocol/nearcore/pull/1933/files. It should be executed with no parameter `valid_blocks_only` to produce invalid blocks.

Check method `adv_produce_blocks` in `adversary` branch. It helps to create a chain of 50 blocks from the available head. This way of block creation ignores `next_block_proposer` value and sends all created blocks to a peer.

Ignoring `next_block_proposer` should be banned instantly. However, the honest node updates `latest_block_height` up to those 50 blocks before banning.

**Comment by ilblackdragon** [comment]
What is the status here @Kouprin ? I'm assuming this is blocking MainNet?

**Comment by Kouprin** [comment]
@ilblackdragon it's fixed since Doomslug is introduced
