### ISSUE TITLE
Re-enable ".with_forbidden_floats" for WASM prepare after AS fix 

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#194]
.with_forbidden_floats should be enabled to prevent undefined behaviour for different WASM platforms.

Currently AssemblyScripts uses f64 for some formatting. Once we remove it from the boilerplate we can re-enable float ban.

**Comment by ilblackdragon** [comment]
@evgenykuzyakov what's the status / priority on this?

**Comment by evgenykuzyakov** [comment]
We need to cleanup AssemblyScript from using floats in default modules. E.g. from string. After this we can try to reenable it

**Comment by ilblackdragon** [comment]
Are floats still enabled?

**Comment by vgrichina** [comment]
@ilblackdragon yes, still enabled.

**Comment by ilblackdragon** [comment]
@evgenykuzyakov @vgrichina pinging this item.

**Comment by nearmax** [comment]
AssemblyScript fix is merged: https://github.com/AssemblyScript/assemblyscript/pull/733
We can re-enable the check now.
