### ISSUE TITLE
Initial near run use too many open files

### ISSUE THREAD

**Issue by ailisp** [nearprotocol/nearcore#1942]
it uses more than 1024, linux system default, recently and we have to raise ulimit. It shouldn't this many

**Comment by mfornet** [comment]
I can't run several tests at the same time in clion because of this problem. I should run them separately.

**Comment by ailisp** [comment]
before i fix it, you can update system ulimit in /etc/security/limits.conf.
I cannot even run single test :)

**Comment by ailisp** [comment]
Seems maybe related to recent tokio/mio update? it has 1802 open files, of them 1647 are something like:
```
near    6237   bo 1783r      REG                0,4         0  217208 /proc/6237/task/6796/stat
```

**Comment by ailisp** [comment]
Seems to be a "bug" in sysinfo crate: https://github.com/GuillaumeGomez/sysinfo/issues/242
