### ISSUE TITLE
Progressive Updates for Validators

### ISSUE THREAD

**Issue by potatodepaulo** [nearprotocol/nearcore#1951]
This is more philosophical than a specific feature. We need a strategy for elegantly upgrading nodes. 
Requirements:
- Minimize downtime per node 
- Minimize lost stake per validator
- Create incentive for nodes to upgrade efficiently/quickly

**Comment by nearmax** [comment]
The first two items are addressed by https://github.com/nearprotocol/nearcore/pull/1962 the last one is a separate discussion on upgradability that we currently have between runtime and chain teams.
