### ISSUE TITLE
Logs aren't captured if view calls panics

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/nearcore#1953]
### Fiddle
https://studio.nearprotocol.com/?f=rgb9hvqmn

### Steps to reproduce
1. Go to https://app.near.ai/app/rgb9hvqmn/
2. Execute `contract.getCounter()` in browser console.

### Expected behavior

1. Logs before panic appear. (`logging.log('getCounter');`)
2. Descriptive error is returned with info on where the contract code panicked (there is file and line info on AssemblyScript side).

### Actual behavior

1. No logs appear.
2. Error returned is `wasm execution failed with error: FunctionCallError(HostError(BadUTF16))`

**Comment by nearmax** [comment]
@bowenwang1996 Is this fixed?

**Comment by bowenwang1996** [comment]
Fixed
