### ISSUE TITLE
Remote transaction signing

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#1967]
We need to add some rpc/http endpoint for transaction signing.

**Comment by nearmax** [comment]
Please describe the use case in more detail.

**Comment by fckt** [comment]
Something like a signing proxy?

**Comment by frol** [comment]
@bowenwang1996 I don't understand how this could work. Do we expect someone to send us their private key to sign a transaction?

**Comment by bowenwang1996** [comment]
No it's would be an endpoint where HSM is hosted. There is some trust involved.

**Comment by ilblackdragon** [comment]
@bowenwang1996 I don't think nearcore should be signing any transactions.
We can have crates for signing tx with HSM and have binaries (CLI, restaking services, etc), but nearcore should not have RPC for signing - this is just a huge security hole.

Closing this, if disagree - please reopen.
