### ISSUE TITLE
Node hangs on smart contract non-view call

### ISSUE THREAD

**Issue by k06a** [nearprotocol/nearcore#1973]
See an attached sampling of what all threads are doing:
- [near_sampling.txt](https://github.com/nearprotocol/nearcore/files/4076389/near_sampling.txt)
- [near_sampling2.txt](https://github.com/nearprotocol/nearcore/files/4076395/near_sampling2.txt)

Not sure we have matches in 2 samplings, so maybe the problem is related to `nearlib`.

**Comment by k06a** [comment]
I tried to view-call a non-view method, we need to show related error @vgrichina, @janedegtiareva, @nearmax

**Comment by bowenwang1996** [comment]
Interesting. There is no error message? Is it a single call or part of some cross-contract call?

**Comment by k06a** [comment]
@bowenwang1996 it was single call and it seems it was stuck in `nearlib`.

**Comment by bowenwang1996** [comment]
That definitely seems like a bug. Can you reproduce it?
