### ISSUE TITLE
Lockup Contract Implementation

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1992]
- [ ] Implement safe balance math;
- [ ] Finish implementation of lock up and vesting contract;
- [ ] Add unit tests;
- [ ] Add pytests that attempt various scenarios, e.g. trying to transfer locked token etc.

**Comment by evgenykuzyakov** [comment]
nearprotocol/nearcore#1714

**Comment by ilblackdragon** [comment]
@evgenykuzyakov We just get a request to allow to switch keys for locked account in case of needing to switch custody. This can be done with authorization of NF.
E.g. we can allow NF to call `switch_key(new_public_key)` function on locked account.

**Comment by nearmax** [comment]
Discussed during middleware sync: https://github.com/near/community/blob/master/meetings/middleware-wg.md#initial-contract the implementation is done. Closing this issue
