### ISSUE TITLE
Add "tail" and GC old blocks / chunks

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#1998]
Add a new field to the chain which is the "tail" of the current chain, in other words how far back do we know the blocks.

We should maintain an invariant that the "tail" is always in the ancestry of "head". The tail should be several epochs in the past from "head" (say 5 epochs).

We should move the tail periodically (either every time head changes, or once head crosses an epoch boundary?). When we move the tail, we should garbage collect all the information assoaciated with the blocks that fell behind the tail. That includes blocks, chunks, chunk extra etc.

**Comment by Kouprin** [comment]
Discussed offline. No tail will be added, only GCing old data.
