### ISSUE TITLE
Fix FunctionCallError(WasmTrap("unknown"))

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2009]
Currently when contract fails we return a non-descriptive error message `FunctionCallError(WasmTrap("unknown"))` we were not able to return a more descriptive message because it was not supported by Wasmer Singlepass: https://github.com/wasmerio/wasmer/issues/903

However, now it is fixed: https://github.com/wasmerio/wasmer/pull/1129

We should update to the new version of Wasmer+Singlepass and make sure this error message is now descriptive in our RPC by writing a test.

**Comment by nearmax** [comment]
Moving it to in progress since I know that @fckt is currently working on it.

**Comment by fckt** [comment]
With https://github.com/nearprotocol/near-bindgen/pull/73 @evgenykuzyakov implemented Rust will call a `panic` extern on panic. How we expect panics to return the `FunctionCallError::HostError::GuestPanic{ panic_msg: String }`.
