### ISSUE TITLE
ActionErrorKind doesn't provide index for ActionError

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#2012]
There are a lot of places where we throw `ActionErrorKind` and then use `.into()`. This doesn't provide the action index. I think we can fix it in `Runtime::apply_action_receipt` by checking if `result.result.is_err()` and it's an `ActionError` and then insert the actual action index into the error.

**Comment by fckt** [comment]
Take a look: 
https://github.com/nearprotocol/nearcore/blob/staging/runtime/runtime/src/lib.rs#L482

**Comment by nearmax** [comment]
Closing since the action index is in `ActionError` struct.
