### ISSUE TITLE
RPC query account information and access keys by a specific block id

### ISSUE THREAD

**Issue by frol** [nearprotocol/nearcore#2015]
*This issue supersedes #2008.*

Our clients want avoid the following race condition that can happen on RPC:

Suppose we want to query both the account info and the access keys of the account at the same time. Unfortunately, these are available through separate RPC requests. They can issue request for account state (suppose they get state at block X), but then when they query access keys get them at block X+Y. They try to re-query the state, but now it is at the block X+Y+Z, etc. This DevX does not seem nice, it would be better if they could issue a query targeting a specific block hash.

**Comment by frol** [comment]
@nearmax The PR is merged, and there is a follow up issue on the Docs repo. What is our current process of handling issues from nearcore? Do we close them?

**Comment by amgando** [comment]
this was published
https://docs.nearprotocol.com/docs/api/rpc-params

see here for history
https://github.com/nearprotocol/docs/pull/252
