### ISSUE TITLE
Expose genesis JSON via RPC

### ISSUE THREAD

**Issue by frol** [nearprotocol/nearcore#2025]
NEAR Explorer requires this to display all the accounts (including the ones only touched / created in genesis)

/cc @icerove @kcole16 @nearmax

**Comment by nearmax** [comment]
We should take into account the fact that the state records from the genesis are too large to be returned all at once.

Also, I am not sure we need a separate RPC API for this. Events already allow querying accounts that were created in genesis.

**Comment by frol** [comment]
*Just documenting the offline conversation.*

> Events already allow querying accounts that were created in genesis.

1. We don't expose the list of accounts
2. The block #0 does not include genesis changes; those go to "block # -1", AFAIK

**Comment by frol** [comment]
@amgando https://github.com/nearprotocol/nearcore/pull/2109 has relevant examples of `EXPERIMENTAL_genesis_records` API call

**Comment by amgando** [comment]
this can be closed
https://github.com/nearprotocol/docs/pull/253
https://docs.nearprotocol.com/docs/api/rpc-experimental
