### ISSUE TITLE
Are some shards more equal than others?

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#2028]
E.g. I'm shard #2. I'm trying to combine incoming receipts from shard #0 and shard #1. Are receipts from shard #0 going to have a priority on top of receipts from shard #1? 
@bowenwang1996

**Comment by bowenwang1996** [comment]
That's right. Even though all shards are equal, some are more equal than others.

**Comment by mfornet** [comment]
Randomness?
