### ISSUE TITLE
Invalid transactions dropped from the pool don't have the error

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#2039]
When a frontend send 2 transactions with the same nonce, both of them are accepted by the node and added to the pool. Then when a block is being produced, one of the transactions become invalid and is dropped from the pool. There are no way to notify the front-end about the results of the transaction or what error caused the transaction to being dropped.

**Comment by bowenwang1996** [comment]
Related issue: #2040

**Comment by bowenwang1996** [comment]
@evgenykuzyakov it looks like this is causing a lot of pain for the applayer. Is there a good way to address it?

**Comment by bowenwang1996** [comment]
Also we need to decide on whether we need to solve this before mainnet as it might not be trivial to do. @vgrichina @kcole16

**Comment by evgenykuzyakov** [comment]
We have 2 issues that makes the design complicated. Transactions are not shared with everyone, so everyone has a different mempool. Once you hit tx-status you might land on someone else node which is not aware of tx-hash.

The solution would be to have a temporary information required to query the status of the transaction. It should be given in addition to tx-hash and every node should be able to use it to forward the tx-status query

This information can be a list of validators which received the transaction and added it to the mempool. It still unknown which validator would actually use the transaction and mark it invalid. Eventually every validator from the list will have some kind of tx-result error.

This error can be cached without being recorded on-chain, because it’s a helper answer only, since the transaction was actually invalid. I guess it’s the same way as it works right now

**Comment by bowenwang1996** [comment]
@evgenykuzyakov I think that partially solves that problem. However, when the network is slow it will still timeout and you cannot distinguish between whether that is because transaction hasn’t been processed yet or because the transaction is dropped due to invalid nonce or the transaction doesn’t exist.

**Comment by ilblackdragon** [comment]
What we can do:
 - If sender of transaction got timeout, they should reach out to any node that tracks the shard this transaction suppose to hit
 - And ask for "is this transaction valid" question (new RPC).
 - This would either respond with:
    - Yes, transaction is valid - which means this tx might still be in the pool of validators and will be included shortly. Keep polling on `tx_status` and this RPC call.
    - No, and it will return the error for this specific transaction.

E.g. RPC node can locally just call verify transaction and return the error that it provides.

**Comment by vgrichina** [comment]
> If sender of transaction got timeout, they should reach out to any node that tracks the shard this transaction suppose to hit

@ilblackdragon this just delayed sender for 10 seconds for no good reason. E.g. I'm using the same web app from 2 different browser tabs – so every once in a while nonces can collide (all that is needed for this is a bit of lag and user switching between tabs). This will mean waiting more than 10 seconds to recover from this trivial issue which shouldn't require user input (for transactions which don't require wallet signing).

Given that nearcore has troubles implementing actually usable long-polling (i.e. with errors being propagated and RPC not stalling block production) – I suggest we kill it altogether and poll client-side.

For this we need:
1) async submit tx (already implemented)
2) tx-status need to be returning immediately (not implemented yet)
3) "is this transaction valid" question (new RPC) – BTW, I don't understand why exposing this is much easier than returning error when transaction is being submitted.

**Comment by vgrichina** [comment]
> However, a transaction can later become invalid after it is submitted and before it is included in a chunk. That's why we need to query whether it is still valid.

still not clear why it is hard to make it happen on nearcore side before we return Timeout to client

**Comment by bowenwang1996** [comment]
It can take longer than the timeout (10s) to tell.

**Comment by frol** [comment]
Yet, sometimes it takes less than 10s and currently we still get the request blocked even though we could have already returned the error

**Comment by vgrichina** [comment]
> It can take longer than the timeout (10s) to tell.

yes, in that case it is expected you return Timeout. What is not expected is to wait 10 seconds to get Timeout for situation where error was likely detected in less than 1 second (just not propagated).
