### ISSUE TITLE
Failed to query account changes

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2048]
Customer encountered the following bug. We need to do two things:
- [x] Try to reproduce and debug it;
- [x] Allegedly when someone sends changes RPC request to staging node it either hangs or crashes. We need to investigate it;
- [x] Independently on whether we can reproduce it or not create an example that uses `near-shell` and `curl` to create an account and query the changes for that account.
- [ ] Create a thorough documentation on how to use it.

From the customer:
> We executed a `create_account` tx with hash: `794Edr3MYhpZEQeaqMGzauQ6VHNWQAzMuz9SiRSfR2Ux` that was executed on block with hash: `7jPYQ33xfJ9XUGP5isybXkdnPhGFzYWnKjtLb4fa6KU` Using the changes endpoint we are trying to find the updates to the sender account's balance. We've tried fetching the `account_changes` for the sender account on that block hash, but got an empty result. We also tried fetching data_changes on the `account_id` but are unsure of the correct `key_prefix`.

> Example account_changes request:
```
curl --request POST \
  --url http://<removed>:3030/ \
  --header 'content-type: application/json' \
  --data '{
	"jsonrpc": "2.0",
	"id": 1,
	"method": "changes",
	"params": [
		"7jPYQ33xfJ9XUGP5isybXkdnPhGFzYWnKjtLb4fa6KU",
		{
			"changes_type": "account_changes",
			"account_id": "near_originator"
		}
	]
}'
```

> Example data_changes request:
```
curl --request POST \
  --url http://<removed>:3030/ \
  --header 'content-type: application/json' \
  --data '{
	"jsonrpc": "2.0",
	"id": 1,
	"method": "changes",
	"params": [
		"7jPYQ33xfJ9XUGP5isybXkdnPhGFzYWnKjtLb4fa6KU",
		{
			"changes_type": "data_changes",
			"account_id": "near_originator",
      "key_prefix": [109, 121, 107, 101, 121]
		}
	]
}'
```

**Comment by frol** [comment]
I was able to reproduce the error. Digging into it further.

Here are the commands I use (just for the reference):

```
$ env NODE_ENV=local near --keyPath /home/frol/projects/nearcore/localnet-data/validator_key.json create_account --masterAccount test.near new-account0
```

Then, I use `storage_paid_at` block height from the account information retrieved with:

```
$ env NODE_ENV=local near state new-account0

{
  amount: '100000000000000000000000',
  locked: '0',
  code_hash: '11111111111111111111111111111111',
  storage_usage: 182,
  storage_paid_at: 48609,
  block_height: 49849,
  block_hash: '2HP6uRCxA6urT2FZbxPCrJX1fJkQ4qwMUex9qaN7QYs5',
  formattedAmount: '0.1'
}
```

Having block height, we get block hash using `block` RPC call (we don't have near-shell shortcut to do this), so here is [httpie](https://httpie.org/) command:

```
$ http post http://localhost:3030 jsonrpc=2.0 id=dontcare method=block 'params:=[48609]'

{
    "id": "dontcare",
    "jsonrpc": "2.0",
    "result": {
        "author": "test.near",
        ...
        "header": {
            ...
            "hash": "NTLc3KhpLsPpUVzgapwEbL7oBNfAYad623sRzJ83JYV",
            "height": 48609,
            ...
        }
    }
}
```

Finally, query for the changes:

```
$ http post http://localhost:3030/ jsonrpc=2.0 id=dontcare method=changes 'params:=["NTLc3KhpLsPpUVzgapwEbL7oBNfAYad623sRzJ83JYV", {"changes_type": "account_changes", "account_id": "new-account", "key_prefix": []}]'
```

And the node crashes with:

```
slice index starts at 76 but ends at 45
```

I am reviewing the RocksDB iterator implementation now.

**Comment by frol** [comment]
Ouch, that was a stupid mistake in calculating a common prefix size for non-data-changes, see #2148
