### ISSUE TITLE
Align economic incentives for partial seat pricing

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2056]
Currently if validator gets 1.7 seats, they are rewarded for 1. Meaning there is no point of marginally adding stake until the threshold crossed.
This may lead to undesired behavior, but also in cases of delegation leads to delegates loosing their reward as more delegates join, e.g.:
 Current stake 10000, seat price: 10000 with reward per epoch per 1 near is 0.0001
 New stake added, current stake: 10100, now reward per near is 0.00009900990099 because the number of seats didn't change but the stake it should be divided increased.

To fix this, we should be distributing rewards proportionally to the stake, incentivizing adding more security via larger stakes, even if validators want to maintain lower number of seats.

**Comment by ilblackdragon** [comment]
@bowenwang1996 is this fixed in #2117 ?

**Comment by bowenwang1996** [comment]
Yes
