### ISSUE TITLE
Querying contract state via RPC does not give any result

### ISSUE THREAD

**Issue by frol** [nearprotocol/nearcore#2067]
I have deployed `studio-abd6fq9b5` contract via studio, and executed a method which set `last_sender` key on a storage to `frol.near`. Yet, `query(contract/)` API does not work:

```
$ http post https://rpc.nearprotocol.com/ jsonrpc=2.0 id=dontcare method=query 'params:=["contract/studio-abd6fq9b5","TsnowmMYMe3aWeM"]'

{
    "error": {
        "code": -32000,
        "data": "key must be a string",
        "message": "Server error"
    },
    "id": "dontcare",
    "jsonrpc": "2.0"
}
```

The second parameter is expected to be a base58-encoded key prefix, so I encoded "last_sender" with base58: "TsnowmMYMe3aWeM"

I have also tried to send an empty string (expecting to receive a whole state), that gives the same error. Providing just a substring of the base58 string, I could get the response, but it is always an empty value.

**Comment by ilblackdragon** [comment]
For documentation purposes, the output of query is a list of (key, value) from storage state encoded in base64 encoding:
```
http post http://localhost:3030 jsonrpc=2.0 method=query id=123 params:='["contract/my_token", ""]'
HTTP/1.1 200 OK
content-length: 302
content-type: application/json
date: Mon, 03 Feb 2020 23:11:51 GMT

{
    "id": "123",
    "jsonrpc": "2.0",
    "result": {
        "block_height": 2057,
        "values": [
            [
                "U1RBVEU=",
                "AgAAAGFpAQAAAAAAAAACAAAAYWsBAAAAAAAAAAIAAABhdqCGAQAAAAAAAAAAAAAAAAA="
            ],
            [
                "YWkMAAAAbXlfdmFsaWRhdG9y",
                "AAAAAAAAAAA="
            ],
            [
                "YWsAAAAAAAAAAA==",
                "DAAAAG15X3ZhbGlkYXRvcg=="
            ],
            [
                "YXYAAAAAAAAAAA==",
                "oIYBAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            ]
        ]
    }
}
```

**Comment by nearmax** [comment]
Raising priority and moving to the EthDenver epic since it is important for the EthBridge. Also adding dependency.

**Comment by frol** [comment]
PR is under review https://github.com/nearprotocol/nearcore/pull/2075

**Comment by nearmax** [comment]
Since we decided to use events differently (see https://github.com/nearprotocol/near-bridge/issues/12) this is no longer a blocker for EthDenver. Therefore I am reducing priority from P0 to P1.
