### ISSUE TITLE
Fix and re-enable gas metering

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/nearcore#208]
Currently `.inject_gas_metering()` is messing up something in compiled AssemblyScript code. This results in garbage passed instead of string constants (mechanism unclear).

**Comment by evgenykuzyakov** [comment]
It's possible that it's related to #194 
We should try again once floats are fixed.

**Comment by vgrichina** [comment]
> We should try again once floats are fixed.

I think we should try to reduce to small synthetic example, should be possible to generate code without floats. Would be very surprising if it is related though. Seems more like offsets to strings aren't updated properly after injecting gas calculation.

**Comment by evgenykuzyakov** [comment]
Well gas_meter is implemented by parity. We'll try to update to latest version (they have api changes), and if the latest version doesn't work we'll contact them with the example.

**Comment by evgenykuzyakov** [comment]
![gas_meter](https://user-images.githubusercontent.com/470453/50133588-103be000-0241-11e9-90ac-790145a0b00b.jpg)

**Comment by evgenykuzyakov** [comment]
I've re-enabled gas meter. We still need to disable float operations
