### ISSUE TITLE
Move CI to github action

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2080]
Looks like github action supports caching now https://github.com/actions/cache. We should try again to see if it works for us now.

**Comment by ailisp** [comment]
2gb is possibly too limited for rust. Will still give a try if it gives a reasonable speedup:
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy

**Comment by bowenwang1996** [comment]
Does using our own runner solve this problem? https://help.github.com/en/actions/automating-your-workflow-with-github-actions/hosting-your-own-runners

**Comment by ailisp** [comment]
It's undocumented whether self hosted runner support a customized maximum cache, but i can try

**Comment by ilblackdragon** [comment]
@ailisp Given you switched to buildkite - I'm assuming this can be closed?

**Comment by ailisp** [comment]
Yes
