### ISSUE TITLE
pytests are broken

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2087]
Python tests are broken due to some strange assertion error, for example http://nightly.neartest.com/run/ae4852eb23166a7ae1a2894e24e57bdf31b234e3_200112_062437/pytest/pytest_sanity_transactions_py/stderr. However, I cannot reproduce this locally.

**Comment by ailisp** [comment]
I constantly get this error when run pytest locally sometime in January. If rerun it always worked again. Then this error disappear locally and i cannot see this error after that. @SkidanovAlex Did you fix it sometime in January and if so what was the fix

**Comment by bowenwang1996** [comment]
I fixed it a while back https://github.com/nearprotocol/nearcore/pull/1985

**Comment by ailisp** [comment]
The fail was old (older than #1985) and should also been fixed by #1985. But why pytest didn't run since Jan 12 is a problem, will create another issue
