### ISSUE TITLE
Expensive tests fail because of too many open files. 

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2088]
For example, `test_smart_contract_self_call_testnet` fail with
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Other, message: "Too many open files" }', src/libcore/result.rs:1165:5
```
http://nightly.neartest.com/run/ae4852eb23166a7ae1a2894e24e57bdf31b234e3_200112_062437/expensive/expensive_nearcore_test_cases_testnet_rpc_test__test_smart_contract_self_call_testnet/stderr

**Comment by ilblackdragon** [comment]
So far we have been avoiding this problem by setting ulimit -u. Putting in Post Mainnet. Let me know if I'm wrong.

**Comment by ailisp** [comment]
Yes. also this does not happen for a while
