### ISSUE TITLE
Publish new nearcore 0.4.4 image to DockerHub

### ISSUE THREAD

**Issue by k06a** [nearprotocol/nearcore#2092]

**Comment by bowenwang1996** [comment]
We are at version 0.4.12. Why publishing 0.4.4?

**Comment by k06a** [comment]
@bowenwang1996 it seems our docker hub version is out of sync with nearcore version

**Comment by bowenwang1996** [comment]
We use `latest` by default, but you are right that we should be more consistent with versions.

**Comment by nearmax** [comment]
I published https://hub.docker.com/layers/nearprotocol/nearcore/ethdenver/images/sha256-7da5a84eb8ff0e7c642d0683fe9d91e1a950fc5b72a6495d449f2314b4a00cbc Once @k06a verifies that it works good we will replace the current testnet with it.

**Comment by k06a** [comment]
@nearmax I can confirm it works good enough with the bridge

**Comment by nearmax** [comment]
> @nearmax I can confirm it works good enough with the bridge

Thank you!
