### ISSUE TITLE
[Discussion] Refactoring of how to run a node

### ISSUE THREAD

**Issue by Kouprin** [nearprotocol/nearcore#2115]
Starts here: https://github.com/nearprotocol/nearcore/pull/2099#pullrequestreview-355217127
@nearmax, discuss here, find the best solution, set proper priority and find an assignee. If not, close.

**Comment by nearmax** [comment]
Copying my suggestion here and assigning to @damons to get his input since he is looking at related things ATM.

>  I suggest we extend the idea of @Kouprin and @mfornet for the adversarial node:
> 
> We are going to have several types of nodes in our system:
> 
> regular node (the only node for which we will be distributing the docker image);
> archival node;
> debug/diagnostics node;
> adversarial node.
> To run any of the above nodes, except the regular one, the user needs to provide the following three things:
> 
> The code should be compiled with the feature flag that guards conditional compilation;
> The node should be started with a special command line flag;
> There should be an intent file next to the node.
> For example, if we want to run adversarial node we should compile it with adversarial_you_will_be_slashed feature, then pass --adversarial_you_will_be_slashed flag and create adversarial_you_will_be_slashed.txt file before starting the node.
> 
> Pros:
> 
> Uniform treatment of various types of the node:
> Adversarial node and debug/diagnostics node use conditional compilation anyway;
> Conditional compilation allows having optional external dependencies that might be used by heavy versions of the node, like "archival node" and "debug/diagnostics node";
> Triple opt-in makes it really hard for someone to launch the wrong node accidentally. There is no need to have a clean-up step where we yank adversarial code when merging into master;
> WDYT @Kouprin , @SkidanovAlex , @mfornet ?

**Comment by damons** [comment]
Also see:  https://github.com/nearprotocol/NEPs/pull/31
