### ISSUE TITLE
Negate the Need to Manually Lookup Latest-Stable-Release Tag

### ISSUE THREAD

**Issue by ghost** [nearprotocol/nearcore#2116]
## Problem

Releases are usually available via a git tag (like `v1.2.3`).

In order to get the latest release from the repo, a user needs to lookup the latest release, or use a cli command like e.g. `git describe --abbrev=0 --tags`.

Those manual steps are error-prone and inconvenient.

## Solution A

With each new release, tag additionally 'stable' (latest stable release)

`git checkout stable` retrieves always the latest stable release code.

## Solution B

Provide a `stable' branch.

A possible(!) related workflow:

* https://gist.github.com/digitaljhelms/4287848

<img src="https://camo.githubusercontent.com/f011896cab0a6e086954a10d3a5132d57ca69468/687474703a2f2f662e636c2e6c792f6974656d732f3369315a336e3154316b3339327231413351306d2f676974666c6f772d6d6f64656c2e3030312e706e67">

### Solution ...

(other solutions)

.

**Comment by ilblackdragon** [comment]
We have `stable` branch now.
