### ISSUE TITLE
Automate reset testnet process

### ISSUE THREAD

**Issue by ailisp** [nearprotocol/nearcore#2133]
This script is for validator perspective, they should be able to run this script to:
- Shutdown node if running
- Obtain new binary & genesis state
- Restart node with new code & state
- Remove old data and reset ~/.near
- Restart the node

**Comment by damons** [comment]
I'd really like to see these functions/use cases to be managed by NEAR Shell.  

See:  https://github.com/nearprotocol/NEPs/pull/31

**Comment by bowenwang1996** [comment]
The reset process should also incorporate what we discussed in #2284.
