### ISSUE TITLE
Document nearcore Release Process

### ISSUE THREAD

**Issue by damons** [nearprotocol/nearcore#2135]
We are moving to scheduled releases, i.e., nightly, staging, testnet, and eventually mainnet.  In order to do this, we must first document our current release process for staging.  We will use this documentation to automate our release process as much as possible.  

The output of this task will be to create a markdown file in the nearprotocol/docs repo describing the steps required to produce a release of nearcore.

**Comment by lazaridiscom** [comment]
Write self documenting release scripts

**Comment by ailisp** [comment]
Haven't find a very appropriate location to put this doc. Suggestions? https://docs.nearprotocol.com/docs/contribution/nearcore or https://docs.nearprotocol.com/docs/validator/staking-overview
Full possible places: https://github.com/nearprotocol/docs/tree/master/docs

**Comment by lazaridiscom** [comment]
@ailisp , a possible solution:

add a "dev" folder in the root of the sources, there you can add any information relevant to (core) development. README would start with "this documentation addresses core-developers and external core-contributors, e.g. people which work on the near-protocol source-code itself"

So, dapp/asset/chain-related documentation goes to the docs sites (normal developers, the "customers")

core-dev related documentation goes to ./dev

**Comment by lazaridiscom** [comment]
Just noticed this in the OP:

> The output of this task will be to create a markdown file in the nearprotocol/docs repo

"docs" implies "standard documentation" (e.g. users/normal devs).

better to distinguish clearly (use of ./dev)

**Comment by ilblackdragon** [comment]
Let's either use docs folder in this repo or contributing section in  https://docs.nearprotocol.com/docs/contribution/nearcore
