### ISSUE TITLE
Revise README

### ISSUE THREAD

**Issue by ghost** [nearprotocol/nearcore#2141]
## Expected

The usual, like:

* Build Status
* Description (very compact, consistent with repo-description)
* Install from Binaries (can point to online-manuals)
* Build from Source (basic build, e.g. for ubuntu, then point to manual for more info)
  * Running Tests
  * Install
  * Mention Mac and Win
* Contribution (tiny text, then point to manual / file)
* Developer Resources
* Acknowledgements (optionally)
* LICENSE

Most importantly, the "Build from Source" is missing.

(folks, it takes forever to land here: https://docs.nearprotocol.com/docs/contribution/nearcore. Really not the way to go)

## Related

review #2042

**Comment by potatodepaulo** [comment]
Thanks for this. Will update with these sections.

**Comment by lazaridiscom** [comment]
> These are mostly subjective changes that don't add a ton of concrete value for someone trying to contribute or find information. This README does need an update, so thanks for raising this issue.

https://github.com/nearprotocol/nearcore/pull/2181#issuecomment-595519692

the changes were not subjective, but absolute and obvious.

Current Readme is a total mess, as is your contribution-process.

Fix both, yesterday.

**Comment by ilblackdragon** [comment]
Done in #2282
