### ISSUE TITLE
Testnet reset testing

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2143]
There needs to be some tests to make sure that the state and config migration is successful. For state migration, we can do a reverse migration and check if the original state dump can be recovered (caveat: need to be extra careful when the migration is not a bijection). In addition, we also want to check:
* stake in `validators` match locked balance on their account.
* genesis time is properly updated.
* Total supply is correctly updated.

**Comment by ailisp** [comment]
> genesis time is properly updated.
> Total supply is correctly updated.

How should they be updated?

**Comment by bowenwang1996** [comment]
For genesis time, we will announce it when we plan the reset/upgrade so that should not be a problem. For total supply, we mainly want to check that if we change something about the account it is updated correctly. For example, if we change the denomination from yotcoNEAR (I don't think it will happen but just in case) to something else, we need to make sure that the total supply is correctly updated.

**Comment by ilblackdragon** [comment]
Linking #2435 here as this issue mentions checking that locked balances match validators stake.

**Comment by ilblackdragon** [comment]
This is done, from my understanding. Closing.
