### ISSUE TITLE
Catchup tests fail

### ISSUE THREAD

**Issue by Kouprin** [nearprotocol/nearcore#2145]
- [x] test_catchup_random_single_part_* fixed in https://github.com/nearprotocol/nearcore/pull/2146
- [x] test_catchup_receipts_sync_distant_epoch fail (related to GC)

**Comment by Kouprin** [comment]
http://nightly.neartest.com/run/8fa00ac6ed6d093d69133aa7a6e2e7e992d2c711_200208_114405

**Comment by bowenwang1996** [comment]
It would be more helpful if you link to the commit.

**Comment by Kouprin** [comment]
> It would be more helpful if you provide a link to the commit.

`git checkout 8fa00ac6`

I'm not sure what are you asking about. What link do you need?

**Comment by Kouprin** [comment]
commit 8fa00ac6ed6d093d69133aa7a6e2e7e992d2c711 in staging.
