### ISSUE TITLE
[WEBSITE] "Validator" vs. "Producer"

### ISSUE THREAD

**Issue by ghost** [nearprotocol/nearcore#2149]
The "Glossary of Terms":

https://nearprotocol.com/papers/nightshade/#glossary

contains

> Validator
> 
> Refers to participants that verify transactions and produce blocks.

Reality seems to be closer to this:

- A Producer produces blocks
- A Validator validates blocks produced by a Producer
- A participant can be
  - only a Producer 
  - only a Validator
  - both, Producer and Validator

Possibly the glossary should be corrected to reflect this.

**Comment by ilblackdragon** [comment]
Currently all validators are block producers.
In the future with "hidden validators" we will have validators who are not block producers. We should revive this glossary question at that point.
