### ISSUE TITLE
[BRANDING] "NEAR Protocol" and its Description

### ISSUE THREAD

**Issue by ghost** [nearprotocol/nearcore#2154]
(this belongs more in a top-level repo, like "org", but did not find one. Note that it does not belong into documentation repos)

Inconsistency:

* github org: **The highly scalable, developer-friendly blockchain.**
* This repo README: **NEAR Protocol - scalable and usable blockchain**

Problems:

* NEAR is more than a blockchain, its a DApp-Platform [1]
* NEAR is `highly scalable` and "usable"

possibly

=> NEAR Protocol, The High Scalability, High Usability DApp-Platform

further problems:

* "near" is a dictionary word
* "protocol" sounds a bit confusing.

-

[1] still trying to find a more general term for this

**Comment by ilblackdragon** [comment]
Updated branding on the org and repo level.
