### ISSUE TITLE
Considering how to integrate nightly test into release process: nightly.neartest.com

### ISSUE THREAD

**Issue by ailisp** [nearprotocol/nearcore#2156]
In short:
@SkidanovAlex @bowenwang1996 
- determine which tests must passed before release
- what if ^ tests doesn't pass, do we still release?

@ailisp 
- have script check these tests passed
- update ui
- need database to track tests. loop to find all runs of existing tests seems already slow

**Comment by bowenwang1996** [comment]
Also update the UI to make it easier to understand.

**Comment by ilblackdragon** [comment]
@ailisp This is done now?

**Comment by ailisp** [comment]
It's close. I added necessary api to nightly to get latest okay commit (given a list of allowed failures). But we're not agree on list of allowed failures yet

**Comment by bowenwang1996** [comment]
@ailisp what's the progress on this?

**Comment by ailisp** [comment]
We have an api to get latest commit in nightly that has only allow fails
(as a POST parameter), but we still don't have an agreed set of "allow
failure" set. so nightly is still not integrated in the betanet release

**Comment by ilblackdragon** [comment]
Hm, should we not have list of allowed failures? E.g. disable tests that are failing right now and enable them back when they are not failing? @SkidanovAlex 
Or alternatively, let's add another flag in nightly.txt that indicates if the test doesn't need to pass.

Also @bowenwang1996 closed my #1799 but it's not really captured here:
 - Show # of failures on http://nightly.neartest.com/ page.

**Comment by ailisp** [comment]
It's done: 
- a seperate service, run at nightly instance ip:8889 to show fails of last finished run and http status 400, or 200 if it's all passed. This service is checked as "nightly" on statuspal (currently is failing)
- on deploy.py, failed tests is checked by getting list of failed tests, once it's fail, exit(1) from betanet release and we should stop, fix nightly fails and release (however exit(1) is commented since we have quite a few failures but we still want to release)
