### ISSUE TITLE
[WEBSITE] Provide High Contrast

### ISSUE THREAD

**Issue by lazaridiscom** [nearprotocol/nearcore#2158]
I'm excited by what the website describes:

https://nearprotocol.com/

but a bit annoyed by the low-contrast.

Readability first, design 2nd.

=> make the text black

## Assessing

use any "font contrast" or "High contrast" extension for the browser to see the difference quickly. Though "high contrast" for documentation like material is a no-brainer

**Comment by amgando** [comment]
@lazaridiscom moving this to the website repo since `nearcore` is unrelated

**Comment by amgando** [comment]
Issue moved to [nearprotocol/wp_website #2](https://github.com/nearprotocol/wp_website/issues/2) via [**ZenHub**](https://www.zenhub.com/)

**Comment by amgando** [comment]
Issue moved to [nearprotocol/wp_website #3](https://github.com/nearprotocol/wp_website/issues/3) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lazaridiscom** [comment]
> 
> 
> @lazaridiscom moving this to the website repo since `nearcore` is unrelated

Given the lack of a dedicated public repo, this would be the related repo.

https://github.com/nearprotocol/wp_website is a deadlink (assuming nonpublic).

(sidenote: GitHub has a new issue transfer functionality, button right)
