### ISSUE TITLE
Create a `devnet` network for daily development work

### ISSUE THREAD

**Issue by damons** [nearprotocol/nearcore#2170]
Per #2165 we should consider creating a `devnet` network with lower stability constraints than `testnet`.

The idea is that whenever a fresh checkout of the default branch of `nearprotocol/nearcore` will be `master` (which is what it is today) which is the tip of development with the latest and greatest code fresh from hackers.  Today, `master` is acting as our release branch and scripts are used to start a NEAR node which points to `testnet` by default.  

This `devnet` should include the same number of nodes as our current `testnet` and any startup scripts in `nearcore/scripts` which are used for development must be modified or created to point to this new network by default.

**Comment by ilblackdragon** [comment]
@ailisp is this done now?

**Comment by ailisp** [comment]
Yes
