### ISSUE TITLE
Create a `betanet` to be used as the chain network for the beta release branch

### ISSUE THREAD

**Issue by damons** [nearprotocol/nearcore#2171]
As part of our efforts to move to schedule releases, I propose we create a new chain network called `betanet` which will be used for all beta releases.  Beta releases will eventually be promoted, after all testing has occurred, to the `stable` branch.  

We should strive to keep `betanet` has stable as possible; however, due to the fact that we are still actively developing our chain protocol, we expect this network to be cycled occasionally.  

This is part of the effort described in #2165.

**Comment by bowenwang1996** [comment]
I believe this is done. Please reopen if that is not the case.
