### ISSUE TITLE
Stabilize staging and master branches and cut a release to the beta branch

### ISSUE THREAD

**Issue by damons** [nearprotocol/nearcore#2172]
To move to scheduled releases, stabilize the `staging` branch, test it until we are satisfied it can be used with `testnet` by the community, and create a `beta` branch that points to a new network.  

This effort depends on the creation of the `devnet` and `betanet` chain networks.  See: #2171

**Comment by damons** [comment]
Needed to realize #2165.

**Comment by lazaridiscom** [comment]
> Needed to realize #2165.

May I suggest that you add this right at the beginning of the issue text https://github.com/nearprotocol/nearcore/issues/2172#issue-569167383, as a "blocks" relation?

`(blocks #2165)`

Better issue-trackers have this build in, well, here on github it needs improvisation.

**Comment by damons** [comment]
> May I suggest that you add this right at the beginning of the issue text [#2172 (comment)](https://github.com/nearprotocol/nearcore/issues/2172#issue-569167383), as a "blocks" relation?
> 
> `(blocks #2165)`

Good idea.  Will do.

**Comment by ilblackdragon** [comment]
Closed, as we have released master to beta now.
