### ISSUE TITLE
Add a new RPC to specify finality in block call

### ISSUE THREAD

**Issue by frol** [nearprotocol/nearcore#2175]
For the reference, the implementation for `query` API: https://github.com/nearprotocol/nearcore/pull/2127

Currently, we can only query `block` by hash and by height, but it is also useful to be able to query the latest, the finalized, and the near-finalized (DoomSlug) block without extra calls.

Current API:

```
http post http://localhost:3030 jsonrpc=2.0 id=dontcare method=block 'params:=[48605]'

http post http://localhost:3030 jsonrpc=2.0 id=dontcare method=block 'params:=["2UP3MujcMuqyrFAtiLwJsjQrxkZuqZWMwCF664dM7MaW"]'
```

Here is the design of the new extended API:

```
http post http://localhost:3030 jsonrpc=2.0 id=dontcare method=block 'params:={"block_id": 48605}'

http post http://localhost:3030 jsonrpc=2.0 id=dontcare method=block 'params:={"block_id": "2UP3MujcMuqyrFAtiLwJsjQrxkZuqZWMwCF664dM7MaW"}'

http post http://localhost:3030 jsonrpc=2.0 id=dontcare method=block 'params:={"finality": "latest"}'

http post http://localhost:3030 jsonrpc=2.0 id=dontcare method=block 'params:={"finality": "near-final"}'

http post http://localhost:3030 jsonrpc=2.0 id=dontcare method=block 'params:={"finality": "final"}'
```

**Comment by bowenwang1996** [comment]
I am not sure whether this needs to be part of the rpc. If we implement this in rpc we have to change nearcore code. Alternatively we can provide this on the explorer side.

**Comment by frol** [comment]
@bowenwang1996 Why is it so? It seems that we should be able to follow the `query` API implementation. Am I missing something?

**Comment by bowenwang1996** [comment]
Ah you are right. I misunderstood the feature.

**Comment by bowenwang1996** [comment]
#2186
