### ISSUE TITLE
[PROJECT] Change Label "housekeeping" to "quality"

### ISSUE THREAD

**Issue by ghost** [nearprotocol/nearcore#2182]
`housekeeping` sounds a little bit casual, it's about "dust", not that much about "how things are organized and work".

But several issues are in essence about `quality`, and a label should indicate this a bit stronger.

I mean, you can easily ignore `housekeeping`, but the label `quality` makes you think twice if you ignore it.

(please feel free to close immediately, this was just a thought when browsing around)

**Comment by nearmax** [comment]
quality has connotations that are too generic. Also housekeeping is a common label on github.
