### ISSUE TITLE
Expose a block_hash into a Wasm runtime

### ISSUE THREAD

**Issue by fckt** [nearprotocol/nearcore#2187]
~@nearmax @SkidanovAlex @ilblackdragon 
How do you think, is there any reason to have a `chunk_hash` exposed to smart contracts as well? I guess it's better to not expose it.~

**Comment by bowenwang1996** [comment]
Smart contracts should not be aware of sharding at all, so I don't see why `chunk_hash` needs to be exposed.

**Comment by fckt** [comment]
Another question: we have a prev_block_hash available. In EVM up to 256 last block hashed are available. Do we need it as well?

**Comment by nearmax** [comment]
> Another question: we have a prev_block_hash available. In EVM up to 256 last block_hashes are available to smart contracts. Do we need it as well?

What is it used for? In general, I would suggest we add host functions as they are requested. @evgenykuzyakov is going to write a bunch of contact examples soon based on Ethereum use-cases and if anything like this pops up we can discuss and add it. Closing it. Will reopen once we have a use case.

**Comment by nearmax** [comment]
Thank you for reporting though!
