### ISSUE TITLE
Update Build Docs for Running a Node

### ISSUE THREAD

**Issue by damons** [nearprotocol/nearcore#2192]
Need to update the NEAR Documentation for Running a Node to direct hackers to use the `stable` branch instead of staging when using `testnet`

Here:  https://docs.nearprotocol.com/docs/local-setup/running-testnet

**Comment by jimmy3dita** [comment]
@damons do we want to rewrite the guide and use Nearup instead?

**Comment by jimmy3dita** [comment]
This may be related: https://github.com/near/docs/pull/426
