### ISSUE TITLE
"Finalize cannot be called with uncommitted changes" error on RPC query

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2226]
Moving our discussion from the telegram group.

@vgrichina encountered the following error message when debugging an EVM contract:
```
thread 'main' panicked at 'Finalize cannot be called with uncommitted changes.', core/store/src/trie/update.rs:151:9
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
thread 'main' panicked at 'called Result::unwrap() on an Err value: Custom { kind: Other, error: "Non-zero exit code: 1" }', near/src/main.rs:205:13
```
The backtrace: https://gist.github.com/vgrichina/db0106ac6f6ae0e35d00e7254d609c5f

The MVP is non-trivial.

Overall, we don't need to call finalize in here https://github.com/nearprotocol/nearcore/blob/f605a11f2c3e4a47e118c9707db100ff6b7c9877/runtime/runtime/src/state_viewer.rs#L164 as pointed out by @bowenwang1996 and we can check whether there are any changes by examining trie update. However, this is not the cause of the problem. Overall, we should always commit changes before calling finalize, we need to find the place where commit should've been called and add it there.

**Comment by vgrichina** [comment]
@nearmax this might be helpful to reproduce https://github.com/nearprotocol/near-web3-provider/issues/12

note that I really cranked up my gas limits as well. Here's my `.near` folder https://drive.google.com/file/d/1gI-n1Bk-OXrIPM8geLk0J3J47LQaCAca/view?usp=sharing (I've been using `vg-evm` contract)

**Comment by vgrichina** [comment]
```
[I] ➜ cat neardev/default/vg-evm.json 
{"account_id":"vg-evm","private_key":"ed25519:5DwpcPJgtqLKSAm6wPtaQ1XyTBdSQxkd4bQY5kCBqZscZ38e1S2HbTwpTsWzgjhf6S2VinbMXWyangAh8GZvYPY6"}%                        
```

here's the key for `vg-evm` there

**Comment by evgenykuzyakov** [comment]
@nearmax @vgrichina @bowenwang1996 @k06a @ilblackdragon 

My question is should we prevent any state writes during view calls?
The current behavior is to execute the view call completely, but fail if the state is modified at the end. This will return all the logs during execution.

### Suggested solution is
change `storage_write` and `storage_remove` to fail when `VMContext` contains `is_view == true`. This will fail view call execution earlier.

What I don't like about this approach is it sometimes useful to reuse functions that temporary modifies storage. Even if you don't care about those results being stored at the end. Essentially what we are doing with the current approach is guarding developers from a mistake, while preventing them from the certain functionality.

**Comment by nearmax** [comment]
@evgenykuzyakov I agree that having temporary storage modifications might be somehow useful, but I would prohibit storage access altogether because accessing storage is expensive, and queries currently have not protection mechanism against spam, by preventing access to the storage we are solving at least part of the problem. The idea of preventing it on `VMContext` level sounds good.
