### ISSUE TITLE
Testnet reset should keep height

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2231]
As noted by @SkidanovAlex, if we do not keep block height after the reset, which is what we currently do, then if not all nodes reset at the same time validators who have and who haven't reset will start slashing each other because of doomslug and finality gadget violation.

**Comment by bowenwang1996** [comment]
Update: actually slashing won't happen because the two networks have different genesis hash and therefore won't connect to each other.

**Comment by SkidanovAlex** [comment]
The genesis hash is not part of the approval message or a block message today.
To challenge someone who doublesigned it is sufficient to provide two blocks or two conflicting approvals.
It is largely orthogonal to whether nodes can connect.

**Comment by bowenwang1996** [comment]
I see. So this is an attack rather than what naturally happens.

**Comment by bowenwang1996** [comment]
Actually how does the challenge get validated when this happens? Shouldn't it be the case that neither chain is able to validate the challenge because block header doesn't exist so that the challenge is invalid?

**Comment by SkidanovAlex** [comment]
The double sign challenge contains the headers. The headers are not fetched from the store when the challenge is validated.

**Comment by bowenwang1996** [comment]
`verify_validator_signature` will fail because prev_hash cannot be found.

**Comment by SkidanovAlex** [comment]
> verify_validator_signature will fail because prev_hash cannot be found.

^^ this means that the validity of the challenge depends on the presence or absence of some other blocks in the storage, in other words the validity of the challenge is not deterministic, right?

And I presume the validity of the block depends on the validity of the challenge, so two nodes that have different set of other blocks in their storage will treat the same block with a challenge differently.

So it's a bug. Block DoubleSign should not be fetching the previous block, and should contain the block producer as part of the challenge (I assume it's what it tries to fetch via the prev block). Tracking in #2233

**Comment by bowenwang1996** [comment]
It needs to access block info in storage to check whether the challenged block producer is already slashed. I think it would be hard to make the challenge self-contained as there is no way of proving that someone has not been slashed.

**Comment by ilblackdragon** [comment]
@bowenwang1996 @SkidanovAlex  `verify_validator_signature` requires to know the epoch and latest known block hash (which is always known and can be different for different nodes for obvious reasons).
Latest known hash indeed will only affect if this validator is already slashed at this point or not.
Question in hand - epoch id from another network won't be found and slashing won't go through.
We should have test for this though as part of our malicious challenges.
