### ISSUE TITLE
We should limit max length for `bs58::decode` input 

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#2256]
For example sending the following:
```python
base58.b58encode(b'123' * 10000)
```

instead of a public key might create an unwanted CPU cycles.

**Comment by evgenykuzyakov** [comment]
The way to address it would be limit the total length of `bs58.decode` before we call it and fail early

**Comment by frol** [comment]
We used to have a size limit on the RPC input arguments. I will double-check that. Thanks!

**Comment by frol** [comment]
We should also check the block, chunk, transaction hash deserialization as well, and identify other potential places where we want to limit the input to avoid DOS.
