### ISSUE TITLE
Cleanup RuntimeExt iterator methods

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#2276]
The iterators were removed from `VMLogic`, but they also needs to be removed from `RuntimeExt`.

**Comment by evgenykuzyakov** [comment]
Related to #2234

**Comment by evgenykuzyakov** [comment]
I'll take it, since I need to remove them as part of my refactoring change.

**Comment by nearmax** [comment]
Thank you!
