### ISSUE TITLE
Whitelist contract. Implementation

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2287]
Given #1992, most of the initial tokens will be locked. We though still need to allow initial set of participants to delegate their tokens using https://github.com/nearprotocol/NEPs/pull/27.

The design for whitelist, can be following:
 - Lockup contract allows to have `delegate(contract_id, amount)` function, that will call `lockup_whitelist.delegate(contract_id)` with the attached amount.
 - Whitelist contract has a registry of contracts that are allowed to be delegated to.
 - On `delegate` call it checks that `contract_id` is in the list, and proxies the delegation to that contract.
 - Otherwise returns funds.

At the start, we allow Foundation to add and remove contracts from the list. This is done by allowing contract `foundation.near` to call functions `add` and `remove`.

**Comment by evgenykuzyakov** [comment]
If for some reason we've failed to delegate from the `lockup_whitelist` to `contract_id` the funds will be stuck in the `lockup_whitelist` contract. Delegation needs a discussion on itself. We can't just assume things without thinking through security

**Comment by ilblackdragon** [comment]
Not clear why would it get stuck?

`lockup_whitelist` contract should receive callback after `delegate` call to the `contract_id` in case of success or failure. In case of failure - just return money back to the originator.

If we don't have context within the failure callback (which is sh*t btw), we should record in the `lockup_whitelist` contract outgoing (`amount`, `predecessor_id`, `contract_id`) and use that when callback arrives.

**Comment by evgenykuzyakov** [comment]
> In case of failure - just return money back to the originator.

It can be tricked within Runtime. It's a design issue that we can't rely on the result of the call to return money. I think we have it explained somewhere but I'm going to explain again here:
- `lockup` calls `lockup_whitelist` with 10N.
- `lockup_whitelist` calls `stake_pool1::stake` and attaches 10N.
- `stake_pool1::stake` calls `oh_no_pls_fail` and returns a promise as a result. But `stake_pool1` keeps 10N.
- `oh_no_pls_fail` doesn't exists, so the result fails.
- `lockup_whitelist` receives failure as a result and returns 10N to the `lockup`, which is taken from `lockup_whitelist` account.

**Comment by evgenykuzyakov** [comment]
The overall solution can direct delegation with whitelist check:
- `lockup` calls `lockup_whitelist::can_delegate_to(contract_id)`
- `lockup_whitelist` says yes.
- `lockup` checks it and calls `contract_id::delegate()` with attached balance.

Should be pretty easy to implement for both staking pool contract and lockup. Since the API can be the same

**Comment by ilblackdragon** [comment]
There are 2 considerations here:

a) All contracts in whitelists will need to be carefully reviewed for any kind of issues, not just calling invalid issues. So your flow seems irrelevant to security of the whitelist as it suggests invalid staking contract in the first place. Your other solution doesn't address this problem either.

b) Indeed seems like a design issue which we should both document VERY VERY VERY BIG LETTERS and post MainNet really invest in addressing (in my understanding with Safes?).

**Comment by evgenykuzyakov** [comment]
Still in your design `lockup_whitelist` seems to act as a proxy instead of just doing whitelisting.

> Indeed seems like a design issue which we should both document VERY VERY VERY BIG LETTERS and post MainNet really invest in addressing (in my understanding with Safes?).

Safes don't address this easily. It needs some type of settlement to decide the fate of the deposit.

**Comment by ilblackdragon** [comment]
Yes, what is wrong with `lockup_whitelist` being a proxy contract?

**Comment by nearmax** [comment]
Discussed whitelist contract during the middleware sync https://github.com/near/community/blob/master/meetings/middleware-wg.md#initial-contract Implementation was estimated by @evgenykuzyakov to be about 1 day for 1 person. Adjusting the estimate.
