### ISSUE TITLE
Scheduled releases

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2288]
Setup scheduled releases:
 - DevNet every night (nightly build) from `master` branch. 
 - BetaNet every week from `beta` branch. Only upgrades from commit that passes all nightly tests.
 - Stable Testnet from `stable` branch.

Releases happen on time. Networks automatically upgrade on our side.
For external validators we push update and they follow on timely manner because they know the timing for release schedule.

**Comment by bowenwang1996** [comment]
I propose that we have a five-week release cycle for testnet.
