### ISSUE TITLE
Disable challenges

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2290]
For MainNet v1 we decided not to enable challenges. That said, right now challenges are in the code and should be disabled.

**Comment by bowenwang1996** [comment]
We should also disable fishermen as part of this change. Not clear whether we should remove that code entirely or just make sure there can be no fishermen (making threshold u64::MAX) for example.

**Comment by ilblackdragon** [comment]
Why not keep fisherman selection?

**Comment by bowenwang1996** [comment]
There were some issues with fishermen so I was thinking about removing them and reconsidering the design. But I think most are fixed now so it's fine if we just disable it.
