### ISSUE TITLE
Implement MainNet config for stable TestNet

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2291]
Stable TestNet should be running with MainNet config. E.g.:
 - [ ] 1/2 day epoch length
 - [ ] Correct economics params
 - [ ] Final gas and fees
 - [ ] Transaction validity length
 - TODO: ???

Should carefully audit every parameter in the config and set values to the right values.
BetaNet can still run with faster epochs / some test params on gas and fees.

**Comment by nearmax** [comment]
It seems like this issue is about taking the existing config and reviewing every single field in on to make sure it is correct. Setting estimate to 3 days.

**Comment by nearmax** [comment]
Removing @bowenwang1996 since we keep one assignee per issue, see the guidelines.
