### ISSUE TITLE
Telemetry for devnet and betanet is off

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2306]
Currently if you run `nearup betanet` or `nearup devnet` you get:
`Telemetry: https://explorer.nearprotocol.com/api/nodes`.

Also note that if you look at the explorer, neither of the networks have any reported nodes.

**Comment by ailisp** [comment]
I suspect it's a explorer bug, since in config.json telemetry already turned on:
```
  "telemetry": {
    "endpoints": [
      "https://explorer.nearprotocol.com/api/nodes"
    ]
  },
```

**Comment by jimmy3dita** [comment]
On the frontend, the URL changes:
devnet: https://explorer.devnet.nearprotocol.com/
betanet: https://explorer.betanet.nearprotocol.com/
testnet: https://explorer.nearprotocol.com/

**Comment by frol** [comment]
@ailisp telemetry should go to the relevant domain for each of the network. It is sort of a duplicate of #1788

**Comment by frol** [comment]
The bug is in nearcore, it seems it cannot connect to HTTPS.

**Comment by ilblackdragon** [comment]
@frol should we just change on the explorer side depending on the `chain_id` at this point?

**Comment by frol** [comment]
I have fixed the issue in nearcore, but we still need to fix nearup: https://github.com/near/nearup/issues/16
