### ISSUE TITLE
Review chain syncing

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#2307]
The corresponding spec work item is here: https://github.com/nearprotocol/NEPs/issues/48

# What to consider before reviewing

Understand the high level of syncing, and think how it'd be built naively. What problems will naive implementation have? Do we have those problems?

For State Sync specifically try to understand all the data that needs to be communicated, and what sort of proofs are necessary. Write down the proofs we need to check before reviewing how it is done today, and make sure all the proofs you outlined actually exist when you review.

# What to review

`HeaderSync`, `BlockSync` and `StateSync` classes and their integration with the client.

TODO @Alex Kouprin where else is the logic for State Sync?

1. Concept of Catching Up - not described at all in this document. (@Alexander Skidanov TODO related to State Sync)
2. Circumstances of when different Syncs should be executed and why (especially State Sync). Horizon constants.
3. Handlers in ViewClientActor and ClientActor with `msg` = StateRequestHeader, StateRequestPart and StateResponse.
4. Methods in `[chain.rs](http://chain.rs)` - getters and setters of State Headers, Parts and Finalizing.
5. Methods in Runtime Adapter - `obtain_state_part()`, `validate_state_part()`, `confirm_state()`, `get_state_root_node()`, `validate_state_root_node()`.
6. Trie `retrieve_root_node()` and `RawTrieNodeWithSize` class.

# What to test

Think of non-trivial syncing cases. Forks, adversarial behavior, etc.

Fuzzy tests for syncing are also missing today.

**Comment by mfornet** [comment]
# Update

1. Covered high level understanding of the Syncing process. Thought about how I would approach it and core issues I foresee.
2. Very useful 101 with @Kouprin where he cover all of my high level questions (not code at this point).
3. Start reading and understanding code. `sync` function at `ClientActor` and `HeaderSync`.
4. Writing comments on the code on functions that benefits more from having more comments, so future reviewers can understand easier (WIP: not a PR yet)
5. Haven't look into existing tests, but thought about some tests that might be useful to have, so will check about those that are implemented and add other myself.

**Comment by mfornet** [comment]
# Update

1. Writing progress on [notion page](https://www.notion.so/nearprotocol/Sync-Review-22a043d5dadc4b1ba921c65883f07a90).
2. #2394

**Comment by mfornet** [comment]
# Update

- Review PR related to sync.

(This week did very little work on stability push due to other issues around network, releasing, testing)

**Comment by mfornet** [comment]
# Update

- Review block / header / state sync.
- Partially went through relevant methods in chain.
- Designing tests for coverage and edge cases.
