### ISSUE TITLE
Remove blockchain from StateViewer

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#232]
StateViewer should not rely on access to blockchain.

**Comment by azban** [comment]
something is going to have to own a `StateDbViewer` and a `BlockChain` though.. and since we don't have anyone consuming this other than the rpc task it doesn't  make sense to separate this out imo

**Comment by azban** [comment]
if were trying to plan for sharding, I think it makes more sense to have statedbviewer take a hashmap of chains than to have RPC impl choose the chain which is where the current PR is heading

**Comment by azban** [comment]
I also think we're getting close to dipping into sharding specific changes. this is not going to hurt compatibility in the future and thus may be premature and we may have a better idea on how to solve this when we actually need to.

**Comment by ilblackdragon** [comment]
I understand your concern about RPC having chains - but it does have chains though indirectly.

But logically, StateView doesn't have anything to do with any chain. And if we really need a root (and we have functions that take it) - we should make runtime self-sufficient.

For example, DevNet shouldn't spin up chains at all. Just bring up runtime / viewer

**Comment by ilblackdragon** [comment]
In general `runtime` module is our Back-end as a Service - and we should be able to use it like that.

**Comment by azban** [comment]
ok. so these are really just functions on `StateDb` then? we don't need a notion of `Runtime` or `StateDbViewer`.

i still don't think it makes sense to pass chains into `RpcImpl` and have them deal with it. we shouldn't have to have different `RpcImpl`s for different ways of using statedb. i think it probably makes sense to have a `StateDbHandler` trait that exposes all of the function without the notion of a root. and then have one that just keeps track of the root without chains that we can use in devnet, one that has a shard chain container, and another for whatever else we need.

**Comment by ilblackdragon** [comment]
Done.
