### ISSUE TITLE
Different protocol versions for different networks

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2326]
Since both `betanet` and `testnet` keep state now, there is an issue with keeping protocol version the same: every migration that changes state will increment protocol version and since testnet and betanet are necessarily on different release schedule, it is impossible to have them on the same protocol version. Ultimately protocol version is specific to the network and two nodes on different networks, even with the same protocol version, should not be allowed to talk to each other. Therefore I think it makes sense to have different protocol versions on different networks.

**Comment by frol** [comment]
Two nodes on different genesis are not going to talk to each other, I don't think we need to make it any more explicit.

**Comment by ailisp** [comment]
There seems a a problem in neard: what protocol_version should neard init generate

**Comment by ilblackdragon** [comment]
Protocol version defines *code* not network:
 - `neard init` without arguments will generate a new network with (a) new account key (b) new network id
 - meaning genesis will be different
 - protocol version can be different or the same between `betanet` and `testnet` - it depends which code they run. Migrations for testnet and betanet should happen independently but the migration itself runs the same code and prepares the state to the same state.
 - migrations should be no used to modify state of the network IMO as we have discussed.

**Comment by bowenwang1996** [comment]
Oh I think I messed up. The plan is to not upgrade protocol version until we merge code into stable  (if necessary). The migration on betanet (if not for protocol breaking changes) does not need to modify protocol version @ailisp.

**Comment by bowenwang1996** [comment]
Followup comment: we should use the same config for betanet and testnet so that there is no confusion as to how to migrate things. Otherwise if we decide to change some config parameter we might need separate migration scripts for betanet and testnet, which can be hard to maintain.

**Comment by mfornet** [comment]
Aren't we using `chain_id` exactly to address this problem?
