### ISSUE TITLE
Fix TransactionOutcome Borsh deserialization by light client

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2340]
An issue for an already existing PR so that we can track its progress in the board

**Comment by nearmax** [comment]
Setting estimate to 5, since we might be breaking some stuff in nearlib with it. CC @frol , @vgrichina

**Comment by frol** [comment]
Do we parse Borsh with near-api-js at all? How do we even get it into JS in Borsh format in the first place (there are no RPCs AFAIK)?

**Comment by nearmax** [comment]
> Do we parse Borsh with near-api-js at all? 

near-api-js parses and unparses Borsh see the usage of https://github.com/near/near-api-js/blob/master/src.ts/utils/serialize.ts

Transactions are in Borsh format because we need to hash the borsh-serialized transaction for signing. I don't know whether anything else is operated using Borsh.
