### ISSUE TITLE
Remove Nightshade Finality Gadget

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#2342]
Context: there's a fundamental issue between Doomslug and NFG that we discovered recently. Specifically, it could be that a block at height `h` is produced, and some participants have already sent endorsements for it, and then a block at height less than `h` is produced but with a higher NFG score, and becomes the head. The chain stalls because no block producer can send a skip message that will bypass `h`.

The solution to it is to make Doomslug aware of the score, and change the conditions for endorsements and skips to accommodate it. However, since both safety and liveness proof of Doomslug rely on head height never getting lower, enduring safety and liveness remain after introducing this change is not trivial.

I instead suggest to completely remove NFG, and change Doomslug so that it
a) becomes a BFT consensus
b) loses its ability to provide some weaker sense of finality at 50%.

The full argument is here: https://docs.google.com/document/d/10uBwpEN3ADDkL9iY52K0zM1edgxmoO8hJBqxmDafFN0/

**Comment by SkidanovAlex** [comment]
Moved to https://github.com/nearprotocol/NEPs/issues/54

**Comment by bowenwang1996** [comment]
Reopen to track progress.

**Comment by bowenwang1996** [comment]
Fixed in #2531
