### ISSUE TITLE
Lookup account by public key

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/nearcore#2349]
Third-party wallets need ability to find accounts with given public key (as they manage keys in a way unrelated to NEAR accounts). Same applies for first-party wallet for some cases of account recovery (e.g. recovering based on seed phrase or based on Ledger wallet).

We need to figure out a way to do it – whether it is in nearcore, explorer or separate service just for this feature (and other potential multi-shard queries). It doesn't necessarily have to be trustless, as results can be easily verified independently.

**Comment by frol** [comment]
The issue is currently tracked at https://github.com/nearprotocol/near-explorer/issues/236.

I want to clarify if this is mainnet blocker for Wallet or anything else.

**Comment by bowenwang1996** [comment]
I think this shouldn't be tracked in nearcore given there is already an issue and we are not going not implement it in nearcore.

**Comment by frol** [comment]
@vgrichina @ilblackdragon I need your judgment about the mainnet priority for such a service. If it is a blocker, I go and implement it ASAP on the Explorer side for now.
