### ISSUE TITLE
feature(jsonrpc): Expose transaction hash in the error response if the `broadcast_tx_commit` times out

### ISSUE THREAD

**Issue by frol** [nearprotocol/nearcore#2359]
Currently, when one submits a transaction with `broadcast_tx_commit` API, we block and wait till the transaction lands to a block, but we have a timeout of 10 seconds to avoid indefinite waiting time. Sometimes (for example, under a load) network does not succeed in landing the transaction and timeout error is returned, but the client may still choose to check on the transaction, but they need a transaction hash. This needs to be returned along with the timeout error.

**Comment by ilblackdragon** [comment]
The sender has transaction hash... Among other things, they just signed it.

**Comment by bowenwang1996** [comment]
@ilblackdragon yes but for example near-api-js doesn't actually return the transaction hash when you submit the transaction. cc @vgrichina

**Comment by ilblackdragon** [comment]
That is an issue of nearlib API @bowenwang1996

**Comment by frol** [comment]
Well, I agree, it seems to make sense to resolve on the near-api-js side. I vote for "moving" this issue to near-api-js issues tracker.

**Comment by bowenwang1996** [comment]
It seems that we cannot transfer the issue to a repo outside of this organization.

**Comment by frol** [comment]
Closing in favor of https://github.com/near/near-api-js/issues/127 /cc @vgrichina
