### ISSUE TITLE
Node stuck in state sync with high CPU usage

### ISSUE THREAD

**Issue by mikedotexe** [nearprotocol/nearcore#2374]
Using [nearup](https://github.com/near/nearup), I had betanet running earlier today, in verbose mode.
The CPU was fairly low.

<img width="1272" alt="Screenshot 2020-04-01 15 23 49" src="https://user-images.githubusercontent.com/1042667/78198370-42288400-743d-11ea-87fe-2d02796b586f.png">

Then I heard there was an update and to restart the node. I did this with:

`nearup stop && rm -rf ~/.near && nearup betanet --verbose && docker logs --follow nearcore `

I heard my computer's fans on high and noticed the CPU usage was now significantly higher:

<img width="1184" alt="Screenshot 2020-04-01 15 24 02" src="https://user-images.githubusercontent.com/1042667/78198408-68e6ba80-743d-11ea-8466-943d3de287c4.png">

It has hovered in the high nineties for a couple hours now.

During an internal discussion with @bowenwang1996 he asked for the Docker image digest. When I provided this he said:

>it looks correct. It is possible that we have some bug in state sync.

If it helps track the issue down, the digest was: `abe5d2ab2d0287b3ce3691c7273c0ad33974efbbd4cdc1108d3e69eec6fdc407`

The NEAR account I entered on the node is `mikedotdmg`

**Comment by bowenwang1996** [comment]
@Kouprin it appears that the node gets stuck in state sync. Given that this happens after your state gc change, I wonder whether it is related.

**Comment by bowenwang1996** [comment]
@mikedotexe is your node eventually synced?

**Comment by mikedotexe** [comment]
> @mikedotexe is your node eventually synced?

It did make it past 99% downloading, if that's what you're asking. It had consistently high CPU (sometimes would drop to 60%, but then returned to high ninety percents) and I saw there were `0/0/40 peers` so I shut it down last night.

I'll restart now and report back anything unusual.

**Comment by mikedotexe** [comment]
As of this morning, the betanet node synced and is hovering around 6% CPU.

**Comment by mikedotexe** [comment]
I'm not seeing this anymore. If this ticket is no longer useful, @bowenwang1996, feel free to close. I don't want to close it myself in case there were further investigations going on with the chain team that I'm unaware of.

**Comment by bowenwang1996** [comment]
Okay let's close it for now. Will reopen when we see this again.

**Comment by jimmy3dita** [comment]
Yesterday I had the same issue on my node, I've extracted the beginning of the issue, and the escalation of CPU use until 100%:

https://gist.github.com/jimmy3dita/41ff8ae917f2360d6eb7af05454c14d0

**Comment by bowenwang1996** [comment]
@jimmy3dita does it eventually resolve or it gets stuck forever?

**Comment by ilblackdragon** [comment]
If anyone observes this again, please attach your folder with data & config.
