### ISSUE TITLE
GC does not handle fork correctly

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2386]
In `clear_data`, we first clear fork data from `tail` to `gc_stop_height`. However, assuming that there is a fork from tail whose head is higher than `gc_stop_height`, this fork will not be cleared and therefore gc will get stuck. One way to solve this is to maintain some `gc_fork_head` and clear fork data from `gc_fork_head` every time. This mitigates the problem but could still be undesirable when there are multiple long forks, which means that the call to `clear_fork_data` can be blocking. In addition, this means that gc can in theory be blocked for arbitrarily long time, which can potentially be leveraged by a malicious attacker to make a validator node run out of disk space. However, I don't see a better solution now.

**Comment by Kouprin** [comment]
> assuming that there is a fork from tail whose head is higher than gc_stop_height

According to @SkidanovAlex, it's only theoretically possible to build a fork which size is big enough to break GC. @bowenwang1996 could you please make sure if this issue make sense?

**Comment by bowenwang1996** [comment]
@Kouprin this part is for sure possible. In fact, it is exactly what happens in `test_sync_from_achival_node`: a node who produces block does not receive block from other nodes (but do receive approvals) and therefore keep building on top of their own block and do not broadcast it. At some point after a long chain has been built (the head of which has height higher than gc_stop_height), they publish the entire chain, resulting in the gc getting stuck.

**Comment by Kouprin** [comment]
> Also I would like to emphasize that before my fix #2387 it would trigger the assertion failure in gc and after my fix this would cause gc to completely stall in every node because tail cannot be updated.

I got it.
I want to point, if we can build some weird situation in our testing environment it does not prove that the same is possible in reality.
`test_sync_from_achival_node` requires disabling Doomslug. How is it possible to reproduce the same with Doomslug enabled in Nightshade runtime?

**Comment by bowenwang1996** [comment]
I think with the new doomslug implementation this should be basically impossible unless 2/3 of people collude or someone has very strong control of the global network. Closing the issue.
