### ISSUE TITLE
Node cannot connect to any peers after restarting

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2395]
When there are a lot of nodes in the network (far more than max_num_peers), when a node stops and restarts, it is unable to connect to any peers. I suspect it is caused by all other peers reaching maximal number of peers and thus rejecting the connection.

**Comment by mfornet** [comment]
As you pointed out if every node is at max-capacity they will no accept new connections. One issue derived from this is that if boot-nodes are at max capacity, new nodes will not be able to connect and discover other nodes.

## How to solve this issue

Use the following variables to control the number of connections each peer will have.

- `MINIMUM_OUTBOUND_CONNECTIONS`: (10) Minimum number of outbounds connection required.
- `IDEAL_CONNECTIONS`: (35) Ideal number of active peers at any moment.
- `MAXIMUM_CONNECTIONS`: (40) Maximum number of connections (hard limit).

```
def connection_service:
    every S seconds:
        if connections > IDEAL_CONNECTIONS:
            remove_one_connection
        if outbound_connection < MINIMUM_OUTBOUND_CONNECTIONS:
            try_to_establish_new_connection

def on_inbound_connection:
     if connections == MAXIMUM_CONNECTIONS:
          reject
     else:
          accept
```

What I expect to happen in a healthy network is that all peers have around `IDEAL_CONNECTIONS` all the time, but allowing some slots for peers that are trying to connect. When new connections are established some edges will be removed such that `connections` are below `IDEAL_CONNECTIONS` again.

Some issues if implemented naively:

- We should avoid network splits, this might happens as edges can be removed without nodes going offline. One easy way to address this is to only remove an edge between A and B if there is another path between A and B (this still can fail as other edges are removed so we can use some heuristic such as number of disjoint path being above certain threshold).

- We are opening a door for malicious actor to connect to the network, and while doing that we are removing connections with honest nodes, being an excellent way to launch an eclipse attack. There is already a mechanism in place to protect us which is the `MINIMUM_OUTBOUND_CONNECTIONS`. However I propose having yet another mechanism on `remove_one_connection` which is as follows

For every active connection define:
- `LAST_MESSAGE_RECEIVED`: The time of last message received from this peer.
- `CONNECTION_ESTABLISHED_DATE`: The time we successfully establish connection.

Define globally:
- `RECENT_PEER_TIME_WINDOW`: We consider a peer live if it is in the `active_peer` list and we have received a message from it in the last `RECENT_PEER_TIME_WINDOW` seconds.

From the peers such that `LAST_MESSAGE_RECEIVED < RECENT_PEER_TIME_WINDOW` select the 20 peers such that `CONNECTION_ESTABLISHED_DATE` is older. This is the safe set of peers (those are considered reliable peer that we have been connected to for longer time). Among other peers select one at random (or using another heuristic) and drop connection to it.

**Comment by bowenwang1996** [comment]
So it seems that your prefer dropping connection that have been established later, but that poses a problem: let's say the a node just connects to you and is syncing. What prevents you from preferring dropping that connection when another node connects?

**Comment by damons** [comment]
Do we have a test for this?

**Comment by mfornet** [comment]
> So it seems that your prefer dropping connection that have been established later, but that poses a problem: let's say the a node just connects to you and is syncing. What prevents you from preferring dropping that connection when another node connects?

@bowenwang1996  This can happen. I'm wondering how harmful would it be for the node which is syncing (receiving state), because if it can still receive state from other nodes then it should be ok.

An alternative is to allocate some slots for nodes which are syncing (at most `K` slots, let's say 5). Nodes that started syncing after all slots are full should know that the connection can be dropped at any time. The idea when choosing which connection to drop is to maintain first 20 connections + at most K syncing nodes and select among other nodes.

> Do we have a test for this?
@damons No, we will have today.

**Comment by mfornet** [comment]
Thinking about this now, the best DoS attack against a node `A` is starting several fresh new nodes without state and trying to connect to `A` and start syncing. `A` will use a lot of resources (cpu/bandwidth/memory) to sync with all this nodes.

Is there any protection to this right now?

**Comment by bowenwang1996** [comment]
> @bowenwang1996 This can happen. I'm wondering how harmful would it be for the node which is syncing (receiving state), because if it can still receive state from other nodes then it should be ok.

What can happen is that if you have two nodes that connect to the network at around the same time, they can keep kicking out each other on each peer, which seems suboptimal.

> Thinking about this now, the best DoS attack against a node A is starting several fresh new nodes without state and trying to connect to A and start syncing. A will use a lot of resources (cpu/bandwidth/memory) to sync with all this nodes.

Is there any protection to this right now?

I don't think so.

**Comment by mfornet** [comment]
> Do we have a test for this?

@damons we already have the [test](https://github.com/nearprotocol/nearcore/pull/2415/files#diff-65772cf59e0714532071b475193bf047R71) which is failing.

**Comment by mfornet** [comment]
> What can happen is that if you have two nodes that connect to the network at around the same time, they can keep kicking out each other on each peer, which seems suboptimal.

Extended proposal:
Each node will have `IDEAL_CONNECTIONS_LO(30)` and `IDEAL_CONNECTIONS_HI(35)`. They will start creating new connections when connections go below `IDEAL_CONNECTIONS_LO` and will start dropping new connections when they have more than `IDEAL_CONNECTIONS_HI`.

If connections are above `MINIMUM_OUTBOUND_CONNECTIONS`, then we prefer to establish new connections with nodes that have minimal degree, so potentially this connections should last longer. 

Within the above procedure I expect the topology should converge fast enough to a stable state even if several nodes join at once to the network. However I'll use [the following script](https://gist.github.com/mfornet/583393d7e350617ce65765dacb91f15a) to see if it works. The script simulates the network in synchronously.

**Comment by bowenwang1996** [comment]
Sounds good to me. I am not sure whether the gap between `IDEAL_CONNECTIONS_LO` and `IDEAL_CONNECTIONS_HI` is sufficient. What if the node is in the process of establishing connection with a few peers? Is it possible that it jumps from fewer than `IDEAL_CONNECTIONS_LO` to more than `IDEAL_CONNECTIONS_HI` connections?
