### ISSUE TITLE
Rpc performance cannot handle more than 150 rps

### ISSUE THREAD

**Issue by ailisp** [nearprotocol/nearcore#2412]
Cannot handle broadcast_txn_async + tx_status rpc calls in total 150 request per second. tx used in broadcast_txn_async is createAccount Action. nonce is correctly set. If send these txns in total 150 request per second there's no timeout and transaction go through very fast (1-2s).

**Comment by bowenwang1996** [comment]
Is this the same issue as https://github.com/nearprotocol/nearcore/issues/2402 or a separate issue?

**Comment by ailisp** [comment]
Seems same one
