### ISSUE TITLE
Print release ID at nearcore node start 

### ISSUE THREAD

**Issue by jimmy3dita** [nearprotocol/nearcore#2429]
## As a user, I want to know if my node is up to date, such that I can promptly update it
This is helpful for bug tracking and double-check any support request. 

## Acceptance Criteria
Print the git release ID, or any similar unique identifier at the node start:

```
nearkat@localhost:~$ docker logs nearcore |more
Apr 09 23:08:14.302  INFO near: Did not find "/srv/near/data" path, will be creating new store database    
Apr 09 23:08:15.076  INFO stats: Server listening at ed25519:87ckeqK4Z9KX3c7LXqhSQhugQJujgT7VrtJXksEJxcwb@0.0.0.0:24567

Apr 09 23:08:15.076  INFO >>> RELEASE VERSION HERE <<<

Apr 09 23:08:25.078  INFO stats: # 1859203 Downloading headers 90% -/4  4/4/40 peers ⬇ 49.1kiB/s ⬆ 1.7kiB/s 0.00 bps 0 gas/s CPU: 55%, Mem: 42.0 MiB    
Apr 09 23:08:35.080  INFO stats: # 1859203 Downloading headers 90% -/4  5/4/40 peers ⬇ 144.0kiB/s ⬆ 2.2kiB/s 0.00 bps 0 gas/s CPU: 57%, Mem: 51.2 MiB    
Apr 09 23:08:45.171  INFO stats: # 1859203 Downloading headers 90% -/4  5/4/40 peers ⬇ 238.4kiB/s ⬆ 2.3kiB/s 0.00 bps 0 gas/s CPU: 70%, Mem: 60.2 MiB 
```

cc @bowenwang1996 from our StakeX meeting today

**Comment by bowenwang1996** [comment]
@jimmy3dita is it acceptable if we print this in nearup instead? If so, we should transfer this issue to https://github.com/near/nearup

**Comment by ilblackdragon** [comment]
@bowenwang1996 we have `version` in `neard/main.rs` which captures the version and git release tag or commit.
