### ISSUE TITLE
near-vm-runner-standalone should include the runtime

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2431]
`near-vm-runner-standalone` should include the `runtime` crate and should be split into `near-runtime-standalone` library and executable (can be done within the same crate).

The library should expose the following methods:
* `run_single_block` -- takes the state, transactions, incoming receipts and outputs execution results, new state, and outgoing receipts. Basically wraps `Runtime::apply`;
* `run_all` -- repeatedly runs  `run_single_block` until there are no outgoing receipts.
* `set_config` -- overrides the default `RuntimeConfig`, can be used to change one field or use free config;
* `set_genesis` -- takes list of `StateRecord`s and sets the genesis using them. Basically wraps `Runtime::apply_genesis_state`;

The binary will have the following arguments that map to the above methods:
* `--genesis` -- accepts the list of state records or the path to JSON-serialized file of records;
* `--input_state` -- accepts the path to the file with the key-values of the state;
* `--output_state` -- accepts the path to the file where to write the new state;
* `--config` -- accepts the config or the path to JSON serialized config;
* `--transactions` -- accepts the list of the input transactions or the path to JSON serialized file with them.
* `--run_all` -- runs `run_all`;
* `--run_single_block` -- makes one step using `run_single_block`

**Comment by nearmax** [comment]
Actually, I see there are other issues assigned to @fckt , so I am going to assign this to @frol

**Comment by bowenwang1996** [comment]
@ilblackdragon is there any reason why this should be in phase 1? Moving to phase 2.

**Comment by nearmax** [comment]
This needs to be done soon because we already have at least three different approaches for testing cross contract calls. Phase 1 requires having lots of complex contracts that need to be tested. While we can test without this change it is preferable to consolidate our contract testing approach soon. Moving back to Phase 1.

**Comment by nearmax** [comment]
To my understanding this is already usable, however not as a command line tool. Closing.
