### ISSUE TITLE
lockup/vesting, staking pool, voting contracts should be tested through near-runtime-standalone

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2432]
lockup/vesting, staking pool, voting are contracts critical to the Mainnet launch. Currently @evgenykuzyakov uses Python script wrapped around `near-vm-runner-standalone` for some tests. However, these contracts have a very complex interaction with other contracts and with the blockchain, specifically we want to be able to test the following cases:

- [ ] Interaction between lockup/vesting contract and the staking pool;
- [ ] Staking pool interaction with the runtime through staking;
- [ ] Lockup/vesting contract interaction with the runtime through transfer;
- [ ] Interaction between lockup/vesting contract and the voting contract, in both directions: voting, and accepting the  successful vote to unlock the transfers.

Once we have a fully-working `near-runtime-standalone` we should be able to test all the above cases.

**Comment by ilblackdragon** [comment]
After thinking about it, I actually think it might be better to test full blockchain with this contracts instead.
E.g. using our nightly infrastrcutre.
I started working on this here for staking contract - #2436 (PR is incoming)

**Comment by bowenwang1996** [comment]
@ilblackdragon given your comment, should this be in phase 2 instead?

**Comment by nearmax** [comment]
See explanation here: https://github.com/nearprotocol/nearcore/issues/2431#issuecomment-619638419

**Comment by nearmax** [comment]
Most of our core contracts are already getting tested through the standalone runtime, written by @fckt . Some tests are done as unit tests without standalone runtime, which is fine. We don't need to have this as a standalone issue anymore. Closing it.
