### ISSUE TITLE
build_and_run uses private bucket to upload chain spec

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#244]
we should be mounting a file for minikube.. for s3, we can specify a bucket name as a stop gap, as users of the aws executor will already have to have their own account setup

**Comment by evgenykuzyakov** [comment]
![I know some of these words](https://user-images.githubusercontent.com/470453/54224937-ce28e000-44b7-11e9-91a6-f71e7ebde28d.gif)

@azban obsolete?

**Comment by azban** [comment]
this is obsolete for now.. we don't need to generate chain specs in this way anymore.
