### ISSUE TITLE
Genesis records for Phase 0

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2440]
Overall design of records:
 - `registrar` is empty registrar account.
 - `near` is default registrar for all the accounts before auction launches. Fund it with something like 10,000 NEAR for creating accounts for developers.
 - `treasury.near` is treasury account that will be receiving future treasury rewards with 0.1 N balance .
 - `contributors.near` is account for initial contributors funding. 
 - `foundation.near` is face foundation account with the rest of the funds.
 - `nfval1.near` is NF 1st validator (the rest validators can be created and dispatched from `foundation.near`)

**Comment by bowenwang1996** [comment]
> treasury.near is treasury account that will be receiving future treasury rewards with 0.1 N balance

Why 0.1N specifically?

**Comment by ilblackdragon** [comment]
@bowenwang1996 Because that's ~minimum for a regular account with some access keys.

**Comment by ilblackdragon** [comment]
Fixed by #2453
