### ISSUE TITLE
DevOps for Phase 0

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2441]
Ideally we should run 4 nodes across 4 data centers:
 - GCloud, AWS, Azure, Ali or Tencent Cloud?
 - These nodes should not have RPC ports open
 - Extra node for RPCs
 - Backup mechanics

**Comment by bowenwang1996** [comment]
Also should this issue be moved to https://github.com/nearprotocol/near-ops?

**Comment by ilblackdragon** [comment]
Moved to  https://github.com/nearprotocol/near-ops/issues/15
