### ISSUE TITLE
Cleaning up and organize prometheus and grafana

### ISSUE THREAD

**Issue by ailisp** [nearprotocol/nearcore#2452]
- some data was intended to collect from single node but wrongly aggregated by all validators (e.g. number of validators 4*4)
- add cpu and memory usage
- Also important to show amount of used gas in the blocks vs just tps
- update nodes, adding 8 betanet nodes and the 4 new devnet nodes, new testnet nodes

**Comment by chefsale** [comment]
There is another issue with more context being worked on.
