### ISSUE TITLE
executing clear_state_data() leads to 'Storage error. Corrupted db or invalid state.'

### ISSUE THREAD

**Issue by Kouprin** [nearprotocol/nearcore#2464]
Reproduces on garbage_collection1.py every run. Commenting `clear_state_data()` passes the test.

Plan to fix: discuss with @mikhailOK about what's wrong, then decide.

**Comment by bowenwang1996** [comment]
How critical is this issue? Do you expect this to happen under normal circumstances?

**Comment by Kouprin** [comment]
@bowenwang1996 it happened every time in Nightly until 85ecbd44120043271a9e00b6a96cdb96f34e88fd is introduced. I guess it might happen after any State Sync. Something in `clear_state_data()` is wrong and should be fixed. We need to get @mikhailOK's opinion first.

**Comment by bowenwang1996** [comment]
@Kouprin if this crashes the node we should immediately disable it and then consider how to fix it.

**Comment by Kouprin** [comment]
https://github.com/nearprotocol/nearcore/pull/2484

**Comment by Kouprin** [comment]
I investigated the situation.
All deletions work properly. The issue is invalid because garbage_collection1.py catches what described in https://github.com/nearprotocol/nearcore/pull/2470 - for node 2 Sync Block is removed and Storage goes into invalid state. That's why I cannot reproduce it after commit https://github.com/nearprotocol/nearcore/commit/85ecbd44120043271a9e00b6a96cdb96f34e88fd.
BTW, #2484 is not enough because disabling State Sync Clearing needs GC Contract changes and Tail / GC stuff updated as well. 
The issue should be closed after reverting, https://github.com/nearprotocol/nearcore/pull/2492. It's better not to include commit related to #2484 to betanet.

Tested on `garbage_collection1.py`, `state_sync3.py`, `gc_after_sync.py`, `gc_sync_after_sync.py` and `gc_sync_after_sync.py swap_nodes`
