### ISSUE TITLE
Pipe logging to file and rotate log files

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#247]
Currently logs are being discarded after application stopped/crashed. 
We should have log files that are rotated and compressed/deleted after some period of time.

**Comment by vgrichina** [comment]
Alternatively we can just pipe process output into whatever system like `multilog` that does it for you:
https://superuser.com/a/291397

**Comment by azban** [comment]
@ilblackdragon thoughts?

**Comment by evgenykuzyakov** [comment]
obsolete. We should move to `multilog` and implement a script for this if needed
