### ISSUE TITLE
Voting contract. Implementation

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2474]
From https://github.com/nearprotocol/nearcore/issues/2283#issuecomment-607425377

Voting contract will have one goal -- it will allow community to decide when to enable transfers. The proxy for the community will be validators. The contract will have access to the list of the current validators through the new host functions. Each account will be then able to cast a vote for a specific TED by calling vote() method on the voting contract (this will overwrite the previous vote with the same account). Then when someone calls ping() on that contract it verifies the following:

`There is TED for which simple majority of the current validators (weighted by stake) have casted the vote`

When such TED exists the voting contract permanently commits to it.

Design
---

`voting` probably should go into its own NEP.

Should we extend `voting` contract to support multiple proposals?

NEAR foundation account will be able to create new proposals with `new_proposal(..) -> u64` returns new proposal ID with arguments:
- `description: String` - Human readable description of the proposal
- `vote_options: Vec<String>` - Human readable description of each voting option
- `expiration_timestamp_ns: Option<U64>` - The timestamp in nanoseconds when the proposal has receive the majority of votes before it expires. 

`vote(..)` will take the following arguments:
- `proposal_id: u64` - the index of the proposal you vote on
- `votes: Vec<Balance>` - distribution of votes weighted in Balance. Staking pool needs to be able to vote on multiple options, because pool users may vote on different options. If the total vote balance exceeds the current stake of the voter, this vote will be considered invalid during resolution.

`get_result(..) -> Option<u64>` returns Some(vote_index) if the proposal was resolved:
- `proposal_id: u64` - the index of the proposal to check

`lockup` and staking pools contracts should have the same `vote` API as `voting` contract.

**Comment by bowenwang1996** [comment]
We need to expose validator information to runtime. Also it seems that whenever someone votes, the contract needs to check on existing votes to see if the stake has changed and adjust the stake accordingly, which is suboptimal but I also don't see a better option.

**Comment by evgenykuzyakov** [comment]
@bowenwang1996  Does it mean our lockup contracts have to support voting for different proposals? Meaning not only on the transfers?

**Comment by bowenwang1996** [comment]
@evgenykuzyakov good question. That is a decision that we have to make. If it is difficult to implement we can say there will be no on-chain voting until sufficient amount of tokens are unlocked.

**Comment by ilblackdragon** [comment]
I still don't understand why voting requires any changes to lockup contract?
We should be able to proxy a call to any other contract, e.g. `staking_contract_i_delegate_to.don_t_agree_with_validator_change_my_portion_of_vote()`

**Comment by evgenykuzyakov** [comment]
I think we should be able to `vote` from lockup contracts though staking pools. I also don't think the should assume voting from the staking pools without explicit votes from the fund owners.

**Comment by bowenwang1996** [comment]
@evgenykuzyakov btw I think `id` as an index is suboptimal. You need to clear expired proposals. Otherwise the contract may run out of storage.

**Comment by evgenykuzyakov** [comment]
We can keep it as a map. And just have empty entries.

**Comment by nearmax** [comment]
Discussed during middleware sync with @evgenykuzyakov and @bowenwang1996 present: https://github.com/near/community/blob/master/meetings/middleware-wg.md#initial-contract it will take us 1-2 days to implement it once the host functions are exposed. Updated the estimate accordingly.

**Comment by bowenwang1996** [comment]
https://github.com/near/core-contracts/pull/43
