### ISSUE TITLE
Tx status timeouts when transaction is missing

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2488]
Currently if transaction is missing, there is no error from `tx` RPC endpoint.

Steps to reproduce
---
1. Start local node
2. Run:
```
http post http://localhost:3030/ jsonrpc=2.0 id=123 method=tx params:='["11111111111111111111111111111111", "test0"]'
```
Observe:
```
{
    "error": {
        "code": -32000,
        "data": "Timeout",
        "message": "Server error"
    },
    "id": "123",
    "jsonrpc": "2.0"
}
```

Implementation, if the node is tracking the shard on which this account is - if it's not found we should return right away here with an not found error https://github.com/nearprotocol/nearcore/blob/5254f85c70ab6413b796a69b452a12a923750d9f/chain/client/src/view_client.rs#L219

From #2039

**Comment by bowenwang1996** [comment]
@ilblackdragon that doesn't quite work because it could be that the transaction hasn't been processed yet.

**Comment by ilblackdragon** [comment]
That's fine - we are not waiting for it to be received right now - we requesting from another node even if we tracking the shard and know it doesn't exist:

```
        if Self::need_request(tx_hash, &mut self.tx_status_requests) {
            let target_shard_id = self.runtime_adapter.account_id_to_shard_id(&signer_account_id);
            let validator = self
                .chain
                .find_validator_for_forwarding(target_shard_id)
                .map_err(|e| e.to_string())?;
            self.network_adapter.do_send(NetworkRequests::TxStatus(
                validator,
                signer_account_id,
                tx_hash,
            ));
        }
```

**Comment by bowenwang1996** [comment]
@ilblackdragon having the latest state root only means that you know the transaction hasn't yet been processed. It could be that it will be processed in the next block for example.

**Comment by ilblackdragon** [comment]
Tx RPC is not suppose to wait for transaction to arrive into the block (and current implement doesn't do that either). Instead it should check if it exists currently.
There is a bug in current implementation - even if transaction doesn't exit and this is a single node, we still send request to network - which might even not have any peers.
I'll fix this.
