### ISSUE TITLE
Replace nearcore/scripts with nearup

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2491]
Currently `nearup` has functionality that replaces the following scripts from `nearcore/scripts`:
* `start_localnet.py`;
* `start_testnet.py`;
* `start_unittest.py`;
* `stop.py`;

The following scripts are obsolete:
* `start_staging_testnet.py`;
* `start_stakewars.py`;

Also `nodelib.py` is currently re-implemented inside `nearup`. We need to de-duplicate this code by getting rid of as many scripts as possible from `nearcore/scripts`. The goal:
* Make sure we have a single go-to tool to start nodes, including for the CI. For instance we would like to use it for eth-bridge;
* Remove duplication to reduce maintenance and the surface for errors.

CC @bowenwang1996

**Comment by bowenwang1996** [comment]
We still use `start_stakewars.py` in tests, which needs to be fixed.

**Comment by ailisp** [comment]
> We still use start_stakewars.py in tests, which needs to be fixed.

Hmm yes, in 100 node. i'll replaced it with direct call to genesis-csv-to-json, keypair-generator and neard.

**Comment by ailisp** [comment]
Also there's some scripts in use in ci and could be move to near-ops:
parallel_run_tests.py
parallel_run_coverage.py
testlib.py
docker_release.sh
binary_release.sh

**Comment by mikedotexe** [comment]
This has caused some confusion as we still have docs that provide these instructions. Linking this issue:
https://github.com/near/docs/issues/363
Particularly, would be nice if there were a way for Windows users to run a node. If not, DevX would like to know this so we can adjust the page saying it's not supported.

**Comment by bowenwang1996** [comment]
>  If not, DevX would like to know this so we can adjust the page saying it's not supported.

Sure let's do that.

**Comment by chefsale** [comment]
Closing this issue in favour of https://github.com/nearprotocol/near-ops/issues/49, as we are migration all the nodes to nearup.
