### ISSUE TITLE
Migrate state and configs by default

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2498]
Going forward we want to restart nodes and maintain data & configs folders without needing to do hard forks.
As part of the solution we want to auto-upgrade state and configs when new version runs. 
Currently it actually can corrupt storage or fail with very weird errors.

Discussed with @bowenwang1996 offline, and suggestion:
 - When neard starts, first thing we load genesis as JSON and read the `protocol_version`
 - If `protocol_version` is below ours, we execute appropriate migrations on the configs and `data/` folder. 
   - Note, that migrations don't do state_dump, they actually migrate state inside the database.
   - This means, that we may need to write migrations in Rust instead.
   - Also it's worth understanding, that these migrations can be pretty painful. For example adding/removing field into `Account` structure, would require to rebuild all tries that are stored in the history.
 - Run code as normal going forward.

Note, the other part is continue working with nodes that running on previous `protocol_version` and be able to agree on moving to new protocol (separate issue).

Alternatively, we actually use `version` of the binary for this migrations and `protocol_version` will be used for network exchange protocol.

**Comment by bowenwang1996** [comment]
I think we already agreed to use `protocol_version` to refer to the version of the protocol, i.e, two nodes with different protocol versions cannot talk to each other. So I think we shouldn't use protocol version here. `config_version` is an option, but we can also migrate based on binary version, which seems more appropriate to me since sometimes the config didn't change but what changed is the storage and `config_version` would be a misnomer.

**Comment by ailisp** [comment]
As of now if there's storage format change (like adding a column, but no change in genesis), we have to bump the protocol_version so nearup would detect protocol version change and delete data to create new storage from new genesis.
We should also record storage format version in db (equivalent to the migration table in a webapp), and any changes made to storage format need a rust migration script ^ describe by @ilblackdragon

**Comment by bowenwang1996** [comment]
@ailisp please note that storage format change does not necessarily mean that the protocol version needs to change. For example if we do something with garbage collection, it is obviously not related to the protocol itself and should not result in a protocol version change. What we should do is to start using semver and bump major version when there is a storage format change and run migration scripts accordingly.

**Comment by ailisp** [comment]
I agree. What i described above is "as of now" because we have no way to migrate storage. And I suggest this "semver" should be stored in storage (like migration table). neard binary or script is aware of version of neard binary and the version of storage format (stored in storage) so it can take action once there's a difference. it's necessary because user can secretly upgrade neard binary.

**Comment by bowenwang1996** [comment]
> because user can secretly upgrade neard binary.

😂

**Comment by ilblackdragon** [comment]
@ailisp that is the proposal, if we use binary version - we need to store the one that was used to produce database somewhere in the first place.

Right now opening DB requires specifying stuff, and if the config mismatches it does some weird recovery and corrupts things. How will we be opening DB in such a way to not trigger this and still read out the version?

I suggest we just use a separate file in `data/` folder where we store latest binary version.
We can't use any external scripts though, because people will just build & ship or download single binary.

**Comment by ailisp** [comment]
ppl can arbitrarily break stuff, but we should care cases when they're not intentionally and easy to break things. It's likely
- they download a newer version of near and use it with a older storage (bypass nearup)
- they backup the data. nearup get new binary, replace the data with their backup

it's therefore more robust check and migrate based on
genesis protocol version - storage version stored in storage (i think this is the version discussed in this pr) - neard binary version
and my understanding on reading above comments:
- neard binary version matches storage version. 
- neard run when there's no data would create storage version matches binary version
- neard run when there's data and storage version mismatch it abort. (we can handle download new binary or download and run specific rust migration script in nearup)
- protocol_version is "lower" or same as storage version. lower is when we did a rust migration that:
`Note, that migrations don't do state_dump, they actually migrate state inside the database.`ne
- genesis version and content looks not important once there's data, neard is rely on storage version stored in data to behave but initially each version of neard only works one version of genesis. genesis wouldn't change often and most likely a upgrade happens in storage_version

**Comment by bowenwang1996** [comment]
@ailisp I think you didn't answer the question of where to store the storage version.

**Comment by ailisp** [comment]
@bowenwang1996 I suggest store in storage

> I suggest we just use a separate file in data/ folder where we store latest binary version.

This works too, but i suggest we store it in col_40 in db. in db it's harder to mess up and enforce a rust migration script to update it (as it touch other columns in db)

**Comment by bowenwang1996** [comment]
> suggest we store it in col_40 in db

But when you try to detect if the current binary version match the version in storage, don't you need to open the database first? But I think if the number of columns changed it will crash there.

**Comment by ailisp** [comment]
> But when you try to detect if the current binary version match the version in storage, don't you need to open the database first? But I think if the number of columns changed it will crash there.

There's a function to get all column families (i used it in backup tool so backup tool doesn't need to upgrade as we add columns). we can open with all families to read db version from db

**Comment by bowenwang1996** [comment]
@ailisp Epic!

**Comment by bowenwang1996** [comment]
Decoupled this issue a bit and created https://github.com/nearprotocol/nearcore/issues/2677.
