### ISSUE TITLE
StorageInconsistent state in pytest

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2500]
rpc_query.py fails with 
```
thread 'main' panicked at 'storage should not fail: StorageInconsistentState("Trie node missing")', neard/src/runtime.rs:1067:9
```

**Comment by Kouprin** [comment]
Can't reproduce it locally nor find `Trie node missing` error in Nightly. Test failed for another reason:
`Traceback (most recent call last):
  File "tests/sanity/rpc_query.py", line 30, in <module>
    assert False, result
AssertionError: {'jsonrpc': '2.0', 'error': {'code': -32000, 'message': 'Server error', 'data': 'Timeout'}, 'id': 'dontcare'}`

**Comment by bowenwang1996** [comment]
@Kouprin yes I'll investigate that separately, but if you run it several times it might fail with `StorageInconsistentState`

**Comment by Kouprin** [comment]
@bowenwang1996 got it. You provided a link to stderr, this is super helpful!

**Comment by bowenwang1996** [comment]
@Kouprin it should be reproducible locally now.

**Comment by bowenwang1996** [comment]
Duplicate of #2544
