### ISSUE TITLE
Add documentation generation

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/nearcore#253]
Make documentation generated from this repo and published to the website:
 - API docs
 - General docs
 - Tutorials

Possible websites: docs.rs

**Comment by ilblackdragon** [comment]
via @vgrichina that AssemblyScript is using: https://www.docz.site/

**Comment by eriktrautman** [comment]
The key requirement for the docs portal is that the interface is beautiful.  It has to be super user friendly.  EOS has strong docs.  All my thoughts on docs and education portal are at https://docs.google.com/document/d/1RvdzhviG_P9xNJyODwL4C5Jl8sLhTbc4dIBrLQdFeFI/edit?usp=sharing

**Comment by ilblackdragon** [comment]
Spun up here - https://github.com/nearprotocol/docs
TODO: put API docs there.

**Comment by ilblackdragon** [comment]
Moved to more specific issues at  https://github.com/nearprotocol/docs/issues
