### ISSUE TITLE
Nightly failure: sanity/skip_epoch.py

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#2546]
Fails consistently. Example run:

http://nightly.neartest.com/run/2cef4105736ab969470df2751e78fd3f0fc0a81d_200428_072213

Nodes don't start.

**Comment by SkidanovAlex** [comment]
Close investigation shows that

`13:08:21.798`: test0 is queried for status, reports head at 29
`13:08:21.824`: test1 updated head to 30
`13:08:21.834`: test1 is queried for status, reports 30, test fails
`13:08:21.835`: test0 updated head to 30

will fix it by querying `test0` one more time the head before checking if it is present.

**Comment by SkidanovAlex** [comment]
Pushing the fix that reduces flakiness.

If it becomes flaky again, a more proper way to fix it is to traverse all the blocks known to the boot_node following the parent links instead of relying on us seeing all the heights by querying it sufficiently frequently.

**Comment by ilblackdragon** [comment]
@SkidanovAlex so should this be closed now?

**Comment by bowenwang1996** [comment]
It didn't fail in last 6 runs. Closing for now.
