### ISSUE TITLE
Nightly failures: sanity/staking2.py and sanity/staking_repro2.py

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#2549]
Fails rarely. Example runs for `staking_repro2`:

http://nightly.neartest.com/run/2cef4105736ab969470df2751e78fd3f0fc0a81d_200428_035216
http://nightly.neartest.com/run/f625606891dec008a572ca61ec37da500c2a95cd_200428_135923

For `staking2`:

http://nightly.neartest.com/run/2cef4105736ab969470df2751e78fd3f0fc0a81d_200428_102644

Evidently fails to process one of the staking transactions in time?

**Comment by bowenwang1996** [comment]
Looks like they are already fixed. Didn't fail in last 6 runs.
