### ISSUE TITLE
Nightly failures: doomslug tests timeout / fail

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#2553]
Consistently. Example run:

http://nightly.neartest.com/run/f625606891dec008a572ca61ec37da500c2a95cd_200428_135923

**Comment by bowenwang1996** [comment]
`:test_consensus_with_epoch_switches` failed again http://nightly.neartest.com/run/338045f4abfe8f9a79edae0dc4ac0783d1c215f9_200430_115745

**Comment by damons** [comment]
Need an estimate here.

**Comment by bowenwang1996** [comment]
@damons The overall estimate is done in the epic #2400.

**Comment by ilblackdragon** [comment]
@bowenwang1996 estimates actually should be on issues - epic shouldn't have estimate and should not be included directly into release.

**Comment by bowenwang1996** [comment]
@ilblackdragon I see. Didn't realize there is double counting. But also some of these issues are closely related and if we put the estimate on the individual issues it might also cause double counting.

**Comment by bowenwang1996** [comment]
Also `test_cross_shard_tx_doomslug` sometimes fails with timeout http://nightly.neartest.com/run/755e9d017981752ff806014ceb2ee263c70c5117_200502_113818

**Comment by SkidanovAlex** [comment]
The failure that is particularly concerning is e.g.


Output:

```
Staring set of tests. Time to GST: 10000, delta: 300
 --> Took 1114800 (simulated) milliseconds and 317 heights
 --> Took 3434000 (simulated) milliseconds and 790 heights
Largest produced_height: 2045
  - tip: ((`CBjZ56QNPxAvyyXwLk9hTcUbpHdprRxv42JdeJGVLW7g`, 2045)), final_height: 1, timer height: 2048
  - tip: ((`CBjZ56QNPxAvyyXwLk9hTcUbpHdprRxv42JdeJGVLW7g`, 2045)), final_height: 1, timer height: 2048
  - tip: ((`CBjZ56QNPxAvyyXwLk9hTcUbpHdprRxv42JdeJGVLW7g`, 2045)), final_height: 1, timer height: 2048
  - tip: ((`CBjZ56QNPxAvyyXwLk9hTcUbpHdprRxv42JdeJGVLW7g`, 2045)), final_height: 1, timer height: 2048
  - tip: ((`CBjZ56QNPxAvyyXwLk9hTcUbpHdprRxv42JdeJGVLW7g`, 2045)), final_height: 1, timer height: 2048
  - tip: ((`CBjZ56QNPxAvyyXwLk9hTcUbpHdprRxv42JdeJGVLW7g`, 2045)), final_height: 1, timer height: 2048
  - tip: ((`CBjZ56QNPxAvyyXwLk9hTcUbpHdprRxv42JdeJGVLW7g`, 2045)), final_height: 1, timer height: 2048
  - tip: ((`CBjZ56QNPxAvyyXwLk9hTcUbpHdprRxv42JdeJGVLW7g`, 2045)), final_height: 1, timer height: 2048
test tests::test_fuzzy_doomslug_liveness_and_safety ... FAILED
```

Which indicates that a block at a height >2000 was produced, but the last final block still has height 1.

**Comment by bowenwang1996** [comment]
@SkidanovAlex are all messages eventually delivered?
