### ISSUE TITLE
StateChanges can break if there is more than one shard

### ISSUE THREAD

**Issue by mikhailOK** [nearprotocol/nearcore#2563]
#1910 introduces StateChanges, with the idea that a node should store all changes to the state.

Each shard has its own state transition and set of changes, and a node can track only a subset of all shards. The way the current implementation works is it flattens the sets of changes for all known shards, and writes them to `ColStateChanges` using the following code:
```
            let storage_key = KeyForStateChanges::new_from_trie_key(
                &self.block_hash,
                &change_with_trie_key.trie_key,
            );
            store_update.set(
                DBCol::ColStateChanges,
                storage_key.as_ref(),
                &change_with_trie_key.try_to_vec()?,
            );
```
This can cause a conflict of storage keys as long as `TrieKey` for changes in shards can be the same, which is a possibility:
```
pub enum TrieKey {
...
    /// Used to store indices of the delayed receipts queue (`node-runtime::DelayedReceiptIndices`).
    /// NOTE: It is a singleton per shard.
    DelayedReceiptIndices,
    /// Used to store a delayed receipt `primitives::receipt::Receipt` for a given index `u64`
    /// in a delayed receipt queue. The queue is unique per shard.
    DelayedReceipt { index: u64 },
...
```

@nearmax @frol @evgenykuzyakov

**Comment by evgenykuzyakov** [comment]
Good point. We should probably filter `trie_key` types before writing those changes to the state. `DelayedReceiptIndices` and  `DelayedReceipt` are shard specific.
