### ISSUE TITLE
GC and genesis state

### ISSUE THREAD

**Issue by mikhailOK** [nearprotocol/nearcore#2570]
`clear_block_data` has special logic where it refuses to do its work for the block on top of genesis:
```
        if height == self.get_genesis_height() {
            if let GCMode::Fork(_) = gc_mode {
                // Broken GC prerequisites found
                assert!(false);
            }
            return Ok(());
        }
```

As we apply deletions for blocks on canonical chain, the old states inevitably become invalid - applying a block at height `5` can delete some nodes created by genesis.
If this logic is meant to persist genesis state forever, it doesn't work.
We should either un-specialcase it, or if the goal is to keep the genesis state then the way to do it is to write its nodes with refcounts `+1` - that way they will never reach zero.

**Comment by bowenwang1996** [comment]
@mikhailOK is this just suboptimal code or does it actually break something as it is written now?

**Comment by mikhailOK** [comment]
just suboptimal - seems like we assume genesis state is always there when in reality it gets corrupted and should never be used

**Comment by Kouprin** [comment]
Plan to fix:
1. Remove Genesis State in GC.
2. Do not add Genesis State in `reset_data_pre_state_sync`
