### ISSUE TITLE
Failed to open the database: DBError(Error { message: "Invalid argument: You have to open all column families. Column families not opened: col38, col37" })', core/store/src/lib.rs:232:23

### ISSUE THREAD

**Issue by sl-he** [nearprotocol/nearcore#2573]
**Describe the bug**
Failed to open the database: DBError(Error { message: "Invalid argument: You have to open all column families. Column families not opened: col38, col37" })', core/store/src/lib.rs:232:23

**To Reproduce**
1. run _curl --proto '=https' --tlsv1.2 -sSfL https://up.near.dev | python3 && source $HOME/.nearup/env && nearup betanet && docker logs --follow nearcore_ 
2. View bug

**Screenshots**

**Version (please complete the following information):**
 near: Version: 0.4.13, Build: 38d54ba7-modified
docker  19.03.8
betanet

**Additional context**
Starting NEAR client docker...
Node is running!
To check logs call: docker logs --follow nearcore
Ignoring directive ``: invalid filter directive
Apr 29 07:48:19.488  INFO near: Version: 0.4.13, Build: 38d54ba7-modified
Apr 29 07:48:19.546  INFO near: Opening store database at "/srv/near/data"
thread 'main' panicked at 'Failed to open the database: DBError(Error { message: "Invalid argument: You have to open all column families. Column families not opened: col38, col37" })', core/store/src/lib.rs:232:23
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1427
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  14: neard::start_with_config
  15: near::main
  16: std::rt::lang_start_internal::{{closure}}::{{closure}}
             at src/libstd/rt.rs:52
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by bowenwang1996** [comment]
It is possible that docker failed to pull the latest image. Can you manually do `docker pull nearprotocol/nearcore:beta`?

**Comment by sl-he** [comment]
> It is possible that docker failed to pull the latest image. Can you manually do `docker pull nearprotocol/nearcore:beta`?

Yes, i try to pull docker image manually. Same error...

**Comment by bowenwang1996** [comment]
Can you manually clear `data` folder? Looks like nearup didn't clear stale data for some reason. @ailisp

**Comment by sl-he** [comment]
I try to clear after this error, of course.

**Comment by bowenwang1996** [comment]
it still doesn't work after you cleared `data` folder?

**Comment by sl-he** [comment]
Nope, is still working

**Comment by bowenwang1996** [comment]
which data folder did you clear? You need to clear `~/.near/betanet/data`

**Comment by sl-he** [comment]
Yes, i clear this directory and near client has started

**Comment by bowenwang1996** [comment]
Okay sounds like it's resolved.
