### ISSUE TITLE
TxExecutionError should not contribute to the outcome_root

### ISSUE THREAD

**Issue by fckt** [nearprotocol/nearcore#2584]
For today ExecutionStatus::Failure holds a `TxExecutionError` which contributes into hash values which are used to generate `outcome_root` and `outcome_paths`. 

It's not optimal, since proof for exact TxExecutionError contributes no value to the protocol and locks the implementation to change/improve the debugging information. `TxExecutionError` should not contribute into the `ExecutionOutcomeWithIdAndProof.proof`'s and `outcome_root`.

https://github.com/nearprotocol/nearcore/blob/650ac70cfb3474fab3658057804aee5a22be78e1/core/primitives/src/transaction.rs#L196-L208

CC @nearmax @bowenwang1996

**Comment by bowenwang1996** [comment]
It might be possible that the error information is useful. For example you may want to prove that a certain type of error happened, but I agree for that we don't need to have a full blown enum.

**Comment by nearmax** [comment]
> It might be possible that the error information is useful. For example you may want to prove that a certain type of error happened

It is an assumption, we don't have a use case of when certain error type can be useful to be proved. So we cannot decide what level of granularity is acceptable for error types. But it is clear there is a large risk of including errors into proofs. We will be removing errors from the proofs.

**Comment by damons** [comment]
We need an owner here.

**Comment by bowenwang1996** [comment]
@fckt just to be clear, the way you are going to fix it is to change what get merklized instead of changing `ExecutionStatus` right? Change to `ExecutionStatus` will cause a lot of downstream changes.

**Comment by nearmax** [comment]
> @fckt just to be clear, the way you are going to fix it is to change what get merklized instead of changing `ExecutionStatus` right? Change to `ExecutionStatus` will cause a lot of downstream changes.

Correct.

**Comment by nearmax** [comment]
Unsetting estimate. @fckt What is your estimate for this work to be completed?

**Comment by fckt** [comment]
I've set to 5

**Comment by frol** [comment]
I am going to take a look into it while working on #2536 and #2652.
