### ISSUE TITLE
Excessive memory usage on archival node

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2593]
We observed excessive memory usage from archival nodes running on betanet. Archival nodes would crash due to out of memory error after running for several hours.

**Comment by bowenwang1996** [comment]
I did some investigation and it appears that there is a massive 2GB memory leak in actix. @frol I know that you recently updated some dependencies, so do you think it could be because of the update? I wonder whether it is related to https://github.com/actix/actix-net/issues/129

**Comment by frol** [comment]
@bowenwang1996  It is reported to be fixed in actix-rt 1.1.1. Let's update.
