### ISSUE TITLE
Node keeps trying to connect to itself

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2601]
**Describe the bug**
Node keep reporting that keep connecting to itself and report warning that it received info about itself.

```
May 02 11:38:10.788  WARN network: Received info about itself. Disconnecting this peer.
May 02 11:38:10.849  WARN network: Received info about itself. Disconnecting this peer.
May 02 11:38:11.092  WARN network: Received info about itself. Disconnecting this peer.
May 02 11:38:12.644  WARN network: Received info about itself. Disconnecting this peer.
```

**Expected behavior**
At most this happens once, ideally doesn't happen at all, because we shouldn't be sending our peer info to ourselves and should determine that peerId is ours and not include it into peer table.

**Comment by bowenwang1996** [comment]
@mfornet I thought this is already fixed?
