### ISSUE TITLE
Remove unnecessary network hop in chunk distribution

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#2608]
Today the chunk distribution follows the following pattern:

1. The chunk producer `C1` produces the chunk
2. `C1` sends the erasure-coded shares (`parts`) to all the block producers (**hop1**)
3. The chunk producer `C2` that tracks the shard receives the part, and sends requests to receive the remaining shares (**hop2**)
4. All the block producers respond to the requests (**hop3**)

The hop2 is unnecessary, if all the block producers upon receiving the erasure-coded share immediately send it to all the block producers who are assigned to the shard.

There's a prototype of such an approach here:
https://github.com/nearprotocol/nearcore/commits/new-pecs

**Comment by birchmd** [comment]
Done in https://github.com/nearprotocol/nearcore/pull/2822
