### ISSUE TITLE
DISCUSS: Whether we should prefix external functions to "_near_..." 

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#262]
Currently set of function that we expose to WASM is simple and can be desired to redefine by lang. E.g.:

storage_write()
storage_read_len()
result_count()
return_value()
sender_id()
account_id()
balance()
mana_left()

Suggestion is to add a prefix to each external function, e.g.:
_near_storage_write()
_near_storage_read_len()
_near_balance()
...

**Comment by vgrichina** [comment]
So these functions are available in `env` namespace and functions defined in AssemblyScript modules get namespaces corresponding to module name. So it's actually not that easy to clash as I thought initially.
I wonder if we still want it though in case somebody's compiling/linking components on other language. That might have different limitations.

**Comment by ilblackdragon** [comment]
@evgenykuzyakov does it clash in Rust? or they also namespaced somehow?

**Comment by evgenykuzyakov** [comment]
Not happening. Let's keep as is for now.
