### ISSUE TITLE
Remove prefix "near_func_" from public facing functions in AS WASM

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#264]
Ideally we should rename actual functions to have a prefix "_near_func_" and public facing functions should have the original name. Let's say you have 2 functions:
```
function sum(a: i32, b: i32): i32 {
  return a + b;
}

export function double_it(a: i32): i32 {
  return sum(a, b);
}
```
instead of generating public facing
`near_func_double_it(): void` and keeping the current funcs `sum` and `double_it`
We should rename internal functions to:
`_near_func_double_it(a: i32): i32` and `_near_func_sum(a: i32, b: i32): i32`, while the exported function should keep the original name: `double_it(): void`.

This helps with cross-contract compatibility and RPC don't have to modify names.

It also keeps the support with other languages compiled into WASM, cause they might not have "near_func" prefixes.
cc @ilblackdragon

**Comment by evgenykuzyakov** [comment]
The complicated part here is whether we can modify the AS compiler to rename all internal function calls, e.g. new `_near_func_double_it` needs to call `_near_func_sum` now
```
export function _near_func_double_it(a: i32): i32 {
  return _near_func_sum(a, b);
}
```

**Comment by vgrichina** [comment]
This is totally doable if instead of appending bindings source to module source we actually import module.

The only problem is that in that case bindings generation has to be aware of module paths, which isn't immediately clear how to do cleanly. We might just hardcode project layout for now though.

**Comment by ilblackdragon** [comment]
For now just going to prefix function calls with "near_func_" when calling WASM inside the node.
Note, this means ppl writing rust contracts to make functions "exported" need to prefix it (we can add a macro for that is also parsing JSON there).
