### ISSUE TITLE
PromiseResult::Failed does not include reason for failure

### ISSUE THREAD

**Issue by mikedotexe** [nearprotocol/nearcore#2640]
Perhaps this is a feature request, but it's certainly blocking normal, expected flow for developers.
 
**Describe the bug/issue**
When using promises, and particularly `env::promise_then(…` a subsequent call cannot see the reason for failure using during the chain of executing promises. It's impossible to tell where the failure was, or what the message was. 

**To Reproduce**
inside an `impl`:

```rust
pub fn request_token_payable(&self, payment: U128, spec_id: Vec<u8>, callback_address: AccountId, callback_method: String, nonce: U128, data_version: U128, data: Vec<u8>) {
        let sender = env::predecessor_account_id();
        let prepaid_gas = env::prepaid_gas();

        // first transfer token
        let promise_transfer_tokens = env::promise_create(
            "v0.link.testnet".to_string(),
            b"transfer_from",
            json!({
                "owner_id": env::predecessor_account_id(),
                "new_owner_id": env::current_account_id(),
                "amount": payment,
            }).to_string().as_bytes(),
            0,
            SINGLE_CALL_GAS,
        );

        let promise_call_self_request = env::promise_then(
            promise_transfer_tokens,
            env::current_account_id(),
            b"request",
            json!({
                "sender": sender,
                "payment": payment,
                "spec_id": spec_id,
                "callback_address": callback_address,
                "callback_method": callback_method,
                "nonce": nonce,
                "data_version": data_version,
                "data": data
            }).to_string().as_bytes(),
            0,
            SINGLE_CALL_GAS
        );

        env::promise_return(promise_call_self_request);
    }

    pub fn request(&mut self, sender: AccountId, payment: U128, spec_id: Vec<u8>, callback_address: AccountId, callback_method: String, nonce: U128, data_version: U128, data: Vec<u8>) {
        env::log(b"top of request");
        // <testing
        assert_eq!(env::promise_results_count(), 1);
        let late: Vec<u8> = match env::promise_result(0) {
            PromiseResult::Successful(x) => x,
            PromiseResult::Failed => env::panic(b"The promise failed."),
            PromiseResult::NotReady => env::panic(b"The promise was not ready."),
        };
  }
```

**Expected behavior**
`PromiseResult::Failed` should return, for instance, "insufficient tokens" or something.

**Version (please complete the following information):**
Done on testnet on May 13th, 2020

**Additional context**
I believe the solution is to build out `Failed` here:
https://github.com/nearprotocol/nearcore/blob/ff60dd435b5951ba6a5fcc439dedb07dc0a7dff4/runtime/near-vm-logic/src/types.rs#L31-L36

**Comment by bowenwang1996** [comment]
That would make error message part of the protocol, which is what we are trying to avoid. @fckt

**Comment by mikedotexe** [comment]
Okay, I guess I can point users to the transaction where it's logged, like here:
https://explorer.testnet.near.org/transactions/C1ocXLZdybhZqbZcKBNUCL615hkj2SSW3A3mUy6AVBqD
I was thinking the contract could have custom error handling logic, but seems like we can parse the logs to get this.

**Comment by nearmax** [comment]
Developer can see error message when executing transaction. Writing a smart contract that would rely on a specific type of the error returned by the promise is not safe as error content is subject to change.

**Comment by mikedotexe** [comment]
@nearmax I could not see the error message.
I returned this error to try to be helpful, but other than that I have to look in the transaction logs to see what happened:
>The promise failed. Likely causes include unavailable fungible token balance and/or allowance.

<img width="1265" alt="Screenshot 2020-05-13 19 01 05" src="https://user-images.githubusercontent.com/1042667/81884262-4079d200-954c-11ea-92a8-74fd8e258336.png">

**Comment by nearmax** [comment]
It is a near-shell bug then.
