### ISSUE TITLE
Lockup contract. Tests

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2661]
As discussed during the middleware sync https://github.com/near/community/blob/master/meetings/middleware-wg.md#15052020 we need to add tests to the lockup contract. We can use the standalone runtime for this. Unfortunately there is a mutual dependence between whitelist contract, staking pool contract, and lockup contract. For now we are going to tests lockup contract using stubs instead of other contracts. @evgenykuzyakov estimates that it will take about 5 days for 3 people. Setting estimate to 21.

Also blocked by https://github.com/nearprotocol/nearcore/pull/2504

**Comment by bowenwang1996** [comment]
Is it better to move such issues to https://github.com/near/initial-contracts/? They are not really specific to nearcore.

**Comment by nearmax** [comment]
@evgenykuzyakov Do I understand correctly that this is done? Closing it, please reopen if it is not.
