### ISSUE TITLE
Release notes should contain features & fixes

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2673]
Currently our release notes for releases just contain the last commit when release was cut:
https://github.com/nearprotocol/nearcore/releases/tag/stable-2020-04-13

Instead it should be similar to https://github.com/cosmos/cosmos-sdk/releases/tag/v0.38.2

Not sure if we also should have similar for betanet releases, but at least it can have all PRs that contained in description instead of just latest commit.

**Comment by chefsale** [comment]
There is a Github Python API https://github.com/PyGithub/PyGithub which I would like to integrate into our scripts because currently we manually do this through bash, this supports most of the functionalities of git(hub) through an API, but I need an GITHUB_TOKEN to authenticate, but can't generate one because I'm not an admin in the org/repo.

**Comment by chefsale** [comment]
Got the admin rights, thanks @ailisp . Will take a look into integrating PyGithub tomorrow and adding support for this.

**Comment by bowenwang1996** [comment]
@chefsale sounds great. How is that related to this particular isse?

**Comment by ailisp** [comment]
I guess we'll need to use github api to programmatically do github release,
with given text

**Comment by chefsale** [comment]
I started working on this, generated an API key added it to buildkite, so I can refactor the current tagging script and use the pygithub API like this:

```
 14 repo = git.get_repo('nearprotocol/nearcore')                                    
 15                                                                           
 16 repo.create_git_tag_and_release(tag="testing",                                  
 17                                 tag_message="tag message",                      
 18                                 release_name='Release vesion',                  
 19                                 release_message='Release message',              
 20                                 type='commit',                                  
 21                                 object=commit)           
```

**Comment by chefsale** [comment]
Created a sample release with bugfixes in the past month:
https://github.com/nearprotocol/nearcore/releases/tag/release-2020-05-20.
this filters the bugfixes by the tag bug.

1. for features can you please provide me with a list of tags you want @ilblackdragon @damons @bowenwang1996  @ailisp 
2. as well we have to make sure we tag our issues with bug and others to make sure they get added to the release message, we have to communicate that to the team.

**Comment by ailisp** [comment]
Looks great!

**Comment by chefsale** [comment]
Created automation for extracting features and bug fixes. The follow up is to communicate the tagging system and these changes to the team and in a README.

https://github.com/nearprotocol/nearcore/releases/tag/1.0.0

**Comment by bowenwang1996** [comment]
@chefsale Let's not close this issue before the solution fully works. Some problems that I see:

* Bugfixes have overlaps with improvements.
* Improvements include issues that we close not because we implemented them, but because we decide not to got with them.

In general I wonder whether full automation is the best option here. It seems that *some* manual review is required.

**Comment by chefsale** [comment]
1. Bugfixes don't have overlaps with improvements anymore, I have fixed this yesterday if you look at the newest release.
2. We can automatically generate the report, but we are free to delete things which aren't relevant. Even tag them as obsolete or something and make the report not include them.

**Comment by bowenwang1996** [comment]
Okay that sounds good. I think we can do automatic generation with manual review. Does your tool support adding stuff manually? I imagine it would be nice to add some high-level summary (if it is necessary).

**Comment by chefsale** [comment]
I could add that easily, but I don't see the point of adding in to the tool. You can easily adapt the release in the github UI which also supports nice markdown editing which makes things much easier than adding it to the tool, if that makes sense?

You can see it here: https://github.com/nearprotocol/nearcore/releases/tag/1.0.0 if you click edit release.

**Comment by bowenwang1996** [comment]
Ah I see. We haven't really used the github UI much before :)
