### ISSUE TITLE
Empty results of testing in Nightly

### ISSUE THREAD

**Issue by Kouprin** [nearprotocol/nearcore#2679]
No Nightly execution results available. Example: http://nightly.neartest.com/run/master_f7345258e6daf8ae229d05583648c08d5239e899_20200518_234019

Result: `<table></table>`

**Comment by ailisp** [comment]
Fixed today since this:
https://nightly.neartest.com/run/master_10f37852a685db743df7646ee71d3a3d1d607799_20200519_174617
