### ISSUE TITLE
Authority should evenly distribute the stake of the same participant

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#268]
Currently, authority distributes the stake randomly across the given blocks. However, if someone has a large stake they should not end-up with this stake in the same epoch, for liveness reasons (they won't be able to handle the load required for TxFlow to function properly). Instead, their stake should be spread as much as possible across the blocks. Ideally, if the stake/number of seats is less than the number of blocks in the given day, then each block would have at most one stake of the given peer.

**Comment by evgenykuzyakov** [comment]
@nearmax obsolete?

**Comment by nearmax** [comment]
Not obsolete.

**Comment by ilblackdragon** [comment]
Closing as obsolete for Nightshade.
