### ISSUE TITLE
Libp2p should allow injecting the public key

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#269]
Libp2p uses PeerId to identify peers, this id is a public key that libp2p computes internally. However, we already have a public key associated with every peer. Unfortunately, there is no way to tell Libp2p to reuse our public key, so instead we have to manually maintain a mapping between network public keys and internal public keys that we use for signing.

Adding @robertsdotpm for this issue.
CC @bowenwang1996 , @ilblackdragon

**Comment by ilblackdragon** [comment]
This not needed - libp2p public key is used for traffic encryption and should not use the same keys as transaction or block signing.
(Also libp2p allows to do it, it's substrate-network that assumes passing specific curve private key)
