### ISSUE TITLE
"nearup logs" produces panic error when network has stalled instead of displaying logs

### ISSUE THREAD

**Issue by Pete-LunaNova** [nearprotocol/nearcore#2707]
When betanet stalled running `nearup logs` or `nearup logs --follow` produces the following error:

```  
12: rust_begin_unwind
             at src/libstd/panicking.rs:419
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  14: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  15: near::main
  16: std::rt::lang_start_internal::{{closure}}::{{closure}}
             at src/libstd/rt.rs:52
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Ideally the command should be able to gracefully handle the fact that the network has stalled and still relay the logs back to the user.

**Comment by bowenwang1996** [comment]
Network stalling is not the same as node crashing. When the node crashes, what do you expect to see instead? Also this should be an issue in https://github.com/near/nearup

**Comment by Pete-LunaNova** [comment]
> Network stalling is not the same as node crashing. When the node crashes, what do you expect to see instead? Also this should be an issue in https://github.com/near/nearup

Apologies for filing this in the wrong place. Please let me know if you want me to close it here and open it under nearup.

When the network stalled, running nearup produced that error message. However, I did not stop the nearup process and just left it. When the network became operational again, I did not need to start nearup again, it was already running and I could execute `nearup logs` fine. Therefore nearup did not appear to have fatally crashed and instead looked like it came back alive all of its own accord.

**Comment by bowenwang1996** [comment]
Right. That is because of nearup also runs a separate process to watch if there is any update to the network. If you still have concerns please file it to https://github.com/near/nearup.
