### ISSUE TITLE
There are chunks with height_created == 0

### ISSUE THREAD

**Issue by Kouprin** [nearprotocol/nearcore#2719]
Caught by #2597.

After executing `tests/sanity/state_sync.py onetx 30` or another Python tests there are usually exist at least one ShardChunk with zero `height_created`.

`chunk_basic_validity > chunks > Ok(ChunkHash(`H9jsbk5R3tokxtfdP3PjmNLtaUM2HSXibrbxH5sxSBmi`)) > Invalid ShardChunk ShardChunk { chunk_hash: ChunkHash(`H9jsbk5R3tokxtfdP3PjmNLtaUM2HSXibrbxH5sxSBmi`), header: ShardChunkHeader { inner: ShardChunkHeaderInner { prev_block_hash: `11111111111111111111111111111111`, prev_state_root: `HyuEMALE5zDzhyJiAtLqXDKXAtn99UZuQKSeLa3SDVCc`, outcome_root: `11111111111111111111111111111111`, encoded_merkle_root: `3HH1fYqnCGMx2ZmL4sLcTuu2Yovg1r6KjNrPtgBATHgu`, encoded_length: 8, height_created: 0, shard_id: 0, gas_used: 0, gas_limit: 1000000000000000, balance_burnt: 0, outgoing_receipts_root: `11111111111111111111111111111111`, tx_root: `11111111111111111111111111111111`, validator_proposals: [] }, height_included: 0, signature: ed25519:1111111111111111111111111111111111111111111111111111111111111111, hash: ChunkHash(`H9jsbk5R3tokxtfdP3PjmNLtaUM2HSXibrbxH5sxSBmi`) }, transactions: [], receipts: [] } stored, height_created == 0`

**Comment by bowenwang1996** [comment]
I am confused. Why is this an issue? Chunks in genesis have `height_created` equal to 0.

**Comment by Kouprin** [comment]
> I am confused. Why is this an issue? Chunks in genesis have `height_created` equal to 0.

There must be no chunks in Genesis.

**Comment by Kouprin** [comment]
Discussed offline. There are Chunks in Genesis
