### ISSUE TITLE
Requesting a garbage collected block hangs instead of returning an error

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#2722]
According to nightly logs, it started happening after this commit:
https://github.com/nearprotocol/nearcore/commit/fd13098a24242f4837cad964bee43fe768472c2f

To reproduce, run

`python tests/sanity/state_sync.py manytx 250`

From `pytest`

It will fail at the end, trying to request a block from `get_all_heights`, and timing out. The block is missing because it is garbage collected, but the expectation is that in such a case we would return "Block missing error" (and `get_all_heights` is expecting such an error).

**Comment by frol** [comment]
I can reproduce the issue with `python tests/sanity/state_sync.py manytx 50` and confirm that it happens right on the mentioned commit. I have compared Cargo.lock and many dependencies got updated there, namely actix. I am digging it further.

**Comment by frol** [comment]
A low-hanging fruit of upgrading the dependencies to the latest versions didn't work. There is nothing special about the missing blocks; there are no loops on the way. I will continue invetigation in the morning.

**Comment by bowenwang1996** [comment]
Fixed in https://github.com/nearprotocol/nearcore/pull/2782
