### ISSUE TITLE
DNS Cache Poisoning Susceptibility/Mitigations

### ISSUE THREAD

**Issue by damons** [nearprotocol/nearcore#2726]
Is nearcore vulnerable to DNS cache poisoning?  If so, how are we susceptible?  What mitigations are required to secure us?

**Comment by damons** [comment]
https://www.cs.cornell.edu/~shmat/shmat_securecomm10.pdf

**Comment by mfornet** [comment]
Nodes discover and communicate with each other directly with their ip:port address, so I don't think we are vulnerable to DNS Cache Poisoning in anyway.

**Comment by bowenwang1996** [comment]
We don't rely on DNS in anyway as far as I know. Please let me know if there are any further concerns.
