### ISSUE TITLE
Transactions with 0 gas get included in the block

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2739]
https://explorer.testnet.near.org/transactions/7cL1khyKpAaFUBM62f1552KajypxwA3nxg8noZFCztD4

It still used 9 Tgas even though 0 gas was attached and only then showed the GasExceeded error.

We have absolute minimum gas requirement for block inclusion - seems like this transaction should fail even basic validation.

**Comment by bowenwang1996** [comment]
@ilblackdragon how do you want to do this? Checking that if transaction contains function call then gas attached cannot be zero?

**Comment by evgenykuzyakov** [comment]
I want to rewrite validation by splitting it into action/limits validation vs state validation. Just didn't have time to do this and not sure if I created the issue for this.

So let's use this issue to address it.

Formally:

- refactor all possible checks from the  `verify_and_charge_transaction` into `validate_transaction`.
- when an RPC node receives a transaction for a shard/account ID that it doesn't track it will run only `validate_transaction` before forwarding the transaction to a node that tracks the account.
- if the node tracks the account, then it will run full validation of `verify_and_charge_transaction` as it's done now.

- `0` attached gas is a special case that I can add a check. I think `1` gas should be fine.

**Comment by ilblackdragon** [comment]
@evgenykuzyakov we should have minimum amount of gas for an actual call of function don't we?
Also when attached gas is specified for tx - that's doesn't include gas for tx inclusion? 

Then why we report 0 attached gas in explorer? E.g. for other types of transactions we report attached gas for the tx inclusion - https://explorer.testnet.near.org/transactions/9qSATziTRmAhBQuf4979H6RmjmajPhmgBgc2Thw8R9Xs. Is this explorer bug or we output wrong information in the result?

**Comment by bowenwang1996** [comment]
> minimum amount of gas for an actual call of function don't we

It probably depends on some genesis parameters.

> that's doesn't include gas for tx inclusion

I believe that's the case. https://github.com/near/near-explorer/issues/232 @ilblackdragon you even commented on the issue.

**Comment by evgenykuzyakov** [comment]
Attached gas in the explorer is just `prepaid_gas`. There are also sent/exec fees on the function call action. The minimum gas is unclear, so we shouldn't set it to any limit, except for above 0.
