### ISSUE TITLE
Deleting log files without stopping nearcore breaks log files output, please add "delete logs" command

### ISSUE THREAD

**Issue by Cloudpostru** [nearprotocol/nearcore#2750]
OS: Ububntu 18.04
NEAR: version: 0.4.13, build:2d02b333

I deleted log files from "data" folder without turning off the nearcore broke log file output for me: nearcore stopped producing log files. Restarting the node didn't help, was able to fix log output only after I comepletely removed "data" folder (which made me sync from scratch).

Please add "delete logs" command (with options to delete logs older than x days/all). It's difficult to recover VM instances that ran out of free space (especially cloud hosting VM), which may result in stuck node/validator.

**Comment by bowenwang1996** [comment]
Those are not nearcore logs but rather rocksdb logs. The issue with excessive amount of logs generated is fixed in #2729. Please let me know if you still have further concerns.
