### ISSUE TITLE
Split VlewClient and Client into separate threads

### ISSUE THREAD

**Issue by Cloudpostru** [nearprotocol/nearcore#2751]
OS: Ububntu 18.04
NEAR: version: 0.4.13, build:2d02b333

I noticed that nearcore in general underutilizes CPU, loads heavily only 1 core which might lead to some major issues like desynchronization of node, missed blocks, loosing validator seat due to multiple missed blocks. 

I think this issue might become critical for Near protocol network stability during stress test or attack (max TX number block spam).

**Comment by nearmax** [comment]
Not sure how underutilization of CPU implies safety issues. The safety part of this description seems to be referring to: https://github.com/nearprotocol/nearcore/issues/2313 The performance part will be addressed once we start doing performance optimizations. Our current code is not optimized on the performance side as planned. Performance optimizations is not a part of Phase 1.

**Comment by nearmax** [comment]
Also, I am not aware of anyone working on it. So I am moving it from In Progress to Ice Box.

**Comment by ilblackdragon** [comment]
@nearmax Literally PR is attached to this issue - you should review it and approve :)

**Comment by damons** [comment]
Assigning to Misha per Phase 1 Triage.

**Comment by ilblackdragon** [comment]
This requires some form of https://github.com/nearprotocol/nearcore/issues/2863 to make sure that there are no race conditions between ViewClient and Client.
