### ISSUE TITLE
Benchmark node in various conditions

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2753]
We have few conditions that we are interested how nodes behave. We want to have an easy way to benchmark to see what are current bottlenecks, if some improvement really changes things, etc.

In all cases prepare large genesis state.

Conditions:
 - Run X validating nodes, load one of the nodes with lots of RPC requests to fetch state
 - Run X validating nodes, prepare large number of signed transactions, load nodes by sending these transactions.
 - Combine two previous scenarios
 
Important, write a documentation for everyone to be able to run this. Also include there current results of these benchmarks on default hardware (GCP, 2 CPU, 7.5GB RAM).

**Comment by mfornet** [comment]
We have this test with large Genesis state:
https://www.github.com/nearprotocol/nearcore/tree/master/pytest%2Ftests%2Fsanity%2Fstate_sync_massive.py
In particular this testing state sync.

**Comment by ilblackdragon** [comment]
Great, let's add that to benchmarking - important part here is setting up baseline and publishing it

**Comment by damons** [comment]
Any update here?

**Comment by ailisp** [comment]
Current devnet/mocknet + 8 loadtester provision script does this and it's running, but didn't have done a wrap up it to a documentation. Now since mocknet is running on every commit on nightly, I think just need to add load test, result, and document the process on how to do this in mocknet.

**Comment by bowenwang1996** [comment]
Superseded by #3111, #3112, and #3116
