### ISSUE TITLE
Pytests do not fail properly

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2761]
When a pytest is expected to fail due to node crash, I observe the following:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 331, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=3041): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/sanity/state_sync4.py", line 74, in <module>
    status1 = nodes[1].get_status()
  File "lib/cluster.py", line 124, in get_status
    r = requests.get("http://%s:%s/status" % self.rpc_addr(), timeout=5)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=3041): Read timed out. (read timeout=5)
```
and there is no indication of any error in the logs as well. It is not clear to me what happened and makes it very difficult to debug.

**Comment by SkidanovAlex** [comment]
A short repro would be helpful :)

**Comment by ailisp** [comment]
> A short repro would be helpful :)

Found a short repo: add a if head.height>10 { panic!("aaa"); }, and run block_production.py. Have a bad fix now (sleep(5) before mv test0 to test0_finished) trying to figure out a better fix

**Comment by ailisp** [comment]
This is still weirdly not fully resolved. In the above test case of manual panic at block 10 in block_production.py, only node1-node3 logs panic but not node0. If, time.sleep(5) before each os.rename(self.node_dir, target_path) in cleanup, then all nodes logs panic. The cleanup are execute sequentially, with node0 to be the last, but equivalently only sleep(20) at node0's cleanup, it still doesn't log panic. So far I can't understand what happens here, even doing a subprocess.check_output('grep ...') after each node shutdown and sleep(0.1) in loop cannot find when the panic is been logged

**Comment by chefsale** [comment]
So, what I believe is the cause here is that we call: status = node.get_status() on in the tests, and the cleanup code is actually killing the node so the http connection fails and we don't handle this case properly, like in this example from block_production.py:
```
45 while max_height < BLOCKS:                                                      
 46     assert time.time() - started < TIMEOUT                                      
 47     for i, node in enumerate(nodes):                                            
 48         try:                                                                    
 49             **status = node.get_status()**                                          
 50             height = status['sync_info']['latest_block_height']                 
 51             hash_ = status['sync_info']['latest_block_hash']                    
```
which means the node is down and we should be skipping here until, all nodes are down I believe.

**Comment by ailisp** [comment]
@chefsale Yeah that's a problem too. The issue i'm trying to fix is not this specific error (that get_status() is fine, although we didn't handle we _still can tell the ugly traceback is caused by node shutdown_

The problem i want to solve is node's stderr log isn't complete, therefore we couldn't tell why the node is down, whether it's by the human kill or it's crashed of some panic. Right now sleep long after the node.kill() but before os.rename(test0, test0_finished) solve the issue, but I'd like to see a less hacky fix

**Comment by chefsale** [comment]
This is an example of the test nodes failing with a fix due to the get_status() message (https://github.com/nearprotocol/nearcore/commit/5d5bf7edf9a879923d92061df296377f28198477). 

The logs are another problem, which I believe is caused by one node crapping out causing them all to exit as well because of this error message, starting the cleanups. And as @frol said you don't get consunsus anymore after that, adding the timer maybe just gives more time for the nodes to get to concensus but its not really a fix.

This is an integration test which will be flaky and things will break but, we have to write it in a way that we minimize that from happening and handling errors like this stops a lot of side effects like this one.

That's my theory, maybe I'm wrong.

**Comment by chefsale** [comment]
As well the proposed fix is only for one test, all the other ones should be changed as well.

**Comment by chefsale** [comment]
As well one thing we should change here, we shouldn't be really spawning processes (aka nodes) like this for integration testing, we will have to come up with a simpler and more deterministic way of doing this. I believe we should rethink the way we are doing this in general.

**Comment by SkidanovAlex** [comment]
What problem are we solving here?
We should not expect the tests to be written in a way that on every failure we handle logging gracefully -- it is not sustainable.

Currently it is expected that if a test fails, nodes get shut down, and some other threads in the test can therefore also fail, producing more error messages. I don't think we need to (or can in a reasonable time, both spent now, and spent going forward writing new tests) fix it.

This particular bug is separate. If nodes crash, we should have complete logs, we cannot truncate them.

**Comment by SkidanovAlex** [comment]
@ailisp 

Can you confirm that when you were running the experiments with panic("aaa") no node (not just node0) had the crash in their log?

When I run locally before your commit, I see that node2 does have the stack trace

**Comment by ailisp** [comment]
> Can you confirm that when you were running the experiments with panic("aaa") no node (not just node0) had the crash in their log?

panic at above location? no, all nodes has panic("aaa") in their log

**Comment by SkidanovAlex** [comment]
> panic at above location? no, all nodes has panic("aaa") in their log

I mean before your commit.

**Comment by ailisp** [comment]
> UPDATE: to clarify the question, I'm asking whether before your fix, if you introduce the panic line, is it the case that no node had the stack trace in their logs after the test failure

@SkidanovAlex 
Before my commit, it's 0d338b6d
I tries three times: first time all node have that panic. second time only node1-3 have. third time same as second time.

After my commit, (with the sleep(5) after node.kill()), i tried at least 5 times yesterday, they all have all panic.)

**Comment by SkidanovAlex** [comment]
@ailisp let's consolidate the conversation in https://github.com/nearprotocol/nearcore/pull/2781

In short, I don't understand why we expect more than one node to have the panic in the logs.
