### ISSUE TITLE
Batch rpc request?

### ISSUE THREAD

**Issue by ailisp** [nearprotocol/nearcore#2776]
Found this when work on bridge: https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html#batchrequest

It'd be helpful to batch arbitrary near rpc request to reduce network overhead in this way, although some request is expensive, we should limit number or cost of batched txn. WDYT? @frol @nearmax 

(It might be a client side feature, but can a client side issue reduce network overhead?)

**Comment by nearmax** [comment]
We discussed this idea with @frol , we just haven't implemented it yet.

**Comment by frol** [comment]
It is really complex topic to implement it efficiently (we will end up either implementing our own DSL or using such complex things like SQL / GraphQL). Thus, the trade-off is the complexity, and I am against doing this trade before the moment we have the measurements in place. Overall, [Network Indexer](https://github.com/nearprotocol/near-explorer/issues/236) should enable all kinds of optimizations outside of the nearcore internals.

I think we can close this issue for now as I don't think we will work on it any time soon. Feel free to add more things like use-cases and design thoughts here and re-open once we are ready to work on it.
