### ISSUE TITLE
Add the fee for loading the contract into memory

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2777]
We should add the fee that reflects the cost of compiling and loading the contract into memory.
The fee should consist of the base cost and the cost per byte. Currently, the base cost of compiling and loading the contract is already represented by `function_call_cost` (https://github.com/nearprotocol/nearcore/blob/0456008492e57612e44b994aa75519a03606874c/runtime/near-runtime-fees/src/lib.rs#L152), however we don't have a cost of calling a contract per byte size of the contract. (Note, `function_call_cost_per_byte` is the cost per byte of the arguments).
This fee should be encapsulating the worst case, when there are no caches and the contract is compiled and loaded into the memory on each single invocation.

**Comment by olonho** [comment]
We agreed that Willem will take a look on that, and I will assist as needed.

**Comment by bowenwang1996** [comment]
@willemneal this is done right?

**Comment by willemneal** [comment]
Yep by #2845
