### ISSUE TITLE
Wasmer error

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2779]
After updating to wasmer version 0.17.0, we saw some debug logging from within wasmer on betanet nodes:
```
[/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-runtime-core-0.17.0/src/instance.rs:609] &error = User(
    Any,
)
```
which refers to this line https://github.com/wasmerio/wasmer/blob/0.17.0/lib/runtime-core/src/instance.rs#L609. This debug logging is removed in the master branch of wasmer but it would be nice to know whether this is something that we need to worry about.

**Comment by olonho** [comment]
Fixed by upgrade to 0.17.1.
