### ISSUE TITLE
Node crash on "seal should be already produced"

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2785]
It is reported that a validator's node crashed on betanet on the this line https://github.com/nearprotocol/nearcore/blob/7eccdd76ef13f51d0bd0051532543168475458f7/chain/chunks/src/lib.rs#L275.

**Comment by NAKsir-melody** [comment]
I just curiouse about, if entry.parts.len() & nu._data_parts() are all zero.
Can we reconstruct something with empty datas?
let seal = self.active_demurs.remove(chunk_hash).expect("seal should be already produced");

means, there is no chunck_hash in hashmap.

**Comment by frol** [comment]
NEAR nodes crashed with this error as well (only node0 and node2 were running when I started resolving the incident, all the RPC nodes and two validation nodes were dead).

Booting the nodes back without any changes or forks unstalled the network and it seems to operate normally now.

**Comment by frol** [comment]
I assign this issue to @birchmd since git points out that this line was introduced in #2702

**Comment by zavodil** [comment]
My node is still alive but I often see this error in output:

```[/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-runtime-core-0.17.0/src/instance.rs:609] &error = User(
    Any,
)```

**Comment by frol** [comment]
That debug output is not hurting, I have found that it is already removed on the master branch of wasmer: https://github.com/wasmerio/wasmer/commit/02000cca44a95d6f4af1d90bc2459271daa450af#diff-7e612dc9771abc65090287e6a6ac3f15L609 /cc @olonho @nearmax

**Comment by frol** [comment]
Reverting PR: https://github.com/nearprotocol/nearcore/pull/2787

**Comment by frol** [comment]
There is already a PR with the fix #2786, so using it for canary.

**Comment by bowenwang1996** [comment]
@NAKsir-melody 

> I just curious about, if entry.parts.len() & num._data_parts() are all zero.

That can never happen
