### ISSUE TITLE
Node should not serve rpc before it is synced

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2795]
If a node is syncing, it can return old data for rpc queries, which can cause a lot of confusions. So it probably makes sense to not serve rpc other than status.

**Comment by frol** [comment]
Should transaction submission be available during syncing?

The implementation should be as simple as splitting [the methods match](https://github.com/nearprotocol/nearcore/blob/08e1443a99401ea0b8bf47286f4990a53d76b78b/chain/jsonrpc/src/lib.rs#L213-L236) based on [the status received from ViewClient](https://github.com/nearprotocol/nearcore/blob/08e1443a99401ea0b8bf47286f4990a53d76b78b/chain/jsonrpc/src/lib.rs#L389).
