### ISSUE TITLE
Garbage collection is unacceptably slow

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2806]
When the node garbage collects data, it invokes `clear_data`, which deletes old block and chunk data. However, in practice we have observed extraordinary slowness in this function. Under current setup, at every call to `clear_data`, we garbage collect 100 heights worth of data and it takes 30-60s to execute after the network has been running for a while, which is absolutely devastating and unacceptable. I suspect that this has something to do with rocksdb compaction and deletion of data might have triggered compaction, which can take a while to run, depending on the size of the data. To address this issue, we should
* in the short term find temporary solution (better than #2807) that minimizes the time spent on garbage collection.
* After the temporary fix, we should develop comprehensive benchmarks to test and fine-tune rocksdb options, as well as our garbage collection parameters, or find some other ways to fully fix this issue.

**Comment by bowenwang1996** [comment]
@mikhailOK @frol please help if you know anything related to rocksdb options.

**Comment by Kouprin** [comment]
test

**Comment by Kouprin** [comment]
It seems I can't resolve it now. Please assign on me when becomes actual.
