### ISSUE TITLE
Nightly failures due to storage inconsistency

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2817]
Storage inconsistencies test failures:
 - http://nightly.neartest.com/test/pytest/pytest_sanity_state_sync_py_manytx_30
 - http://nightly.neartest.com/test/pytest/pytest_sanity_state_sync_late_py_notx
 - http://nightly.neartest.com/test/pytest/pytest_sanity_block_sync_py
 - http://nightly.neartest.com/test/pytest/pytest_sanity_state_sync3_py

Other failures:
 - http://nightly.neartest.com/test/pytest/pytest_sanity_staking_repro1_py
 - http://nightly.neartest.com/test/pytest/pytest_sanity_staking_repro2_py

**Comment by Kouprin** [comment]
https://github.com/nearprotocol/nearcore/pull/2819 fixes storage inconsistency failures only.
