### ISSUE TITLE
useful near_is_validator metric

### ISSUE THREAD

**Issue by mabalaru** [nearprotocol/nearcore#2839]
At the moment in the RPC:3030/metrics there is no metric showing that the current node is a validator or not.
It should be very useful to have this metric so that we can monitor the status and trigger an alert if the node is not a validator anymore.

**Comment by mfornet** [comment]
@mabalaru this metric was added in #2804, it will be available after the next upgrade and it will be available as a prometheus metric at `RPC:3030/metrics`

Check a node running exposing this metric right now here: http://34.94.189.12:3030/metrics

Notice the `is_validator` gauge.
