### ISSUE TITLE
Test zero downtime upgrade for validators

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2840]
In https://github.com/near/docs/issues/341, @ilblackdragon described the way for validators to seamlessly upgrade their nodes (by spinning up a new node and stake with a new key). However, we have not yet done any testing to make sure that this works in practice. There should at least be some sanity test to show that the procedure described in https://github.com/near/docs/issues/341 isn't trivially broken.

**Comment by mfornet** [comment]
I can attest this doesn't work today. AccountId/ValidatorKey is not propagated properly when new node with the same account is announced. 

Also, in the network level code it is assumed that each account id is associated with a at most one node_key at all times. But we should relax this condition a bit to be: Each account id is associated with at most one pair (node_key, epoch_id). This will require that the network layer should be aware of the current epoch, which is something undesired.

**Comment by bowenwang1996** [comment]
Fixed in #2846
