### ISSUE TITLE
High Swap Usage but Plenty of RAM Available

### ISSUE THREAD

**Issue by gaia** [nearprotocol/nearcore#2847]
**Describe the bug**

running current version for betanet stakewars

`for file in /proc/*/status ; do awk '/VmSwap|Name/{printf $2 " " $3}END{ print ""}' $file; done | sort -k 2 -n -r | less` shows me near using 1465876 kB of swap space.

`free -h`
![image](https://user-images.githubusercontent.com/87547/84539756-dec29a00-aca8-11ea-8df8-eb4c7276a432.png)

`top`
`PID USER 20   0 3479604 1.287g   9696 S  29.3  5.5 592:07.48 near`

Note that I have 24GB of RAM and 10GB available

**To Reproduce**
`near betanet --nodocker`

**Expected behavior**
Is so much swap usage, when there is RAM available, by default?

**Comment by bowenwang1996** [comment]
Are you sure that it is neard that uses the swap space? That 13G of memory for sure cannot be all consumed by neard.

**Comment by gaia** [comment]
the 13GB is definitely not consumed by near. i have a few other daemons running.

I noticed that my swap usage increased tremendously, and i check who has the largest share, and it's near

**Comment by ilblackdragon** [comment]
@gaia neard doesn't do anything special with swap/memory. Might be some configuration on your side that pushes background processes into swap?
