### ISSUE TITLE
The node stopped producing blocks at the beginning of the epoch

### ISSUE THREAD

**Issue by narniec** [nearprotocol/nearcore#2852]
This morning I noticed that my node stopped producing blocks. I immediately opened the logs and saw the following:
![photo_2020-06-15_16-54-43](https://user-images.githubusercontent.com/64380122/84665790-edb77f80-af28-11ea-802e-0bf63fd4ef7a.jpg)
I rebooted the node, but it didn't solve the problem. After deleted folder data /root/.near/betanet/data and it helped
Blocks were no longer produced at the beginning of the epoch (only 1, an hour later, another 1 block)
![333](https://user-images.githubusercontent.com/64380122/84672435-396e2700-af31-11ea-9ff7-237410cc69a4.PNG)
at the same time my cpu grew sharply
![cpu](https://user-images.githubusercontent.com/64380122/84673569-8ef70380-af32-11ea-9b00-e0d141a6402c.PNG)

**Version (please complete the following information):**
- nearcore commit/branch: [b30864b](https://github.com/nearprotocol/nearcore/commit/b30864b881299b820aff56c9f3b2ce7a351e1cb2)
- betanet

**Comment by bowenwang1996** [comment]
Two questions:
* Did it only happen at the beginning of an epoch?
* How were you sure that your node was not producing blocks?

**Comment by narniec** [comment]
> Two questions:
> 
> * Did it only happen at the beginning of an epoch?
> * How were you sure that your node was not producing blocks?

- Yes, at the beginning of the epoch. The previous 2 epochs fully received 100% blocks
- I received a notification in my email, I checked "near validators current" and saw my Blocks produced = 0 and i checked logs. I had this problem yesterday, but I thought it wouldn't happen again

**Comment by bowenwang1996** [comment]
> I checked "near validators current" and saw my Blocks produced = 0 and i checked logs

How many blocks were you supposed to produce when you saw there are zero blocks produced?

**Comment by narniec** [comment]
> > I checked "near validators current" and saw my Blocks produced = 0 and i checked logs
> 
> How many blocks were you supposed to produce when you saw there are zero blocks produced?
I think about 30, before that i was on the road

**Comment by bowenwang1996** [comment]
Looks like it is caused by #2806, but it is not clear to me why this only happens to your node. What kind of CPU do you use?

**Comment by narniec** [comment]
> Looks like it is caused by #2806, but it is not clear to me why this only happens to your node. What kind of CPU do you use?

My CPU:
AMD EPYC Processor (with IBPB)
![Снимок](https://user-images.githubusercontent.com/64380122/84687189-f5d1e800-af45-11ea-901c-c39bebb20830.PNG)

There are 2 more people who have the same problem the last 2 days. They have the same high CPU load. I can find out what processor they , if necessary
1.
![photo_2020-06-15_20-29-08](https://user-images.githubusercontent.com/64380122/84687800-f6b74980-af46-11ea-917d-2218cb97cd41.jpg)
2.
![photo_2020-06-15_16-28-42](https://user-images.githubusercontent.com/64380122/84687823-fcad2a80-af46-11ea-84e1-37d513eae974.jpg)

**Comment by bowenwang1996** [comment]
> 2 more people who have the same problem the last 2 days

I see. Did they report it anywhere?

**Comment by narniec** [comment]
> > 2 more people who have the same problem the last 2 days
> 
> I see. Did they report it anywhere?

No.
They wrote only in the telegram chat RU

**Comment by bowenwang1996** [comment]
@narniec how long does the high cpu usage last?

**Comment by narniec** [comment]
> @narniec how long does the high cpu usage last?

Until I stop the node and delete the data folder. My node works for 2 epochs, after which it does not produce blocks.
I set up another server.
Public_key  and account ID a good
![ll](https://user-images.githubusercontent.com/64380122/84801696-2b3f0a00-b008-11ea-8b24-55ca64b38655.png)

**Comment by bowenwang1996** [comment]
> Until I stop the node and delete the data folder.

Can you give an estimate in terms of the amount of time or number of blocks?

**Comment by narniec** [comment]
Exactly two epochs passed, and the node worked well. Now the beginning of the new epoch and in the logs immediately appeared this:
![1](https://user-images.githubusercontent.com/64380122/84812798-a0660b80-b017-11ea-8fdd-33c648bde408.PNG)
Cpu UP:
![image](https://user-images.githubusercontent.com/64380122/84812937-d86d4e80-b017-11ea-8e33-0909b453f20c.png)

**Comment by bowenwang1996** [comment]
How long does this last?

**Comment by narniec** [comment]
> How long does this last?
As i said earlier, until i delete the data folder.
Today i moved to a new server, made everything new, changed the validator key, and check how everything will work. The 3rd epoch is already underway and everything is fine!

**Comment by narniec** [comment]
I have not encountered this problem again.
