### ISSUE TITLE
RPC returns [transaction] has not been confirmed when it clearly was

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2855]
First, start the local node:
```bash
cargo run --package neard --bin neard -- --home=/tmp/testdir init --chain-id= --test-seed=alice.near --account-id=test.near --fast 
cargo run --package neard --bin neard -- --home=/tmp/testdir init --chain-id= --test-seed=alice.near --account-id=test.near --fast 
```
Then create a local project:
```bash
npx create-near-app --vanilla myproject
cd myproject
mkdir neardev/default
cp /tmp/tesdir/validator_key.json neardev/default/test.near.json
```
Also change in `src/config.js`  the following entry:
```js
    case 'testnet':
        return {
            networkId: 'local',
            nodeUrl: 'http://localhost:3030',
            contractName: CONTRACT_NAME,
            walletUrl: 'https://wallet.testnet.near.org',
            helperUrl: 'https://helper.testnet.near.org',
        };
```
Then run:
```bash
near create_account bob.test.near --masterAccount test.near
near send test.near bob.test.near 1 --masterAccount test.near 
```
Observe the transaction hash in the output.
Go to http://localhost:3030/status and copy the most recent block hash.

Then execute the following rpc request:
```bash
http post http://localhost:3030 jsonrpc=2.0 id=dontcare method=EXPERIMENTAL_light_client_proof \
params:='{
    "type": "transaction", "transaction_hash": "<observed_tx_hash>", "sender_id": "test.near", "light_client_head": "<observed_block_hash>"
  }'
```
Observe the output:
```
HTTP/1.1 200 OK
content-length: 159
content-type: application/json
date: Tue, 16 Jun 2020 01:04:39 GMT

{
    "error": {
        "code": -32000,
        "data": "2e7woi7vPBcmPzMWFtJLaVyQPbVCwPZoujJd4H7bbBrK has not been confirmed",
        "message": "Server error"
    },
    "id": "dontcare",
    "jsonrpc": "2.0"
}
```
But transaction was clearly confirmed (you can check the account balance before and after).

**Comment by bowenwang1996** [comment]
That means the next block hasn't been produced. Can you try putting a little sleep before issuing the command?

**Comment by nearmax** [comment]
> That means the next block hasn't been produced. Can you try putting a little sleep before issuing the command?

I do sleep manually in between :) since I issue these commands manually, and the node is producing blocks with `--fast`.

**Comment by nearmax** [comment]
Could it be possible that it is GCed?

**Comment by nearmax** [comment]
> Could it be possible that it is GCed?

Indeed it was... I started the node without `--fast` and it works now.

**Comment by bowenwang1996** [comment]
@nearmax can we close this issue now that it is resolved?

**Comment by nearmax** [comment]
@bowenwang1996 how do we turn off the GC?

**Comment by bowenwang1996** [comment]
@nearmax you set `archival` to be true in `config.json`
