### ISSUE TITLE
Improve transaction status and submission RPCs

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#2867]
There are two flows that can be improved by changing few things:
 - `tx-status` should optionally take transaction bytes. This would allow to not only check for the status of transaction hash inclusion, but also identify if transaction already became invalid. E.g. `tx-status` can return 3 statuses: `Success/Failure` (transaction was included but), `InvalidTx` (transaction is invalid as of this point), `Unknown`.

 - `broadcast_tx_commit` should:
   - check if transaction is valid, if not - return `InvalidTx`.
   - submit tx for execution
   - use `tx-status` on this transaction for one of the 3 statuses.
Ths will still have Timeout error in case of real timeout because validators are slow, but will allow to resend transaction via the same end point and get `InvalidTx` or `Success` if for example this transaction was included. Same as if you query `tx-status` of this transaction.

Internally, it's a small change for `tx_status_fetch` can take either hash or transaction itself. And ping TxStatus ViewClient with that. And it can then `InvalidTx` return if transaction becomes invalid during polling.

Previous discussion was here: https://github.com/near/near-api-js/issues/344

**Comment by bowenwang1996** [comment]
@ilblackdragon it seems that then we don't need `EXPERIMENTAL_check_tx`

**Comment by ilblackdragon** [comment]
@bowenwang1996 Yes, we don't with this improved flow. Good thing it's `EXPERIMENTAL`
