### ISSUE TITLE
Store Validator needs additional Consistency checks

### ISSUE THREAD

**Issue by Kouprin** [nearprotocol/nearcore#2893]
Subtask of https://github.com/nearprotocol/nearcore/issues/2597. Child of https://github.com/nearprotocol/nearcore/issues/2860.

We should add the next checks:
- [x] Each record that is in ColOutcomesByBlockHash should be reachable in ColTransactionResult (outcome_by_outcome_id_exists)
- [x] Each Block that is in ColOutcomesByBlockHash should not be deleted (outcome_id_block_exists)
- [x] Each record in ColTransactionResult should be reachable in ColOutcomesByBlockHash (outcome_indexed_by_block_hash)
- [x] Each ColStateDlInfos record should be consistent itself (state_sync_info_valid)
- [x] Each Block that is in ColStateDlInfos should not be deleted (state_sync_info_block_exists)
- [x] Each record in ColBlockInfo should be reachable in ColBlock (block_info_exists)
- [ ] Each record in ColBlock should be reachable in ColBlockInfo (block_info_block_exists, no bijection found after State Sync)
- [x] Each Epoch in ColEpochInfo should exist (epoch_validity)
- [ ] For each Block its Epoch id should be reachable in ColEpochInfo (block_epoch_exists, not true in python tests)
- [x] Block that is in ColLastBlockWithNewChunk is reachable (last_block_chunk_included)
- [x] Chunk that is in ColLastBlockWithNewChunk is reachable (last_block_chunk_included)

Discuss with @bowenwang1996 and @SkidanovAlex about more checks.

**Comment by bowenwang1996** [comment]
> There is no Chunk higher than ColLastBlockWithNewChunk

This is not true. You can reconstruct and save a chunk before receiving the block that includes the chunk.

**Comment by Kouprin** [comment]
> > There is no Chunk higher than ColLastBlockWithNewChunk
> 
> This is not true. You can reconstruct and save a chunk before receiving the block that includes the chunk.

Ok, removing. Any other guarantees?

**Comment by bowenwang1996** [comment]
There should be a bijection between blocks and block infos.

**Comment by Kouprin** [comment]
Checks are added, closing this one.
