### ISSUE TITLE
ExecutionOutcome should include the address of the account/contract that produced it

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2902]
Currently, execution outcome only contains the receipt id that produced it. In case of the bridge, it makes it unusable, since contract on Ethereum cannot verify that certain amount of tokens was burnt by the specific fungible contract on Near. The situation is even more difficult, since receipts are merkelized in a different block from their outcomes. Execution outcome should include the id of the account/contract that emitted it, similarly to how it is done on Ethereum.

**Comment by evgenykuzyakov** [comment]
It's not a `bug`. `bug` should be used when there is misbehaviour.
