### ISSUE TITLE
clear_data can delete the same transaction twice, resulting in debug_assert

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#2906]
I can only reproduce it under stress. But possibly we can figure out why that happens without having a lightweight repro, just by inspecting the logic.

The observed behavior:

Debug assert with "Transaction overwrites itself" (it is inside `StoreUpdate::commit`), that shows in the trace the following line twice (and multiple other similar lines, each occurring twice):

`  - ColTransactions 5rrivziGwNuAsKp5WqE1Z7Eh5oCPKZ6YtYL6sfZZz8Xw`

Indicating that the same transaction was cleaned up twice.
The stacktrace indicates that the `commit` is invoked from within `clear_data`.

If you do want to reproduce, check out `stress_fixed` branch and run

`python tests/stress/stress.py 3 3 3 0 staking transactions node_restart`

It reproduces relatively consistently.

**Comment by Kouprin** [comment]
As the same tx may be included in several chunks, it's possible to delete the tx as many times as amount of Forks we currently have.
The solution is to store refcount on tx usage.
