### ISSUE TITLE
state_sync_massive.py fails

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2932]
`state_sync_massive.py` fails because we don't have `genesis-populate` compiled for the nightly runner.

**Comment by bowenwang1996** [comment]
looks like it still fails because of timeout. @mfornet maybe we didn't give it enough time to run?

**Comment by mfornet** [comment]
Test is still failing after timeout was increased.

**Comment by mfornet** [comment]
Tracking timeout issue in #3130
