### ISSUE TITLE
expensive tests test_cases_testnet_rpc fail

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2934]
Many `test_cases_testnet_rpc` fail on nightly but from stdout it appears that they actually pass. It seems that there is some unclean shutdown that have caused the runner to think that the test has failed.
Example stdout http://nightly.neartest.com/run/master_3b40a61c5ce6cd1ee4dbfb3bfcdb33eea9040a39_20200701_075801/expensive/expensive_nearcore_test_cases_testnet_rpc_test__test_smart_contract_with_args_testnet/stdout
stderr http://nightly.neartest.com/run/master_3b40a61c5ce6cd1ee4dbfb3bfcdb33eea9040a39_20200701_075801/expensive/expensive_nearcore_test_cases_testnet_rpc_test__test_smart_contract_with_args_testnet/stderr

Notice the following logs in stderr
```
pure virtual method called
terminate called without an active exception
```

**Comment by bowenwang1996** [comment]
@ailisp is there any update on this? looks like they still fail on nightly.

**Comment by ailisp** [comment]
Seems i only updated check pass logic for parallel nightly. Updated and deployed now
