### ISSUE TITLE
Prevent node from locking itself out of the network by banning all peers

### ISSUE THREAD

**Issue by hendrikhofstadt** [nearprotocol/nearcore#2953]
**Version**: stable

Our node on testnet banned all peers for `HeightFraud` and got disconnected from the network.
The only way to recover was to manually write a tool to unban the peers (#2850).

Ideally a node should never ban all of its connected peers to maintain a link to the network.

**Comment by bowenwang1996** [comment]
We patched stable branch with the fix https://github.com/nearprotocol/nearcore/commit/0152d1e69d6d97bd6d34abda8e28684b08b6101b
