### ISSUE TITLE
Run near-sdk-rs tests in nearcore

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#2959]
Currently, nearcore sometimes breaks near-sdk-rs and we find it out only when someone pushes a change to near-sdk-rs and triggers the CI. Sometimes we only find it out more than a week later. We need to run near-sdk-rs tests on nearcore commits to prevent this from happening.

This addresses our recurrent discussion on how we make sure nearcore is not breaking dependent repos. CC @SkidanovAlex , @olonho , @chefsale

**Comment by chefsale** [comment]
@nearmax @ailisp @frol @vgrichina I don't have access to our travis. near-sdk-rs is hosted on travis and our nearcore is on buildkite. I think the best way to make this happen is to migrate near-sdk-rs to buildkite as well and than trigger the pipeline from nearcore. Does that makes sense? As well could somebody give me access to travis?

**Comment by chefsale** [comment]
Login with github and opening the right pages did it. I plan to migrate near-sdk-rs to buildkite than. Let me know if that works for you?

**Comment by frol** [comment]
Why do we need to migrate near-sdk-rs to buildkite? Will the failure on near-sdk-rs happening on nearcore commit fail nearcore CI instead of near-sdk-rs then?

**Comment by chefsale** [comment]
So I would move near-sdk-rs to a seperate pipeline which would be triggered on commits in near-sdk-rs repo, but if you commit to nearcore it will also run the near-sdk-rs pipeline as a step to make sure that is still passing as well. Getting that to work to trigger travis from buildkite would be pretty hacky, so maybe better to move it.

**Comment by chefsale** [comment]
And yes failure on near-sdk-rs happening on nearcore commit fail nearcore CI and on near-sdk-rs. Essentially both, until it gets fixed.

**Comment by chefsale** [comment]
Created the pipeline on buildkite: https://buildkite.com/nearprotocol/near-sdk-rs/builds/10#730aa905-b845-4195-8215-1af5641c0d60

**Comment by frol** [comment]
@chefsale will it fail near-sdk-rs on a PR to nearcore?

**Comment by chefsale** [comment]
Hmm, not sure what is the exact question? If you push a change which breaks near-sdk-rs compatability it will fail but on the PR on nearcore, it shouldn't be blocking an near-sdk-rs PR, now it will as the near-sdk-rs is broken.

**Comment by chefsale** [comment]
Near-sdk-rs runs their own tests now on buildkite as well: https://github.com/near/near-sdk-rs/pull/199. Last step is to make sure that we trigger the pipeline from nearcore.

**Comment by chefsale** [comment]
Now sdk tests are being ran inside nearcore as well: https://buildkite.com/nearprotocol/nearcore/builds/2450.

**Comment by chefsale** [comment]
cc: @nearmax @frol @SkidanovAlex you will have to make sure that SDK is now fixed and compatible otherwise tests will be failing.

**Comment by nearmax** [comment]
Assigning this fixing near-sdk-rs to @evgenykuzyakov and re-opening.

**Comment by bowenwang1996** [comment]
near-sdk-rs tests are fixed https://github.com/near/near-sdk-rs/pull/200
