### ISSUE TITLE
CPU and memory utilization not being reported in Prometheus

### ISSUE THREAD

**Issue by chefsale** [nearprotocol/nearcore#2960]
There is no data being reported in the grafana dashboards: http://grafana.neartest.com/d/CYmywxiGz/node-inspection?orgId=1.

It used to work few days ago, probably we want to fix that cc: @mfornet @bowenwang1996 @frol 

There is Prometheus data though: http://34.94.78.219:9090/graph?g0.range_input=1h&g0.moment_input=2020-07-09%2011%3A27%3A11&g0.expr=up&g0.tab=0&g1.range_input=1h&g1.expr=&g1.tab=1

**Comment by chefsale** [comment]
Actually there is no data points for cpu usage, memusage. @mfornet do you have any idea why?

http://34.94.78.219:9090/graph?g0.range_input=1h&g0.moment_input=2020-07-09%2011%3A27%3A11&g0.expr=up&g0.tab=0&g1.range_input=1h&g1.expr=&g1.tab=1

**Comment by mfornet** [comment]
Will fix it, it was after updating metric names that dashboard was not updated properly
