### ISSUE TITLE
Remove CI check for protocol version match

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2962]
Since we are moving towards proper upgrades of the node instead of doing hard forks, we should remove the CI check that asserts that `PROTOCOL_VERSION` is the same as `protocol_version` in `neard/src/genesis.json`.

**Comment by ailisp** [comment]
We solved this, still check entire neard/src/genesis.json match neard init, but not particularly require or check PROTOCOL_VERSION
