### ISSUE TITLE
test_simple_transfer fails

### ISSUE THREAD

**Issue by frol** [nearprotocol/nearcore#2992]
**Describe the bug**

CI seems to fail due to a flacky test:

```
[2020-07-15T13:56:07Z] ---- test_simple_transfer stdout ----
[2020-07-15T13:56:07Z] thread 'test_simple_transfer' panicked at 'index out of bounds: the len is 0 but the index is 0', runtime/runtime/tests/test_async_calls.rs:589:5
```

https://buildkite.com/nearprotocol/nearcore/builds/2552#d060f247-329f-4a2c-a0ca-4d86717851ac/6-3794

**To Reproduce**

Unknown

**Expected behavior**

The test should pass.

**Version (please complete the following information):**

- nearcore commit/branch: we caught it with unrelated changes in https://github.com/nearprotocol/nearcore/pull/2651

**Comment by evgenykuzyakov** [comment]
Hmm. This might be due to random fees. I wonder what fee triggers it.

**Comment by frol** [comment]
Failed again on a PR which just updates a README (https://github.com/nearprotocol/nearcore/pull/2997) file: https://buildkite.com/nearprotocol/nearcore/builds/2643#249b8945-fbf1-41b6-b2f1-1530c46a0a9f/6-3932
