### ISSUE TITLE
create bs58 serde for transactions

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#301]
this is going to be a mess because we need to duplicate all of the structs with a different serialization format (bs58)

**Comment by ilblackdragon** [comment]
Btw, we need to have a way to serialize transactions from JS / Python as well as Rust into the same binary format. It's unclear if serde is the way to do it vs writing a custom byte writer. (e.g. current thing with using Rust binary to create transaction is not really way forward).
Then we can use serde for json serialization.

**Comment by azban** [comment]
yea, i think that makes sense for now. we can return a base64 encoded transaction. and not worry about field level serialization. if we need to change in the future, we can control response type/encoding by headers.

**Comment by ilblackdragon** [comment]
I still don't understand what "base64 encoded transaction" mean and why we don't need to care about field level serialization.
#306 is the main issue tracking figuring out the transaction format.

**Comment by azban** [comment]
meaning that instead of sending over a json blob with field level serialization of bytes, we could encode the entire blob in b64. I don't think that comment makes sense with
