### ISSUE TITLE
Investigate bridge failure

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#3049]
As discussed in https://github.com/near/rainbow-bridge/issues/217 as of one week ago the bridge contracts sometimes reject headers and proofs coming from the nodes. And can be a sign that nearcore headers and proofs are not consistent with the format that the code was using a week ago, which might be a sign of an unintended breakage. We need to resolve this issue before launching Phase 1.

**Comment by nearmax** [comment]
Me and @ailisp are working on extracting reproducible tests. So far it is flaky and only manifests on the CI machines.

**Comment by ailisp** [comment]
I got an repro from logs in this: https://buildkite.com/nearprotocol/rainbow-bridge/builds/418#ee325a11-df0b-4425-8b17-b0f2ba8ce089

repro steps: 
1. checkout to https://github.com/near/rainbow-bridge/pull/227
2. yarn test in libs-sols/nearprover

**Comment by nearmax** [comment]
@bowenwang1996 here is a reproducible light client issue.

**Comment by ailisp** [comment]
My repro is wrong, it fail because missing bridge.blockMerkleRoots[406]. In ci e2e, bridge.blockMerkleRoots[406] do exist but doesn't match prover's (line 48 of NearProver.sol). Still need to output that info from bridge side to make a correct repro

**Comment by ailisp** [comment]
Found a correct repro and fixed in near/rainbow-bridge#227
