### ISSUE TITLE
Spamming with RPC transactions should not bring down

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#305]
If we can't fit transactions into the channel/queue, we should respond with an error to the RPC.

**Comment by azban** [comment]
this already is the case . seems like we need to figure out the bottleneck and configure channel size based on that

**Comment by ilblackdragon** [comment]
@azban  @nearmax Then why did it submitting transactions from Place required to reboot the node?
Also agree on finding bottleneck and figuring out right channel sizes.

**Comment by azban** [comment]
i don't think the cause was known

**Comment by ilblackdragon** [comment]
Ok, let's get #304 fixed and then double check with Places example.

**Comment by evgenykuzyakov** [comment]
@ilblackdragon @azban Is it done?

**Comment by evgenykuzyakov** [comment]
@bowenwang1996

**Comment by nearmax** [comment]
We do not have a proper stress test to verify it.

**Comment by ilblackdragon** [comment]
Closing toward a general street test task #780
