### ISSUE TITLE
Language independent serialization

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#306]
Transactions and Blocks should be serialized in the format that is language independent.
We either need to validate that we can serialize/deserialize from other languages into the same format as serde, or switch to a different format.

**Comment by ilblackdragon** [comment]
FYI @vgrichina @azban

**Comment by vgrichina** [comment]
1. serde currently doesn't make sense. You don't want to serialize binary blob as JSON array of ints. Base64 strings would be far better.
2. Same object's JSON serialization doesn't generally result in same serialized bytes. We need to introduce some rules to make it happen, e.g.:
- Don't use any whitespace
- Order fields alphabetically
- Always escape Unicode characters in strings

**Comment by azban** [comment]
yep I agree b64 is ideal for transactions , although it is a little weird to have that along with b58 for addresses.

**Comment by azban** [comment]
along the lines of conversation here: https://github.com/nearprotocol/nearcore/issues/30

what about the following:
avoid field level serialization of bytes altogether.. use deterministic JSON serialization for objects, and then use base64 to encode the entire blob. consumers will then be able to decode, and encode bytes as they see fit (base58, base64, etc).

**Comment by ilblackdragon** [comment]
From discussion on discord:
 - For transaction/blocks we can use protos. As it's predefined schema and we need byte compatibility across devices.
 - For arguments inside transactions, some form of compressed JSON. For example using Brotli with pre-initialized vocabulary.

**Comment by ilblackdragon** [comment]
Actually, after thinking about it - I think we should check how hard it is to serialize manually transaction from JS into serde format.
Also, we *probably* should remove all the proliferation of transaction types to reduce interface to absolute minimal.

**Comment by azban** [comment]
i think the enumeration should still exist. without it, usage is clunky,
validation will be hard to implement and documentation will be confusing.
however, anything outside of rust will see a transaction as something like
`{"type": "stake", "body": {"originator": "...", "amount": "...",...}}`

**Comment by ilblackdragon** [comment]
@azban There is the difference in enums in Rust vs enums in the binary format of the Transaction. I mean we don't need enums for the binary format. We can decode in them if we want to make the code more straightforward.

That said, the RPC call should be reduced back to one - sending byte sequence of the serialized transaction. And JS/Python/Rust/etc libraries can perform all the operations to build right transaction with nice API.

**Comment by azban** [comment]
still feel like we can provide a reasonable API for RPC without having to use a helper library through the enumlike syntax i posted in comment above

**Comment by evgenykuzyakov** [comment]
@azban @ilblackdragon Can we close here?

**Comment by azban** [comment]
related to https://github.com/nearprotocol/nearcore/issues/483#issuecomment-472189636

**Comment by ilblackdragon** [comment]
@azban implemented transactions, @bowenwang1996 implemented network.
