### ISSUE TITLE
[perf] Runtime: Optimize gas counter by splitting `burn_gas` and `used_gas`

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#3071]
I’m thinking we should refactor `GasCounter`  to split `burn_gas` and `used_gas` . Right now `used_gas`  includes `burn_gas` which makes logic more complicated when we need to increment only `burn_gas`

This might save us 2X in the critical path, since `used_gas` increases are more rare than `burn_gas`.

The critical path in `near-vm-logic` is the call to host function `gas(amount)` from the VM as part of gas metering. 

This change will require to touch most of the `vm-logic` host functions but will simplify the code.

**Comment by olonho** [comment]
Think it is to be done after https://github.com/nearprotocol/nearcore/pull/3038 is merged.
