### ISSUE TITLE
Create a list of hardware we support

### ISSUE THREAD

**Issue by chefsale** [nearprotocol/nearcore#3075]

**Comment by bowenwang1996** [comment]
So far we have
* CPU must support AVX instructions
* Disk must be SSD

We can add such checks to nearup as well.

**Comment by olonho** [comment]
Actually SSD requirement is an optional one, it shall not affect correctness, only performance. AVX now is checked automatically, and we are planning to eventually eliminate it as a hard requirement using updated Wasm VM. Practically speaking our machine requirements include:

  * x86-64 machine (with AVX support currently)
  * Linux operating system. @bowenwang1996 which version of Linux do we use for building node software? glibc is only backward compatible, so this is likely a limiting factor.
  * Do we want to support running nodes on Windows/macOS?
  * Do we have RAM requirements? At least 8G of RAM seems natural.

**Comment by bowenwang1996** [comment]
while SSD doesn't affect correctness, if a node does not use SSD it cannot keep up with the network and therefore I consider it to be required.

**Comment by olonho** [comment]
Think if it can keep up with the network depends on multiple factors, and currently AFAIK we don't have enough data to confirm or deny this hypothesis.

**Comment by bowenwang1996** [comment]
I did investigate this in the past. When we use HDD garbage collection became very slow because of storage read. Some read can take more than 100ms.

**Comment by chefsale** [comment]
Can we close this issue? cc: @bowenwang1996
