### ISSUE TITLE
Different RPC endpoints disagree on whether receipt of block header is known

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#3125]
See comments here: https://github.com/near/rainbow-bridge/pull/254#issuecomment-671655192

CC @ailisp , @Kouprin

**Comment by bowenwang1996** [comment]
https://github.com/near/rainbow-bridge/pull/254#issuecomment-671665710

**Comment by bowenwang1996** [comment]
looks like this is resolved.
