### ISSUE TITLE
proxy_restart.py is flaky, fails with "Connect call failed ('127.0.0.1', 24578)"

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#3134]
E.g

http://52.149.162.182:3000/#/test/6792
http://52.149.162.182:3000/#/test/7512

**Comment by bowenwang1996** [comment]
still doesn't work http://nayduck.eastus.cloudapp.azure.com:3000/#/test_history/36161

**Comment by mfornet** [comment]
Fixed in #3414
