### ISSUE TITLE
start_from_genesis.py doomslug_off is flaky

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#3138]
E.g.

http://52.149.162.182:3000/#/test/7284
http://52.149.162.182:3000/#/test/7644

```
Traceback (most recent call last):
  File "tests/adversarial/start_from_genesis.py", line 86, in <module>
    assert saved_blocks_2['result'] < saved_blocks['result'] + 10
AssertionError

```

**Comment by mikhailOK** [comment]
What the test is doing:
1. start node0 and node1, wait for 30 blocks
2. stop node0 and node1, clear data of node1
3. restart node1 and set `adv_disable_header_sync`
4. restart node0
5. Use `adv_produce_blocks` on node1, producing 10 blocks from current head
6. verify that node0 did not save those blocks

The test expects that node1 does not not sync, and produces 10 blocks from genesis to height ~20, so node0 should not save them. But node1 can still sync: some time after starting, node0 produces a new block and sends it to node1, and node1 request the chain of parents through orphan logic in `receive_block`.

So, if node1 syncs between steps 4 and 5, the test fails, but when it happens after step 5 test passes. 

Possible ways to fix the test:
- do `adv_produce_blocks` before restarting `test0` - does the test need this order?
- disable requesting orphan parents with `adv_disable_header_sync` (or make a new adversarial switch?)

**Comment by SkidanovAlex** [comment]
The first way should be OK, I don't think there's any reason for the current order of those two operations
