### ISSUE TITLE
Introduce scheduled receipts. We need them for both Stake and TxStake withdrawals

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#315]
Often user have to regenerate some mana before the tx_stake can be returned, or we manually introduce the delay. Validation stakes can only be returned after X blocks, so we need to schedule return of funds and deposit to account for stake.

**Comment by evgenykuzyakov** [comment]
Similar to #309

**Comment by ilblackdragon** [comment]
@evgenykuzyakov this is still a feature we want to implement right?

**Comment by bowenwang1996** [comment]
I think so. It is necessary for returning stakes.

**Comment by evgenykuzyakov** [comment]
Sure. It's just hard to prevent abuse with over-scheduling for the same block index. We need to gracefully handle it.

**Comment by evgenykuzyakov** [comment]
not needed
