### ISSUE TITLE
Separate storage of code from Account

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#318]
Currently code is inside Account, which makes Account large and updates of balance take longer then should.

**Comment by azban** [comment]
when we do this, we should also add the option to request code for account, or make another call so that we don't have to do this fetch and add bandwidth for requests that are only looking for stake or balance

**Comment by bowenwang1996** [comment]
Should we allow accounts without code?

**Comment by bowenwang1996** [comment]
Resolved in https://github.com/nearprotocol/nearcore/pull/332
