### ISSUE TITLE
Separate rpc.py into pynear library

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#319]
Make python library separate from cli tool.

**Comment by azban** [comment]
have working example here: https://github.com/nearprotocol/hackathon-emails/
need to fix error for passing None or bad keystore configs to `NearRPC`

**Comment by azban** [comment]
when doing this, we should clean up some stuff there..
- update naming to match new stuff (i.e. sender -> originator)
- remove _get_account_id
