### ISSUE TITLE
rpc node bug

### ISSUE THREAD

**Issue by leor-w** [nearprotocol/nearcore#3190]
**Describe the bug**
On this node, request the return of the block from 3 days ago  **Block Missing (unavailable on the node): 6oHKZvXVtSzPacFYEWGzzfqDTrZFmbQmZ9pwWrR4pWJq \n Cause: Unknown \n Backtrace: **  
https://rpc.mainnet.near.org 

**To Reproduce**
Request the above node using JSONRPC request body:

```
{
    "jsonrpc": "2.0",
    "method": "block",
    "params": {
        "block_id": 12151662
    },
    "id": 1
}
```

**Expected behavior**
I want the node to return the block information normally

**Screenshots**
![image](https://user-images.githubusercontent.com/45963588/90351263-62ff1800-e072-11ea-978e-f42bc19f97f0.png)

**Version (please complete the following information):**
mainnet

**Additional context**

**Comment by nearmax** [comment]
@bowenwang1996 , is this the case of https://github.com/nearprotocol/nearcore/issues/2976 hiding the fact that the block was GCed?

**Comment by SkidanovAlex** [comment]
"Unavailable on the node" means it was garbage collected. Non-archival nodes garbage collect information that is more than 5 epochs (2.5 days) old.
If you want to serve data that is older, you'd need to run an archival node (`neard --archive`)

**Comment by leor-w** [comment]
> "Unavailable on the node" means it was garbage collected. Non-archival nodes garbage collect information that is more than 5 epochs (2.5 days) old.
> If you want to serve data that is older, you'd need to run an archival node (`neard --archive`)

Thank you, I see, but I would like to have a archival node, which I see here.
https://docs.near.org/docs/interaction/rpc#block

**Comment by SkidanovAlex** [comment]
> > "Unavailable on the node" means it was garbage collected. Non-archival nodes garbage collect information that is more than 5 epochs (2.5 days) old.
> > If you want to serve data that is older, you'd need to run an archival node (`neard --archive`)
> 
> Thank you, I see, but I would like to have a archival node, which I see here.
> https://docs.near.org/docs/interaction/rpc#block

Sorry, I misread the issue, I was under an impression that it's your local node.
Yes, we should consider converting our RPC nodes to archival, thanks for bringing it up.

**Comment by leor-w** [comment]
Thank you for your answer. I closed the question
