### ISSUE TITLE
LightClient RPC returns unfinalized blocks

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#3206]
I ran rainbow-bridge on our current TestNet and observed that LightClient RPC returns unfinalized blocks which are promptly getting rejected by the contracts. Unfortunately, it returns unfinalized blocks in large amounts sequentially which makes it sometimes unusable.

Observe the test added by https://github.com/near/rainbow-bridge/pull/275 that contains the responses from the LightClient RPC. You can see that the block has <60% of approving stake. It has been returning unfinalized blocks for approximately 9 minutes.

Setting priority to P0 since it is blocking bridge launch this week.

Note, I've been using https://rpc.testnet.internal.nearprotocol.com/ for the node RPC, so it cannot be a malicious node.

**Comment by nearmax** [comment]
CC @Kouprin , @ailisp

**Comment by bowenwang1996** [comment]
> You can see that the block has <60% of approving stake

How did you see this? A block cannot be produced if there is less than 67% approval

**Comment by nearmax** [comment]
> > You can see that the block has <60% of approving stake
> 
> How did you see this? A block cannot be produced if there is less than 67% approval

Bridge has literally received a light client header with <60% approving stake from the node. See the attached PR it has commented out test with dumped light client header.

**Comment by SkidanovAlex** [comment]
> Bridge has repeatedly received light client headers with <60% approving stake from the node. See the attached PR it has commented out test with dumped light client header.

Which particular block has less than 60% stake?

**Comment by SkidanovAlex** [comment]
Can confirm that the block at the height ending with 218 in there appears to have less than 60% of stake, investigating further.

**Comment by SkidanovAlex** [comment]
@nearmax how is the file `libs-sol/nearbridge/test/init_validators_12640118.json` computed? It appears to be in a format different than `next_bps`. Is it just an output of validators RPC request?

**Comment by nearmax** [comment]
Yes, we compute it here: https://github.com/near/rainbow-bridge/blob/master/environment/lib/near2eth-relay.js#L71

**Comment by nearmax** [comment]
Here is the full logs dump from `near-relay` service: https://drive.google.com/file/d/1v3tbqrqAQ2hHDfgHGax5VoeqvChBF9HA/view?usp=sharing

**Comment by nearmax** [comment]
It actually looks worse than I thought the testnet node was sending bad light client headers between 2020-08-18 20:01:17.246 and 2020-08-18 11:48:23.748 -- for 8 hours!

**Comment by SkidanovAlex** [comment]
> Yes, we compute it here: https://github.com/near/rainbow-bridge/blob/master/environment/lib/near2eth-relay.js#L71

Is it correct to say that the test relies on the `validators` endpoint to return the block producers in the same order as the `next_bps`?
If yes, there's no such guarantee.

**Comment by ailisp** [comment]
> Is it correct to say that the test relies on the validators endpoint to return the block producers in the same order as the next_bps?

Yes

**Comment by SkidanovAlex** [comment]
As I said, there's no such guarantee. So likely that is what is causing it.
We should always use block producers from `next_bps` of the previous epoch.
The only question is how to fetch the very first (genesis) set of block producers. Given `validators` don't give the correct order, I'm not sure we have such a way, so we need to add it.

We should either make the RPC end point return in the same order (if it's easy), or just have the genesis ordered list somehow extractable from the genesis config.

**Comment by ailisp** [comment]
>  We should always use block producers from next_bps of the previous epoch.

This would cause near2eth-relay wait one epoch to initialize (to get next_bps of last epoch), so it's not ideal

> We should either make the RPC end point return in the same order (if it's easy)

Will be great if we can do that

**Comment by bowenwang1996** [comment]
The new rpc is introduced in https://github.com/nearprotocol/nearcore/pull/3213. It returns validators in the current epoch.

**Comment by nearmax** [comment]
@SkidanovAlex thank you for debugging it and thank you @bowenwang1996 for implementing it. I am assigning it to @ailisp since it is a bridge issue. Unfortunately I cannot transfer it to bridge repo.

**Comment by ailisp** [comment]
Looks @Kouprin have a wip PR https://github.com/near/rainbow-bridge/pull/279

**Comment by nearmax** [comment]
Closing it, since it is an issue of the bridge.
