### ISSUE TITLE
Increase RPC limit of contract deployment size

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#3231]
Currently RPC prevents contract deployments of the size that it allowed by the runtime. We should increase this limit and make it configurable without code recompilation.

**Comment by frol** [comment]
@nearmax @evgenykuzyakov what is the runtime limit of contract size? The current RPC limit is 2MB of JSON data where contract is base64-encoded (which is 33% overhead), so given the metadata size in the payload and base64 encoding overhead, I estimate the current max contract size is ~1MB.
