### ISSUE TITLE
1.13.0-rc.1 tag builds 1.13.0-beta.1

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#3273]
Steps to reproduce:
* Clone this repo and do `git checkout 1.13.0-rc.1`
* Run `cargo build -p neard`
* Check version by `neard --version`

**Comment by chefsale** [comment]
It looks like the automatoc version bump failed in the script, we have to manually bump it.

**Comment by chefsale** [comment]
The build was fine, just the tag was wrong
