### ISSUE TITLE
Upgradability test uses the wrong branch

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#3285]
`upgradable.py` still uses `beta` branch as the "stable" branch, but we have already deprecated beta and stable branch and we should use the branch that current testnet uses as the branch for testing. The branch can change dynamically, so we should use the same logic that the release script uses to find the correct branch.

**Comment by chefsale** [comment]
Created a PR to fix this issue: https://buildkite.com/nearprotocol/nearcore/builds/3512

**Comment by chefsale** [comment]
Added to use rc instead of beta: https://github.com/nearprotocol/nearcore/pull/3296
