### ISSUE TITLE
Expose execution outcomes of a given chunk via view-client

### ISSUE THREAD

**Issue by frol** [nearprotocol/nearcore#3305]
**Describe the feature request**

NEAR Indexer needs to expose execution outcomes for every chunk, but there is no relevant interface to fetch the data.

**Expected behavior**

It would be great to have a view-client method to expose the execution outcomes. I don't think we should extend any of the existing view-client methods, but rather we should add a new one.

Where should I start or maybe someone will be able to jump and implement a draft of it and I can finish the interfaces?
/cc @khorolets

**Comment by frol** [comment]
The implementation only exposes the execution outcomes for "Incoming Receipts" that were processed and included into the chunk.receipts, but there are "local receipts", which are never recorded as chunk.receipts, and they are, essentially, ephemeral though they still have execution outcomes. @evgenykuzyakov and @nearmax suggested that instead of querying execution outcomes one by one, we can extract all the execution outcomes at once using merkle root (I am not familiar with the storage to this degree, which is why I asked for help)

**Comment by bowenwang1996** [comment]
Sorry for misunderstanding what you wanted. I'll try to fix it today.
