### ISSUE TITLE
exchange integrated

### ISSUE THREAD

**Issue by haiheipijuan** [nearprotocol/nearcore#3315]
NEAR’s account design is not friendly enough for exchange access. Is there any document describing how the exchange integrated?

**Comment by bowenwang1996** [comment]
Please check out https://docs.near.org/docs/roles/integrator/exchange-integration and regarding implicit account creation, https://github.com/nearprotocol/NEPs/pull/71/

**Comment by bowenwang1996** [comment]
Also for documentation request, please open issues on https://github.com/near/docs
