### ISSUE TITLE
upgradable.py should be runnable on mac

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#3318]
Current `upgradable.py` cannot be run on mac because it tries to pull pre-compiled binary for the rc release and there is none for mac. We should fall back to compile the branch when pulling the binary failed.

**Comment by chefsale** [comment]
Possibly my PR on fixing the branch broke this.

**Comment by ngmiller** [comment]
It does appear that we are generating `Darwin` binaries, which are for mac
```
aws s3 ls s3://build.nearprotocol.com/nearcore/Darwin/
```

**Comment by chefsale** [comment]
https://app.zenhub.com/workspaces/site-reliability-engineering-5f10314fb21679001345df96/issues/nearprotocol/near-ops/167
