### ISSUE TITLE
malicious_chain.py and adv_produce_blocks

### ISSUE THREAD

**Issue by mikhailOK** [nearprotocol/nearcore#3322]
`malicious_chain.py` without `valid_blocks_only` mode always passes:
The test calls `adv_produce_blocks` on `test1`, which always makes the node crash, and then checks that `test0` does not switch to the wrong chain and passes.

Calling `adv_produce_blocks` with `valid_blocks_only=false` is just another way to write `node.kill()`.
`valid_blocks_only` mode works fine.
example: http://nayduck.eastus.cloudapp.azure.com:3000/run/352#/test/30264

**Comment by bowenwang1996** [comment]
@mikhailOK is this done?
