### ISSUE TITLE
Design EVM challenges

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#3325]
Before we release a stable version of the native EVM we need to make sure that the design allows implementation of challenges. We need to design exactly how EVM challenges will look like for all EVM operations. Note, some challenges might be tricky to implement, if we use state iteration anywhere the challenge for state iterator is not trivial to design.

**Comment by ilblackdragon** [comment]
EVM doesn't have any state iteration.
The only state iteration is done for removing subtree in state, via the same operation we use for deleting account.
Whatever we are using for account deletion - we can leverage there.

**Comment by nearmax** [comment]
Okay, let's consider this superseded by https://github.com/nearprotocol/nearcore/issues/2445 We take @ilblackdragon 's comment as a guarantee that they are enable-able.
