### ISSUE TITLE
[Tracking issue] Review Native EVM Implementation

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#3337]
Review of the native EVM implementation takes time and effort from multiple people. Specifically, the following two PRs need to be reviewed b @nearmax and @evgenykuzyakov : #3299 and #3257

It will take approximately 3 days from 2 people to review, plus some extra time in case @abacabadabacaba finds time to review it. Therefore setting estimate to 8.

CC @ilblackdragon

**Comment by evgenykuzyakov** [comment]
done
