### ISSUE TITLE
Investigate adding more tests to EVM and add low-hanging fruits

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#3340]
We need to research tests that we could add to EVM to make sure it is compatible with standard EVM implementation. @ailisp estimated that it would take 0.5 day to research what tests we should add (e.g. Ethereum test suite) and about 1 day to add low-hanging fruits that he thinks we might have. Assigning 2 days to this issue.

**Comment by ailisp** [comment]
Research on evm tests: 
https://docs.google.com/document/d/1kJ2VGK-ufyvA_izrsEuNhGORt0f3azjBxbfVeOk4PJU/edit?usp=sharing

**Comment by nearmax** [comment]
Investigation is done. Now @ailisp is going to do #3450

**Comment by artob** [comment]
@frankbraun Note the research document, above.
