### ISSUE TITLE
Decide on key store and Account interaction

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/nearcore#335]
Not sure why `Account` should know about key store vs passing key directly.  I can see it being useful if e.g. signing happens on keystore level so that there is no need to read key here.
In that case key store can e.g. be backed by hardware device doing the signing without key bytes ever leaving device.

@ilblackdragon what do you think?

_Originally posted by @vgrichina in https://github.com/nearprotocol/nearcore/pull/326/files/8def816aef28585aa9f0f29978f53cc6a3cd020d_

**Comment by ilblackdragon** [comment]
Agree with @janedegtiareva , it can be a `signer` interface, with default implementation as in-memory key store.

**Comment by evgenykuzyakov** [comment]
I think it's done
