### ISSUE TITLE
Coordinate the Testnet hardfork after Rainbow Bridge hackathon

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#3353]
In the current Testnet, some blocks are entirely missing from the storage of every validator. However, partners that user Rosetta would like to be able to re-validate all blocks from the genesis to ensure consistency of the balances (CC @frol ). Unfortunately, since blocks are not recoverable it is not possible, so we need to hardfork Testnet to rebase the genesis. Unfortunately, we don't want to fork testnet until Rainbow Bridge hackathon is finished. However, once it is done we should do it.

**Comment by bowenwang1996** [comment]
Looks like this will not be done in this milestone given the hackathon duration. Removing it from this milestone.

**Comment by frol** [comment]
@bowenwang1996 coordination (announcement and other preparations) should be done ahead of times, that is during the hackathon, shouldn’t it?

**Comment by bowenwang1996** [comment]
That's fair

**Comment by bowenwang1996** [comment]
Announcement done. Migration script done here https://github.com/nearprotocol/near-ops/pull/178 and tested by @mhalambek
