### ISSUE TITLE
Tracking ticket to coordinating Mainnet Releases

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#3354]
This is a tracking issue to account for time spent on coordinating Mainnet releases during 21.09-02.10 cycle. There are two important work items:
- [ ] Roll out the release that contains implicit account creation to unblock partner integration.
- [ ] Prepare the release that enables inflation when the voting for phase 2 is done.

**Comment by bowenwang1996** [comment]
Release that contains implicit account creation https://github.com/nearprotocol/nearcore/releases/tag/1.13.1
Release for enabling inflation prepared in https://github.com/nearprotocol/nearcore/tree/1.13.2. Will release it once the voting is done.
