### ISSUE TITLE
Create NEP that specifies how to upgrade to new fees

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#3356]
With https://github.com/nearprotocol/nearcore/issues/3158 we are going to introduce invasive changes to the runtime that we might be rolling out in increments. Since the procedure might be quite complex we would benefit from having a NEP that describes in high detail how exactly the rollout is going to happen. This issue is tracking the work of writing this NEP. Specifically we need to cover the following topics:
* Deploy to charge compilation cost
* Remove compilation cost from runner
* Empty code to produce `Crypto::default()`

**Comment by evgenykuzyakov** [comment]
Created https://github.com/nearprotocol/NEPs/issues/120
