### ISSUE TITLE
how to get the private key?

### ISSUE THREAD

**Issue by 1971192997** [nearprotocol/nearcore#3361]
1 how to get the private key to sign the transaction?

2 how to get private key from 12 word which is called seeds? 

i do not get private key from the wallet on testnet , pls help me ,thanks

**Comment by frol** [comment]
Please, use [stackoverflow (with tag #nearprotocol)](https://stackoverflow.com/questions/tagged/nearprotocol) for support questions.

Here are the resources you may find helpful:

* https://docs.near.org/docs/development/near-cli
* https://stackoverflow.com/questions/58550759/how-to-create-an-account-with-a-specific-private-key
* https://stackoverflow.com/questions/58772724/how-do-i-sign-a-message-with-a-newly-created-near-account-in-a-3rd-party-app/58772901#58772901
