### ISSUE TITLE
"Waiting for peers" gets never recovered

### ISSUE THREAD

**Issue by frol** [nearprotocol/nearcore#3362]
**Describe the bug**

Sometimes I observe a freshly started node fails to find peers for a long time, but if I just restart it, it immediately finds peers and proceeds to work just fine.

**To Reproduce**

I don't know how to reproduce, but it is not the first time I observe such behavior.

**Expected behavior**

The node should retry reaching peers and identify dead connections.

**Screenshots**

![image](https://user-images.githubusercontent.com/304265/94004432-109ccf80-fd73-11ea-8f9c-bd85ff53f2d5.png)

**Version (please complete the following information):**
- nearcore commit/branch: master as of https://github.com/nearprotocol/nearcore/commit/70c0a5c6
- rust version: rust-toolchain
- docker: no docker
- testnet

**Comment by bowenwang1996** [comment]
How long did you wait?

**Comment by frol** [comment]
@bowenwang1996 It was in this state for around half an hour.

**Comment by bowenwang1996** [comment]
That is very abnormal. @mfornet please take a look

**Comment by mfornet** [comment]
I'll take a look, but is it possible that the node got banned for some reason?

**Comment by mfornet** [comment]
Fixed in #3397
