### ISSUE TITLE
ExecutionOutcome for the Transaction expected in the same block but it is not there

### ISSUE THREAD

**Issue by khorolets** [nearprotocol/nearcore#3370]
**Describe the bug**
From slack discussion:

Guys when we were dealing with local receipts and found the way to handle them via ExecutionOutcome for transaction. I’ve asked whether I can be sure ExecutionOutcome for transaction is always in the same block (once tx just coverts to receipt for magic to start). And I had positive answer. But indexers went down recently in the place where I expect outcome to definitely be present.

Can you fill the light on in which cases outcome for transaction if definitely present in the same block and in which cases it is not guaranteed?

Example
This happened on testnet in block **17192648**
This transaction doesn’t have ExecutionOutcome returned via new ViewClient method @Bowen has created recently.
```
SignedTransactionView {
    signer_id: "aguxez.testnet",
    public_key: ed25519:3u4z3rV2cfNWAgmZXGjnFwB3T8LNPc4N6zxpvW4idjCy,
    nonce: 3917,
    receiver_id: "picks.aguxez.testnet",
    actions: [
        FunctionCall {
            method_name: "close_picks_placement",
            args: "eyJyYWNlX2lkIjoiOWlMV05yeiJ9",
            gas: 100000000000000,
            deposit: 10000000000000000000000,
        },
    ],
    signature: ed25519:3CuBf3uwGgL8oXpNFeBRneswVbvy7mUinB4BM661M1jEXhnQm1bSxFeSvhPKsFVh65nenoaoqayBm21cYiU27sQo,
    hash: `42T1tDEaP96qWFvqpaPDHQcV1xouo6DKeKnvsDEGzTzi`,
}
```
But I’ve expected it be there as I’ve been assuming ExecutionOutcome for Transaction is always in the same block as the Transaction.
Our design of Indexer Framework is based on this assumption.

**To Reproduce**
NEAR Indexer Framework Streamer panics on the block **17192648**

**Expected behavior**
ExecutionOutcome for the Transaction expected to be present in the same block.

cc @frol @evgenykuzyakov

**Comment by bowenwang1996** [comment]
Is the transaction execution outcome that is missing or is it the receipt execution outcome?

**Comment by khorolets** [comment]
@bowenwang1996 Transaction
