### ISSUE TITLE
Add extra options to print memory usage by all actors

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#3377]
We should add options to print the memory usage by actors to help check for memory leaks. This does not include memory consumed by actix itself.

**Comment by pmnoxx** [comment]
I added printing memory stats for the following
ClientActor
ViewActor
PeerActor
PeerManagerActor

I'll need to take a look whenever there are any other actors.
as part of (https://github.com/nearprotocol/nearcore/pull/3319)

**Comment by pmnoxx** [comment]
We have 7 actors in total. The first 4 I already covered. The remaining ones are WaitOrTimeout, TelemetryActor, EdgeVerifier. All of those data structures contain no data, so there isn't any point in printing stats for them.
