### ISSUE TITLE
Return readable errors from json rpc calls. 

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/nearcore#340]
A good test case is view account on an account which doesn't exist. the error response is thousands of lines long currently.

**Comment by vgrichina** [comment]
Ideally errors should reuse existing HTTP status codes. Like in case above it makes sense to return 404.

**Comment by azban** [comment]
it would be useful to create individual tickets for error cases that are not covered.

for the one mentioned here, i cannot reproduce the issue. 

```
./scripts/rpc.py view_account -a dingo
b'account dingo does not exist while viewing'
```

i deferred on implementing standard HTTP status codes because moving away from RPC was still being considered.. have we made a decision there?

**Comment by vgrichina** [comment]
I think HTTP status codes play fine with both RPCs we have now and REST. JSON-RPC seems like just additional pain for most webdevs (except ones using statically compiled languages, which is basically asking for pain anyway if you use JSON).

**Comment by vgrichina** [comment]
OOPS, didn't mean to close

**Comment by evgenykuzyakov** [comment]
@janedegtiareva @vgrichina What are the action items here?

**Comment by janedegtiareva** [comment]
It works fine now. Closing issue.
