### ISSUE TITLE
Version ShardChunkHeader

### ISSUE THREAD

**Issue by birchmd** [nearprotocol/nearcore#3410]
In order to complete https://github.com/nearprotocol/nearcore/issues/3347 we need to make the changes in the `post-phase-1` branch backwards compatible. One such change was the away hashes are computed for shard chunk headers (for details about why this change is needed see https://github.com/nearprotocol/nearcore/pull/2769#discussion_r434730109 ). To be backwards compatible, we need to know the protocol version when computing the hash (to use the old logic for old versions and the new logic for new versions). The version needed depends on the epoch in which the chunk was created, and therefore is not always computable at the time of the structure deserialization (e.g. in the peer actor).

One solution to this issue is to create a new version of the `ShardChunkHeader` which includes the protocol version with it. However, transitioning the structure from being unversioned (as it is today) to version is itself a difficult problem. The purpose of this issue is to decide how this should be done and to implement it.

Note: another solution to the core issue of computing the hash requiring a version would be to make it lazy, so that it is only computed once the protocol version is known. However, this only "kicks the can down the road" in the sense that we will likely need to modify the `ShardChunkHeader` some day in the future and we will once again face this issue.

**Comment by bowenwang1996** [comment]
@birchmd what about your idea of passing the protocol version along by creating a new version of `RoutedMessage`? Do we see any issue with that?

**Comment by birchmd** [comment]
I'm looking into it now. It looks like it could require quite a lot of code duplication, which I really would like to avoid.

**Comment by birchmd** [comment]
I am wondering if maybe instead I should add a new variant to `RoutedMessageBody` which carries a new version of `PartialEncodedChunk`, which will carry the new `ShardChunkHeader`. I'll also need to add a new version of `Block` which carries the new chunk headers as well. I think this might be less work and less code duplication overall.

**Comment by bowenwang1996** [comment]
yeah that sounds like a good plan.

**Comment by birchmd** [comment]
There is a lot of code which is touched when changing `ShardChunkHeader` to be an enum. Much of the modifications are mechanical, but still take time to complete. I am also trying to minimize the overall impact as much as possible, which takes additional time.

This issue is being closed because the current cycle is completed, but will continue in https://github.com/nearprotocol/nearcore/issues/3440 next cycle.
