### ISSUE TITLE
Node doesn't download headers, can't sync

### ISSUE THREAD

**Issue by Ivan123-ops** [nearprotocol/nearcore#3446]
**Describe the bug**
Node doesn't download headers or downloads too slowly. 
Message in logs
Telemetry data could not be sent due to: Failed to connect to host: the handshake failed: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915:: certificate has expired

**To Reproduce**
Remove .near folder and start nearup betanet

**Expected behavior**
Node doesn't download headers or downloads too slowly. 

**Screenshots**
<img width="1033" alt="Снимок экрана 2020-10-04 в 17 48 34" src="https://user-images.githubusercontent.com/58822673/95018742-46429200-066a-11eb-9753-54908d13c13f.png">

**Version (please complete the following information):**
Running with docker, latest version.

**Additional context**
Digital Ocean machine with 4CPU and 8GB+2swap

**Comment by bowenwang1996** [comment]
The node is downloading headers. It's just that there are so many headers that downloading is slow. If you wait for a while you should see it making progress.

**Comment by Ivan123-ops** [comment]
It took 2 days to sync now OK(
