### ISSUE TITLE
use cache manager for shardchaindb

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#364]
we currently don't do any garbage collection on caches and this will eventually cause memory to grow indefinitely

ref: https://github.com/paritytech/parity-ethereum/blob/7c335e87642b848f61ab3ee7bbff5964b53d6f11/ethcore/db/src/cache_manager.rs#L25

**Comment by azban** [comment]
this also needs to be done in BlockChain

**Comment by evgenykuzyakov** [comment]
@azban Where do we use caching (except for WASM)?

**Comment by azban** [comment]
https://github.com/nearprotocol/nearcore/blob/79c76189ec14bd1a82c29d6eba15361c684bccd7/core/storage/src/storages/shard.rs#L21-L23

https://github.com/nearprotocol/nearcore/blob/master/core/storage/src/storages/beacon.rs#L17-L28
