### ISSUE TITLE
cache signature verifications

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#388]
was going to implement this initially along with transaction signing but i think it would be better to be a bit more deliberate about this and take the performance loss, rather than having invalid functionality..

things that need  to happen:
- cache garbage collection https://github.com/nearprotocol/nearcore/issues/364
- cache public keys somewhere, need to invalidate this cache when public keys are swapped, deleted, etc. should we do this in `StateDbViewer`, or whatever is owning this? should we do this in `SignatureVerifier`?

**Comment by evgenykuzyakov** [comment]
@azban @nearmax  Is it still relevant after we switched to BLS?

**Comment by nearmax** [comment]
Yes, it is independent of BLS verification. We have standard ed signatures that we should make sure we are not re-verifying.

**Comment by ilblackdragon** [comment]
Actually interesting to see benchmark for this. ED sig verification should be really fast so caching it may be heavier toll.
We should consider caching account retrieval for TX verification prior to mem pool.

**Comment by evgenykuzyakov** [comment]
Probably not worth it now
