### ISSUE TITLE
Fiddle names have uppercase letters

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#412]
We shouldn't allow uppercase letters in the contract names, since contract names are account_id which are bound by the account_id regex policy.
There are 2 bugs:

- deploy contract should check that the account_id is valid
- Studio should not use uppercase letters for fiddle names

**Comment by vgrichina** [comment]
> deploy contract should check that the account_id is valid

Shouldn't this happen on `near core` side?

**Comment by evgenykuzyakov** [comment]
Yes, this should be on the nearcore side

**Comment by evgenykuzyakov** [comment]
But it's probably not happening, since we can deploy contract like "studio-4Xvd5BW"

**Comment by vgrichina** [comment]
https://github.com/nearprotocol/near-fiddle-api/commit/d5f3e65943944c7669cca60399557d22130c3c9d fixed at fiddle id generation side

**Comment by vgrichina** [comment]
updated prod as well

**Comment by evgenykuzyakov** [comment]
Thanks. I'll fix the nearcore part

**Comment by evgenykuzyakov** [comment]
I only need to fix view calls

**Comment by evgenykuzyakov** [comment]
Fixed view calls as well.
