### ISSUE TITLE
validate testing/devnet/testnet/mainnet specific cli flags

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#418]
we should have a way to indicate what flags affect what environments, throw errors when they are specified and unused, etc.

**Comment by azban** [comment]
https://github.com/nearprotocol/nearcore/pull/417#discussion_r248424276

**Comment by evgenykuzyakov** [comment]
@azban We split them into different files now, right?

**Comment by azban** [comment]
think so.. @nearmax knows more here now

**Comment by nearmax** [comment]
Currently the configuration can be specified either through flags or through files. Files configure only some things, e.g. they do not configure the network, rpc stuff, etc. I organized some of this code by separate it into config objects.

We have the following config objects:
* `ClientConfig`;
* `AuthorityConfig`;
* `ChainSpec`;
* `DevNetConfig`;
* `NetworkConfig`;
* `RPCConfig`;

`DevNet` config is used by DevNet only. `NetworkConfig` is used by TestNet only.

Ideally we would like all these configs to be assignable from the CLI or readable from a config file such that if some value is present both in CLI args and in the specified config file, CLI takes precedence. This would make it very useful for launching devnet/testnet manually, through kubernetes, or as integration tests (e.g. pynear integration tests). This issue also suggests that we should test that these configs work as intended.

Unfortunately, I did not have time to finish this work, and so there is still some disorganization. Specifically:
* some configs have duplicated or redundant flags. We specify boot nodes both in `ChainSpec` and `NetworkConfig`;
* Some values cannot be set from CLI. Most of the `ChainSpec` values can only be set through a file;
* Some configs are redundant. `AuthorityConfig` duplicates `ChainSpec`.
* Everything but `ChainSpec` cannot be set through a file, which is a pain for deploying this stuff on a cloud.

**Comment by ilblackdragon** [comment]
@nearmax cleaning up configs for BetaNet.

**Comment by ilblackdragon** [comment]
This should be cleaner now in Nightshade impl.
