### ISSUE TITLE
It's too easy to hit gas limit when returning arrays from contracts

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/nearcore#459]
It's too easy to hit gas limit when returning arrays from contracts

Compare https://studio.nearprotocol.com/?f=8u6y2w762 and https://studio.nearprotocol.com/?f=natqgjb1b getMap -- first implementation fails running into gas limit, while 2nd works. The only difference is the format of the output. 

It appears like MVC example hits the limit with about 20 todos.

**Comment by vgrichina** [comment]
Should be better after this fix:
https://github.com/nearprotocol/assemblyscript-json/commit/e564e7171cc63af24579ba31264c01d3cc2fb2b8

You'll need to update `decoder.ts` with latest version from here.

**Comment by ilblackdragon** [comment]
@janedegtiareva @vgrichina I'm assuming this is not a problem anymore, so closing.
