### ISSUE TITLE
remove TransactionBody enumeration in protobuf

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#462]
this was intended for easier bindings for system contract calls, but shouldn't be at the protobuf layer, as it should match the interface for all other transactions.  

the enumeration may be useful inside of runtime after system contract calls are parsed

**Comment by ilblackdragon** [comment]
End of de-prioritizing this, because first need to adjust runtime to treat everything as a function.
And later we can remove this enum.

**Comment by ilblackdragon** [comment]
Removed both protots and enumeration.
