### ISSUE TITLE
create contract shim for system contract

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#463]
until we can (if ever), move system contract calls into wasm and treat it like any other contract, we should strive to make the interface as similar as possible to other contracts. this means that we should do the similar kind of argument parsing, validation, error throwing, etc.

until we have a first pass at this, it's going to be faster to just creates protobufs for each system contract method, rather than trying to recreate arg parsing and validation in runtime, especially because runtime is currently being heavily worked on. once this is ready though, we should remove the enumeration and `TransactionBody` will just match the interface of the current `FunctionCallTransaction` (issue [here](https://github.com/nearprotocol/nearcore/issues/462))

**Comment by ilblackdragon** [comment]
@bowenwang1996 implemented system contract shim.
