### ISSUE TITLE
reconsider CryptoHash interfaces

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#471]
`From<Vec<u8>> for CryptoHash` is confusing because it silently truncates a longer vector.. the `hash` function is actually what i was looking for, but this isn't really clear

cc: @ilblackdragon , @bowenwang1996

**Comment by azban** [comment]
i think signature interface also needs a little polish.. froms and new on everything seems wonky and panics rather than returning results

**Comment by bowenwang1996** [comment]
What's the plan for this? Should we implement `TryFrom` instead?
