### ISSUE TITLE
create view layer on top of client

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#479]
we need to create a layer that is agnostic to interface (cli, rpc, ws, etc) that is used for computing and packaging data that is extracted from the system for various purposes.

the motivation behind this is to not tie view logic into a specific interface, while keeping it separate from domain logic that needs to be as concise as possible and more heavily tested.

**Comment by azban** [comment]
cc: @ilblackdragon  @nearmax

**Comment by azban** [comment]
relevant pr: https://github.com/nearprotocol/nearcore/pull/477

**Comment by evgenykuzyakov** [comment]
@azban Is it done?

**Comment by nearmax** [comment]
No, RPC is still accessing the internals of client, shardclient, etc.

**Comment by ilblackdragon** [comment]
Interface `query_client` was made for this. Also Nightshade has an extra actor `ViewClientActor` that provides view only operations.
