### ISSUE TITLE
ReceiptBlock

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#480]
Currently, Receipts are stored without attached source information.

We need to store receipts only in ReceiptBlock:
```
struct ReceiptBlock {
   header: SignedBlockHeader,
   merkle_path: Vec<CryptoHash>,
   receipts: Vec<Receipt>,
}
```

Thus can't be stored together with SignedTransaction.

**Comment by bowenwang1996** [comment]
Resolved in #514
