### ISSUE TITLE
Define Event format for log entries

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#488]
In Ethereum logs are used to store `Events` as well as regular logs.
We can just define a special format for events that can be distinguished from regular logs by frontend.

**Comment by vgrichina** [comment]
Why do we actually need Events? They seem redundant in case we persist results of method execution.

**Comment by evgenykuzyakov** [comment]
Can you subscribe to the Events? Or what's the point for events

**Comment by evgenykuzyakov** [comment]
Let's reopen this when we actually need it
