### ISSUE TITLE
Bring rustfmt back to pre-commit

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#49]
i don't know if we are always gonna line up with rustfmt rfc's and it would be good to have an option to define our own style but also get a formatting tool.

options:
- fork rustfmt
- use non-rust specific formatter that you can tune well

this issue will also be used for discussions about style preferences we have that don't align with our current configuration.

**Comment by ilblackdragon** [comment]
@azban we are ok with clippy / cargo fmt for now?

**Comment by evgenykuzyakov** [comment]
Seems clipply disabled on nightly. I'd prefer to get it back

**Comment by nearmax** [comment]
Last time I checked clippy did not compile on CI and because of the nightly switch.

**Comment by azban** [comment]
@bowenwang1996 fixed that in https://github.com/nearprotocol/nearcore/pull/675

i'm fine with clippy.. we still haven't converged on cargo fmt for linting, and i feel like it would be a good idea to have a strict linting tool to use at some point

**Comment by bowenwang1996** [comment]
I disabled clippy again due to its instability with nightly. On some days it work with nightly and when we are not lucky, it doesn't.

**Comment by nearmax** [comment]
@azban I am fine with rustfmt. Sometimes it derps, but it seems to be the widely accepted standard and we should be using at least something, so let's use it.

**Comment by ilblackdragon** [comment]
Closing this, as we have now CI check.
