### ISSUE TITLE
TryFrom for conversions that can fail

### ISSUE THREAD

**Issue by david-stolp** [nearprotocol/nearcore#502]
TryFrom is currently a nightly-only API, but will be useful in several places.  For now I've used From in some places that should really be TryFrom.

**Comment by azban** [comment]
relevant issue: https://github.com/nearprotocol/nearcore/issues/471

**Comment by ilblackdragon** [comment]
Just to bump this up:
`./target/debug/nearcore --addr 0.0.0.0:3001 --rpc_port 3031 --base-path=test2 --test-network-key-seed 2 --boot-nodes 127.0.0.1:3000/GuMriipt4yUXfkZL2z3zLPbYaozkZ` <-- hash is truncated but error is super unclear.
