### ISSUE TITLE
data client

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#520]
creating this issue to track discussion related to data that we want to expose that is not essential for write functionality.

although they are probably lofty optimizations at this point, i feel like it's good to track where we are compromising now.

cc: @ilblackdragon @nearmax 

examples:
- transaction address
- transaction + receipt tree

**Comment by ilblackdragon** [comment]
@azban what is the scope of this tracking?
We are exposing transaction addresses and there is a way to fetch the tree. Do you mean to directly expose tree in one API from the node?

**Comment by nearmax** [comment]
Yes, I think that's what he means.

**Comment by ilblackdragon** [comment]
Transaction tree is exposed right now. Although chunks will make it more complicated.
