### ISSUE TITLE
Partial view_state request

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#525]

**Comment by ilblackdragon** [comment]
How is this different from state view call?
Or what do you mean?

**Comment by evgenykuzyakov** [comment]
@vgrichina Is this what you mentioned in the chat? Be able to read data by a given contractName and a key without WASM.

**Comment by ilblackdragon** [comment]
@evgenykuzyakov so how is this different from view state RPC call?

**Comment by evgenykuzyakov** [comment]
It's like view_state request, but can be partial. E.g. use prefix for keys or a vector of keys

**Comment by evgenykuzyakov** [comment]
Already implemented using `contract/account_id` and `data` as a prefix
