### ISSUE TITLE
Sending money doesn't work

### ISSUE THREAD

**Issue by mfornet** [nearprotocol/nearcore#539]
Sending money from one account is not working. Following are steps to reproduce the issue.

Follow steps from [Running TestNet Locally](https://github.com/nearprotocol/nearcore#running-testnet-locally)

Remove the storage:

`rm -r test1 test2`

Launch the boot node:

`cargo run -- --addr 127.0.0.1:3000 --rpc_port 3030 --base-path=test1 --test-network-key-seed 1 --chain-spec-file ./node/configs/res/testnet_chain.json`

Launch the second node using the first one as the boot:

`cargo run -- -a bob.near --addr 127.0.0.1:3001 --rpc_port 3031 --base-path=test2 --test-network-key-seed 2 --chain-spec-file ./node/configs/res/testnet_chain.json --boot-nodes 127.0.0.1:3000/D5kxnrPGZFtGXEniPV76CURQod4t3YMy1Q6qpWQm9mCe`

---

Check alice account balance from boot_node.

`./scripts/rpc.py view_account -a alice.near -u http://127.0.0.1:3030/`

Expected output:

`{"account_id": "alice.near", "amount": 100, "stake": 100, "nonce": 0, "code_hash": "2Kkfab2QQ3GK7DSiuzcRF2H4vNSPKFfE9gkCDkPGumtV"}`

Make the transaction.  

`./scripts/rpc.py send_money -s alice.near -r bob.near -a 1 -k 22skMptHjFWNyuEWY22ftn2AbLPSYpmYwGJRGwpNHbTV`

Unspecified arguments for `send_money` are: 
+ `KEYSTORE_BINARY` Default: `None`
+ `KEYSTORE_PATH` Default: `keystore/`

Check alice account balance:

`./scripts/rpc.py view_account -a alice.near -u http://127.0.0.1:3030/`

The transaction never happened.

**Comment by nearmax** [comment]
Works for me.
Btw, you probably meant:
```sh
./scripts/rpc.py view_account -a alice.near -u http://127.0.0.1:3031/
```

**Comment by nearmax** [comment]
On a second look it seems like financial transactions do not decrease the balance of whoever sends it.

**Comment by bowenwang1996** [comment]
It works for me

**Comment by mfornet** [comment]
@bowenwang1996 It works for me now too. Maybe there was a problem in the setup, with storage/test*/keys, I don't know. 

@nearmax you can check if it works for you too and close this issue.
