### ISSUE TITLE
Refactor test-utils

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#550]
Currently test-utils are part of the crate, but they should only be compiled for tests.
See this for how to correct it: https://stackoverflow.com/questions/41700543/can-we-share-test-utilites-between-crates

**Comment by ilblackdragon** [comment]
A lot of test utils were moved out into separate crate. Also we still have test utils in some of the crates which should have a test feature on them (there is another issue to track that).
