### ISSUE TITLE
cargo + gitlab + cache build issues

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#560]
current gitlab configuration is causing fairly regular intermittent failures:
```
error[E0460]: found possibly newer version of crate `beacon` which `client` depends on
 --> /builds/nearprotocol/nearcore/node/devnet/src/lib.rs:9:5
  |
9 | use client::Client;
  |     ^^^^^^
  |
  = note: perhaps that crate needs to be recompiled?
  = note: the following crate versions were found:
```

it's sometimes other crates, but same error

ex: https://gitlab.com/nearprotocol/nearcore/-/jobs/160508079
 
current workaround is to log on to gitlab runners and clear cache dirs

cc: @ilblackdragon @bowenwang1996 @frol

**Comment by frol** [comment]
Well, it seems to be a bug in Rust: https://github.com/rust-lang/rust/issues/49979

I think the trigger is that some PRs may introduce newer dependencies and while the upgrade works fine, the other PR using the "old" set of cached dependencies gets into troubles.

**Comment by ilblackdragon** [comment]
Close for now as we didn't observed this in awhile.
