### ISSUE TITLE
Test nearlib and wallet integration

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/nearcore#573]
Need to use real browser, e.g. through https://github.com/GoogleChrome/puppeteer

**Comment by evgenykuzyakov** [comment]
@azban I think you are already working on this.

**Comment by azban** [comment]
this is done here.. i need to integrate this into CI tho. https://github.com/nearprotocol/integration/blob/master/integration/tests/integration/test_integration.py#L52

**Comment by ilblackdragon** [comment]
Issue moved to [nearprotocol/nearlib #26](https://github.com/nearprotocol/nearlib/issues/26) via [**ZenHub**](https://www.zenhub.com/)
