### ISSUE TITLE
MemPool for Payloads

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#576]
Payloads can be transactions, receipts, etc.

Pool must do next things:

* On insertion of tx -> be able fast query if the new transaction already in the accepted blocks (each pool is attached this way to a chain, and can use TransactionAddress there).
* On new block prune the tx (implemented)
* Produce payload (implemented)
* Be able to tell which tx are missing given some info (bloomfilter?) and query for them
* Be able to respond to such queries with tx.

Additional functionality which is important for stability:

* temporary ban transactions that are invalid - e.g. wrong signatures, missing account etc. As they going to be rejected from pool, but can keep being received. This also requires pruning this temporary things when time expires.
* order transactions on importing based on account_id / nonce to actually execute them in the order they meant to be. Grouping by account_id can also help us later to execute them in parallel.
* limit size of the pool to not eat all RAM.

Generally, https://github.com/paritytech/substrate/blob/master/core/transaction-pool/graph and https://github.com/paritytech/parity-ethereum/blob/d89b8d904ff28382d3692290a936706304627255/miner/src/pool/ is a good thing to look at for inspiration of functionality.

This part I'm less sure, but I think pool should be queried by consensus to request the current payload.
Then it's merkeliazed + attach the previous block and sent for consensus between active nodes.
There are few details here which we should figure out.

**Comment by ilblackdragon** [comment]
So the later diffing items between peers can be done via Invertible Bloom Lookup Tables.
 - https://people.cs.umass.edu/~pinar/ozisik.cbt.2017.pdf
 - https://medium.com/codechain/invertible-bloom-lookup-table-37600927cfbe

**Comment by dangerousfood** [comment]
> order transactions on importing based on account_id / nonce to actually execute them in the order they meant to be.
Is this seeking to order the transactions by nonce of the account? Or is it to order transactions based on their time  of arrival? If it is the later there is no way to order transactions based on their arrival time because it is a subjective observation.

**Comment by bowenwang1996** [comment]
By nonce of the account.

**Comment by ilblackdragon** [comment]
#649 address a few of the issues here.

TODos from there:
 - Store hashes of transactions in the snapshot
 - Send gossip to a subset of authorities
 - Make sure receipts are sent / tracked fully (for one shard this is not critical)
 - Unify `add_payload_with_author` vs `add_payload_snapshot` and generally computation of `known`.
 - Investigate gossiping of hashes with requesting ones that node doesn't know.

**Comment by ilblackdragon** [comment]
Most of the issues addressed in #768 .
For future issues, tracking #741
