### ISSUE TITLE
Asserts in AS should show the full stack trace

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#588]
Currently failures inside some other library/call shown like this:
```
[studio-3xdvym4w7_t1550600774114]: ABORT: "" filename: "~lib/string.ts" line: 525 col: 8
nearlib.js:349 [studio-3xdvym4w7_t1550600774114]: Runtime error: wasm async call execution failed with error: Wasmer(CallError(Runtime(User { msg: "Error: AssertFailed" })))
```

**Comment by vgrichina** [comment]
@ilblackdragon that's unlikely to be tractable without exception handling in WASM (hasn't landed yet), unless our wasm VM can provide this info on abort (then source mapping can be used to symbolize it).

@evgenykuzyakov does wasmer provide you any metadata on abort?

**Comment by evgenykuzyakov** [comment]
No, wasm doesn't even have original source. So it would be func 23, func 53, func 92. Not a simple task. While assembly script that creates this assert might actually be able to get the stack.
I don't think it's a priority right now, but we can ask AssemblyScript folks to look into this.

**Comment by vgrichina** [comment]
@evgenykuzyakov there is source map produced by assemblyscript, so having stuff like `func 23` actually can be fine.

**Comment by vgrichina** [comment]
@evgenykuzyakov similar thread in assemblyscript:
https://github.com/AssemblyScript/assemblyscript/issues/484

**Comment by ilblackdragon** [comment]
I'm going to close this as stale.
