### ISSUE TITLE
Off by one? Transaction nonce {} must be larger than sender nonce {}

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#596]
We might be off by one when computing nonce, here:
https://github.com/nearprotocol/nearcore/blob/1ee7faf4e86dc3c51ba8c749535f50ce2ff2920f/node/runtime/src/lib.rs#L246
As the result of the above check, the first ever transaction sent by an account is expected to start with 1, not 0. Is it off by one error?

**Comment by evgenykuzyakov** [comment]
The first TX should have nonce 1. Maybe the issue is with the tool that sends this TX

**Comment by nearmax** [comment]
What I mean, is that a transaction nonce starting with 1 looks like an off-by-one error. You are saying it is designed that way, correct?

**Comment by evgenykuzyakov** [comment]
Yes. I think so. At least according to this line:
https://github.com/nearprotocol/nearcore/blob/1ee7faf4e86dc3c51ba8c749535f50ce2ff2920f/node/runtime/src/lib.rs#L239

And later we use TX nonce and set it to account nonce.

**Comment by nearmax** [comment]
I see.
