### ISSUE TITLE
improve http healthcheck endpoint

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#602]
https://github.com/nearprotocol/nearcore/blob/0b2e2613a506a2fc848dd9e3cc60e6cd6464b7dd/node/http/src/server.rs#L327-L339 makes the assumption that if http + beacon chain is configured than the node is healthy. there are other services that could be waiting to come up or unhealthy

a better solution is to have whatever is starting the client set some state that http can access

relevant change: https://github.com/nearprotocol/nearcore/commit/1d9b28524918eb287d13c702985b2684bb7e9213

**Comment by ilblackdragon** [comment]
Good condition is the chain is synced up. We currently don't have a flag for that, but let's do it.
Additionally should return some chain information (chain spec or at least genesis block).

**Comment by ilblackdragon** [comment]
In nightshade `status` check reports: current network, sync status, last block time and height. All of it can be used to determine health status of the node.
