### ISSUE TITLE
Report errors from Nearlib

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#604]

**Comment by vgrichina** [comment]
It's better to use specialized tool like https://sentry.io/

**Comment by evgenykuzyakov** [comment]
Nice. Whatever is better, let's add it.

**Comment by ilblackdragon** [comment]
Issue moved to [nearprotocol/nearlib #25](https://github.com/nearprotocol/nearlib/issues/25) via [**ZenHub**](https://www.zenhub.com/)
