### ISSUE TITLE
Mark adversaries after state verification failures.

### ISSUE THREAD

**Issue by mfornet** [nearprotocol/nearcore#608]
After seeing a state verification failure an honest participant is sure that the sender needs to be an adversary since he signs the gossip containing such message. It is important to don't allow bad actors to spam honest actors in this way, because state verification is slow.

Proof about an actor behaving maliciously needs to be stored, so the entire gossip, with the signature and the invalid state must be stored as evidence.

**Comment by ilblackdragon** [comment]
Close this as prev consensus related.
