### ISSUE TITLE
gitlab: move away from parity's base image

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#610]
we have been using this out of convenience, but it has stuff we don't need, and we could speed up gitlab runs if we prebuilt stuff like this:
https://github.com/nearprotocol/nearcore/blob/ab83e28ac61fc976d905bc777034d130156c6cf5/.gitlab-ci.yml#L15-L22

**Comment by evgenykuzyakov** [comment]
We should also remove protobufs from CI

**Comment by ailisp** [comment]
#1267
