### ISSUE TITLE
Authority should be using disk storage

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#612]
DevNet has a very slow start when it launches on an existing storage. To reproduce:
- Unpack the storage: https://drive.google.com/open?id=1gCmFjQw_BbC02_Fiq1nDQctIjWOfb8jS
- Check out the commit from the mater: 0b2e2613a506a2fc848dd9e3cc60e6cd6464b7dd
- Observe that DevNet takes >>10mins to start.

### Root cause
What slows down DevNet is computation of the authority schedule and the fact that we use stake rollover. Specifically, in order to compute which authorities are participating in a block of epoch E we need to know all the blocks in epoch E-2 and the authorities of epoch E-2. In order to know authorities of blocks in epoch E-2 we need to know authorities of epoch E-4.

This long-range dependency happens because we allow the stake to rollover without re-staking. So if some authority staked themselves in epoch E-2X the only way to know whether this authority is participating in epoch E is to know all its participation in epochx E-2X, E-2X+2, ... . 

### Short-term solution
Currently there is no way to avoid computation of authorities for each block starting from genesis, even if the node joins the network on the block index far in the future. However, if we have a node (or Devnet) that was stopped and then restarted we can avoid recomputing authorities for all blocks starting from the genesis. This can be done by storing computed authorities in the storage, which is already allowed by current chain/storage architecture.

Specifically, the following code is where the slowness happens: https://github.com/nearprotocol/nearcore/blob/master/node/beacon/src/authority.rs#L111
It iterates over the headers starting from genesis and computes authorities for each of them. Instead we need to:
* Store `proposals`, `participation`, `thresholds`, and `accepted_authorities` in storage in addition to keeping these fields in `Authority`;
* `compute_accepted_authorities` and `process_block_header` would then check whether the information is already available in the storage before processing it;
* To operate with storage `Authority` would need to have a dependency on  `BeaconChainStorage`. And would need to have additional methods that store and retrieve `proposals`, `participation`, `thresholds`, and `accepted_authorities` from the corresponding columns in the storage https://github.com/nearprotocol/nearcore/blob/master/core/storage/src/storages/beacon.rs See for the reference how `ShardChainStorage` has special method to store and retrieve transaction addresses and transaction results: https://github.com/nearprotocol/nearcore/blob/master/core/storage/src/storages/shard.rs

### Long-term solution
Currently, `BeaconBlock` has not additional information compared to `BeaconBlockHeader`. Instead it should store the computed authorities for that block. ( `BeaconBlockHeader` only stares proposals, which is not enough because we need to know whether the stake was rolled over).

**Comment by ilblackdragon** [comment]
@bowenwang1996 is working on storing info every epoch in disk.
Also we should increase epoch time to way more (right now it's 1).

The @nearmax long term solution IMO does make sense - if you store in the block authorities that sign the block I'll just make a full fake block.
And if you have offset by one, its enough to compromise one block to compromise network forever.
There is a reason why this should be recomputed.

The real long term solution is zkSnark. If you add a snark that authorities computed correctly then we can download the snapshot of current authorities.

**Comment by nearmax** [comment]
> @bowenwang1996 is working on storing info every epoch in disk. Also we should increase epoch time to way more (right now it's 1).

What exactly is he working on? Is he going to augment Authority to use storage as discussed in the short-term plan?

**Comment by nearmax** [comment]
#671 adds necessary code to fix this but I do not think it fixes it yet. Authority constructor still iterates through all past headers and computes authorities which is what we wanted to avoid in this issue. https://github.com/nearprotocol/nearcore/pull/671/files#diff-79b1c9541902719c7c34ca5c107a30bcR110

**Comment by ilblackdragon** [comment]
@nearmax it only iterates if there is no cache. How are you planning to avoid this?

**Comment by ilblackdragon** [comment]
Was fixed and will be reimplemented for Nightshade in #963
