### ISSUE TITLE
Devnet doesn't use new receipts in the next block

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#637]
Now we have more logs and block explorer is working, so hopefully we can find out what's happening with our devent and why it doesn't add new receipts to the next block.
Example of a block that is affected: https://studio.nearprotocol.com/debugger/shard-block/151118
Gist of part of the logs that contains the issue (already happening): https://gist.github.com/evgenykuzyakov/0788678d9f4a66ea73d94f3890b14242

Commit that we running: afeda3ed0ffa8e0f3196183dfd2451644e640a04
Full LOGS: https://drive.google.com/open?id=1q-E1pcn0q2OMgJ4gxwHCVwP6tFBsgKjq
Full Storage: https://drive.google.com/open?id=1_5uF3U9mzAqUk7zEEmsDuaChBDsphYop

Seems the last block that has receipt transaction as an input is block 151075
The block 151076 has a new receipt, but the next block 151077 doesn't have the new receipt as an input.
Debugger links:
https://studio.nearprotocol.com/debugger/shard-block/151075
https://studio.nearprotocol.com/debugger/shard-block/151076
https://studio.nearprotocol.com/debugger/shard-block/151077

@nearmax @ilblackdragon @azban Any ideas why it happens?

**Comment by nearmax** [comment]
Is it a recent breakage? Because it used to work before, correct?

**Comment by nearmax** [comment]
Okay, I think our transition to mempool was premature. I am looking at the mempool code and it is quite racy.
For instance here: https://github.com/nearprotocol/nearcore/blob/master/core/mempool/src/lib.rs#L44
You can see how we locking twice in `add_transaction`. During the first unlock we create state update object, during the second one we add it to the transactions list. If in between these lines the blockchain progresses to a new block (with a new state) then I do not know what will happen after we apply the outdated transaction state.

**Comment by ilblackdragon** [comment]
Isn't the commit @evgenykuzyakov mentioned is before Mempool switch #628?

**Comment by nearmax** [comment]
Correct, my bad. I created a separate issue here: https://github.com/nearprotocol/nearcore/issues/638

**Comment by ilblackdragon** [comment]
@evgenykuzyakov You will need to upgrade to new version (e.g. #629) and tell us if you see this issue again. Pretty much everything in devnet was re-plumbed with MemPool / new passthrough consesus.

**Comment by evgenykuzyakov** [comment]
Sounds good. I'll think a little how we can migrate state from the current chain to the new genesis. It would be helpful to have a migration tool available for future upgrades as well.

**Comment by evgenykuzyakov** [comment]
Seems the storage is still compatible with the master, so I'll push the latest code to prod devnet

**Comment by evgenykuzyakov** [comment]
Restarted the devnet in prod with the new mempool. We'll monitor if over the weekend and see if there is any issues remaining.

**Comment by nearmax** [comment]
This should be fixing it for good: https://github.com/nearprotocol/nearcore/pull/650

**Comment by nearmax** [comment]
I am closing this issue. Please reopen if it reoccurs.
