### ISSUE TITLE
CI fails to build

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#66]
Looks like some linker or cargo issue

https://gitlab.com/nearprotocol/nearcore/-/jobs/125040565

**Comment by nearmax** [comment]
https://gitlab.com/nearprotocol/nearcore/-/jobs/131207827

**Comment by nearmax** [comment]
This happened again.

**Comment by azban** [comment]
i think the temp solution is to clear the cache on gitlab
