### ISSUE TITLE
Cannot submit transactions through pynear. Crypto is broken.

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#661]
To reproduce:
Follow the instructions to start 4 nodes of alpanet net, see: https://github.com/nearprotocol/nearcore/pull/658

Upon submitting the transaction the following error occurs:

> Traceback (most recent call last):
>   File "/usr/local/bin/pynear", line 11, in <module>
>     load_entry_point('near.pynear', 'console_scripts', 'pynear')()
>   File "/Users/zaver/Projects/nearcore/pynear/src/near/pynear/cli.py", line 295, in run
>     MultiCommandParser()
>   File "/Users/zaver/Projects/nearcore/pynear/src/near/pynear/cli.py", line 53, in __init__
>     response = getattr(self, args.command)()                                                                                                                                   File "/Users/zaver/Projects/nearcore/pynear/src/near/pynear/cli.py", line 142, in send_money
>     return client.send_money(args.originator, args.receiver, args.amount)
>   File "/Users/zaver/Projects/nearcore/pynear/src/near/pynear/lib.py", line 134, in send_money
>     signature = self._sign_transaction_body(send_money)
>   File "/Users/zaver/Projects/nearcore/pynear/src/near/pynear/lib.py", line 91, in _sign_transaction_body
>     return self.keystore.sign(data, self._public_key)
>   File "/Users/zaver/Projects/nearcore/pynear/src/near/pynear/key_store.py", line 116, in sign
>     secret_key = ed25519.Ed25519PrivateKey.from_private_bytes(secret_key)
>   File "/usr/local/lib/python2.7/site-packages/cryptography/hazmat/primitives/asymmetric/ed25519.py", line 66, in from_private_bytes
>     return backend.ed25519_load_private_bytes(data)
>   File "/usr/local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 2228, in ed25519_load_private_bytes
>     raise ValueError("An Ed25519 private key is 32 bytes long")
> ValueError: An Ed25519 private key is 32 bytes long

**Comment by nearmax** [comment]
New error message:
```
Traceback (most recent call last):
  File "/usr/local/bin/pynear", line 11, in <module>
    load_entry_point('near.pynear', 'console_scripts', 'pynear')()
  File "/Users/zaver/Projects/nearcore/pynear/src/near/pynear/cli.py", line 295, in run
    MultiCommandParser()
  File "/Users/zaver/Projects/nearcore/pynear/src/near/pynear/cli.py", line 53, in __init__
    response = getattr(self, args.command)()
  File "/Users/zaver/Projects/nearcore/pynear/src/near/pynear/cli.py", line 141, in send_money
    client = self._get_rpc_client(args)
  File "/Users/zaver/Projects/nearcore/pynear/src/near/pynear/cli.py", line 109, in _get_rpc_client
    keystore = FileKeyStore()
TypeError: __init__() takes exactly 2 arguments (1 given)
```

**Comment by azban** [comment]
https://github.com/nearprotocol/nearcore/pull/664

**Comment by ilblackdragon** [comment]
Should this be closed now?

**Comment by ilblackdragon** [comment]
@nearmax is this fixed now?

**Comment by nearmax** [comment]
The hotfix was applied. This should not be closed until we have a fix.

**Comment by azban** [comment]
closing this in favor of https://github.com/nearprotocol/nearcore/issues/618 .. reopened the proper fix
