### ISSUE TITLE
Remove tx from mempool only after block is accepted.

### ISSUE THREAD

**Issue by mfornet** [nearprotocol/nearcore#667]
[Quote](https://github.com/nearprotocol/nearcore/pull/649#issuecomment-468931137) from @ilblackdragon at #649 
> We need to change snapshots to be just hashes of tx/receipts. Right now they actually removing tx, which prevents them from gossiped / and when another snapshot is accepted - must not remove the tx that didn't end up there.

**Comment by nearmax** [comment]
Duplicate? https://github.com/nearprotocol/nearcore/issues/660

**Comment by mfornet** [comment]
Yes
