### ISSUE TITLE
Support ":" for account_id. Enables trusted account names.

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#686]
`:` will be a special symbol in account_id. You can only create a new account with a colon symbol by having your `account_id` + `:` + `new_account_suffix`. 

**So why do we need this?**
The reason is to have verifiable accounts. Let's say we (NEAR) want to have trusted accounts by email. So we would create `email` contract at genesis with embedded authorities in the contract code that sets NEAR foundation/NEAR devs as a trusted oracle. Then we would create accounts on demand when you confirm them by email. It's centralized, but once you have an account, you can also have some way to recover them by email (if you keep the original code on the account or maybe some 2nd key).

Same applies to other account types:

- phone numbers
- github
- twitter
- facebook
- other chains: ether, bitcoin, etc. We would need to increase the total character limit on the account to support BTC and ether. We can do bridges with this as well.

The cool part is that we don't keep this functionality for NEAR only. Other users can start provide similar functionality if they want to. E.g. if `google` claims the account_id, they can start providing accounts like "google:larry", there also can be 2nd level names, e.g. "google:larry:sundar".

It would also help companies to have trusted accounts, e.g. "parity" would only create accounts like "parity:gavin" and you would know that it's Gavin from "parity".

We may also lock brands at genesis (like cocacola, google, etc.). We should discuss this.

**Comment by vgrichina** [comment]
I think we should avoid using colon, cause then we cannot use regular URL infra.
What I mean is that we should be able to handle `near:your.address` URLs on mobile, etc if we have colon as part of address it will have to be encoded.

Note that I only voice concern regarding use of `:` specifically, I agree that we need something like this. We just need to make sure we fit well into existing URL infra. This means it might be better to use `/`. So you have `near:email/gmail@chucknorris.com`

**Comment by evgenykuzyakov** [comment]
I guess `/` is better yes.

**Comment by evgenykuzyakov** [comment]
Actually `/` is also bad since we can't properly use account_id in urls then :) Colons should be fine if you escape them.

**Comment by evgenykuzyakov** [comment]
BTW, we should also support `domain:`

**Comment by ilblackdragon** [comment]
Why not just use `.domain` as it was originally?
There is a top level registerer contract, which is managed by the board and includes new top level registrers.
E.g. we register `.near` accounts. Google can apply to register accounts with `.google`.
For ETH it's `0xblah.eth`, but BTC it's `0xblah.btc`.
And email just kept as `someemail@gmail.com` as it has a separate confirmation process. Or it can also have `.email` suffix.

**Comment by ilblackdragon** [comment]
I'm assuming we are not doing this as it's not in the Account Name Service NEP :)
