### ISSUE TITLE
Beacon chain

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#7]
For MVB we use beacon chain to keep state:
 - [x] Implement blockchain tracking (storing into DB blocks and headers)
 - [x] Block production
 - [x] Block validation
 - [x] Network catch up
 - [x] Witness staking, selection and accounting for block production

**Comment by nearmax** [comment]
Network catch up is currently missing.

**Comment by ilblackdragon** [comment]
@bowenwang1996 says we have catchup. If we need more specific catch up mechanics let's file separate issue.
