### ISSUE TITLE
Nightshade should be using weighted seats oppose to a single seat per shard

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#712]
Currently, if a participant has more than one seat in a shard they still create only one Nightshade per shard that acts as one seat that has exactly the same voting power as any other participant in this shard. We, however, need to weight the voting power with respect to how many seats this participant has in a shard.

In addition to changes in the infrastructure, it requires redoing the formal proof of Nightshade.

**Comment by ilblackdragon** [comment]
Closing as related to prev consensus.
