### ISSUE TITLE
invalid connection does not close

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#714]
when testing, i found that the network hangs on an unexpected request. the connection should be closed with some kind of error. 

here is a relevant log:
```
Mar 13 03:01:25 ip-172-31-46-22 alphanet[19835]: [2019-03-13T03:01:25Z WARN  network::peer] Error receiving data from incoming connection unknown variant `ET / HT`, expected one of `Handshake`, `InfoGossip`, `Mes..
```

cc: @nearmax

**Comment by nearmax** [comment]
Should've been solved by moving to proto encoding over network.
