### ISSUE TITLE
Update README.md and doc repo according to the recent protos change

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#738]
The following command is required on some systems to be able to build the project:
```
sudo apt-get install -y unzip && wget -O /tmp/protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip && sudo unzip /tmp/protoc.zip -d protoc && sudo mv protoc/bin/* /usr/local/bin/ && sudo  mv protoc/include/* /usr/local/include/ &&  sudo chmod 755 /usr/local/bin/protoc && sudo chmod 755 /usr/local/include/google
```

Also cargo run now needs sudo.
We should investigate whether we can drop sudo. We should also update https://github.com/nearprotocol/nearcore/blob/master/README.md and https://docs.nearprotocol.com/quick_start/expert

**Comment by nearmax** [comment]
At the moment I am solving it by opening access like this:
```
sudo chmod -R 755 /usr/local/include/
```
but the permissions should've been set correctly in the first place.

**Comment by azban** [comment]
also, https://github.com/nearprotocol/integration/blob/master/salt/srv/salt/devnet/source.sls#L17 needs to be updated

**Comment by azban** [comment]
is there a ppa that has a newer version of `protobuf-compiler`?
