### ISSUE TITLE
Bugs and issues in Mempool 

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#741]
Bugs:
1. `Pool::add_transaction` does not check whether the transaction is already known and erases all knowledge of whom this transaction is known to when it is re-added https://github.com/nearprotocol/nearcore/blob/e46a7c36d275ec77d552e345bb1ee30cfeb1dfac/core/mempool/src/lib.rs#L119 This in combination with how payload gossip is implemented will cause transactions to bounce between peers (even if they already know them) until the block is produced.

Incorrect assumptions:
1. `Pool::known_to` is updated when the payload is gossiped, but if payload never arrives due to network issues we would incorrectly assume that peer has that transaction. Payload gossip depends on this assumption;
2. `Pool::add_transaction` will reject transaction if the account from which it is send is created in the same block;

Dead code:
1. `Pool::ready_snapshots` on a first glance looks like it is used, but it is filled and immediately drained within the same function `process_payload_response`. Could've just used a temporary variable. See: https://github.com/nearprotocol/nearcore/blob/8b370c01b096978fac20a4a3cf264cfc2b97074c/node/coroutines/src/client_task.rs#L394 
2. `PayloadResponse::General` is never constructed, but there is code to process receiving it. Therefore `Pool::add_payload` is also unused;
3. `PayloadRequest::General` is never constructed, but there is code to process receiving it;
4. `Pool::pending_snapshots` is populated but never used;

Race conditions:
1. If peer A receives a snapshot request from peer B, but the corresponding block was just popped due to block production then A will mark B as potentially malicious.
see: https://github.com/nearprotocol/nearcore/blob/fc9b9228564d66b0584a83a605b2b25595cba52f/node/network/src/protocol.rs#L105

**Comment by bowenwang1996** [comment]
> `Pool::add_transaction` will reject transaction if the account from which it is send is created in the same block

I think this is expected behavior. You cannot transact using an account that does not exist yet.
