### ISSUE TITLE
Allow freshly started authorities to participate in second round BLS

### ISSUE THREAD

**Issue by mikhailOK** [nearprotocol/nearcore#747]
test_4_20_kill2 found the following failure scenario:
- Run 4 nodes, they produce blocks
- Kill 2 nodes after nightshade agreed on transactions but before they signed the second BLS for state transition
- Restart those nodes, they will not join the signing and blocks will stall

Freshly started authorities should join the 2nd round even if they missed the first.

**Comment by ilblackdragon** [comment]
Closing as related to prev consensus.
