### ISSUE TITLE
Storage migration process & testing

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#750]
We need process when we change storage:
 - We should have a previous version of storage in our repo and integration test that checks that we can load it.
 - Versioning for storage format.
 - When we change storage format, write an importer of the previous version.
 - Probably the way to do the migration for complex cases is to have dump to json / load from json tool.

**Comment by evgenykuzyakov** [comment]
@ilblackdragon What's left from this issue?

**Comment by ilblackdragon** [comment]
We have mechanics to update old storages for hard forks.
Going forward we will have backward compatibility requirement enforced by CI (#1573)
