### ISSUE TITLE
Take ownership of `Message` in `encode_message`?

### ISSUE THREAD

**Issue by mfornet** [nearprotocol/nearcore#792]
Right now to encode message we are taking ownership of the message from PR #744 ([`fn encode_messsage`](https://github.com/nearprotocol/nearcore/pull/744/files#diff-5d0e61692c4e61fedace8a659453c173R303)).

This is a problem for #735 (Network Proxy) since messages can be duplicated (because of some handler), and hence, several copies of the same message can be sent through the network. There are two solutions:
1. Cloning the entire `Message` before sending it.
2. Encode message without taking ownership.

I think option 2 is the way to go. It makes sense not taking ownership of the message to encode it and it is more efficient encoding the message without cloning before.

**Comment by nearmax** [comment]
Since the only situation where we clone message is when we duplicate it with the proxy it is okay to do it, because it is only going to happen in a testing environment.

**Comment by mfornet** [comment]
@nearmax But messages traveling through the proxy are behind an `Arc`, so in order to encode it, I will have to clone it, since I can't take ownership of value inside an `Arc`. This means that we will need to clone **all** messages before encoding, on every case, being a duplicate or not.

**Comment by mfornet** [comment]
Closing in favor of #794
