### ISSUE TITLE
Let NetworkConfig accept proxy handler arguments.

### ISSUE THREAD

**Issue by mfornet** [nearprotocol/nearcore#795]
- [ ] Populate `ProxyHandlerType` with all proxy_handler we want to have builtin. [`ProxyHandlerType`](https://github.com/nearprotocol/nearcore/pull/735/files#diff-f867e369a7e940d58e0993e41478fa46R152)
- [ ] `get_handler_type` is a map-like function that build `ProxyHandlerType` (with fixed parameters) from identifier (string). [`get_handler_type`](https://github.com/nearprotocol/nearcore/pull/735/files#diff-f867e369a7e940d58e0993e41478fa46R158)
- [ ] Parse config to accept proxy handlers. (This haven't been tested) [Implementation](https://github.com/nearprotocol/nearcore/pull/735/files#diff-f867e369a7e940d58e0993e41478fa46R79)
- [ ] Pass proper arguments to [`NetworkConfig` constructor](https://github.com/nearprotocol/nearcore/pull/735/files#diff-f867e369a7e940d58e0993e41478fa46R140)
- [ ] Build proxy_handlers properly from network configs. [Here](https://github.com/nearprotocol/nearcore/pull/735/files#diff-2d7700c294860638b86d74e3aaa9b5a8R413)

**Comment by ilblackdragon** [comment]
Outdated.
