### ISSUE TITLE
CI runners compete for resources which causes tests to timeout

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#801]
There is an anecdotal evidence from @evgenykuzyakov , @bowenwang1996 , @mfornet and and me that when we have multiple CI runners running tests at the same time some of our heavy integration tests starts failing significantly more frequently, like every other time. These integration tests, specifically https://github.com/nearprotocol/nearcore/blob/d9e1a85367b2751e5c8800cb77eceacc4eb5a9e3/tests/test_alphanet.rs#L49, fail because they have general timeouts that limit the execution time.

We should investigate how to make CI runners to not interfere.

**Comment by azban** [comment]
can we extend the timeouts for now? i have a bunch of other stuff on my plate and have 0 knowledge about our gitlab setup, and would rather avoid random test failures on CI asap.

**Comment by nearmax** [comment]
Please review: https://github.com/nearprotocol/nearcore/pull/800

**Comment by ilblackdragon** [comment]
Closing this one as we haven't observed this issue.
