### ISSUE TITLE
Remove system account

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#812]
@bowenwang1996 says it is not used anymore.

**Comment by bowenwang1996** [comment]
Where is it used?

**Comment by nearmax** [comment]
https://github.com/nearprotocol/nearcore/blob/3efbaaa03093531e372fce4905fa024de7ac13aa/node/runtime/src/test_utils.rs#L42

https://github.com/nearprotocol/nearcore/blob/f274630ce64461452528dfb2088540f0714989ef/node/runtime/src/system.rs#L21-L20

https://github.com/nearprotocol/nearcore/blob/64835fe432d476581212f277f685982fc9cd2a02/node/runtime/src/lib.rs#L572

**Comment by bowenwang1996** [comment]
I was wrong. It is still used.

**Comment by nearmax** [comment]
I just commented out the line from the first link and all tests are still passing.

Also, what is the meaning of the "system" account?

**Comment by bowenwang1996** [comment]
System does not need to sign anything, so commenting that line out is fine. It is used for refunding/returning stakes.

**Comment by nearmax** [comment]
What is the meaning of the "system" account, though?

**Comment by bowenwang1996** [comment]
When you try to create an account with money but fails, the money gets refunded but there needs to be a sender. It can be thought of as the runtime itself.

**Comment by nearmax** [comment]
So account X is trying to create account Y and fails. Should we refund money back to X? Why do we refund it to "system"?

**Comment by bowenwang1996** [comment]
It goes to X, but the receipt has to have an originator.
