### ISSUE TITLE
Mempool: tx_nonce issue

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#814]
When mempool orders transactions, does it removes old? The issue I'm seeing is when alice tries to make a new transaction with the same nonce, the 2nd one doesn't get into blocks
To reproduce, run a devnet and call something like:
```
pynear create_account GGU3YKMF3Mz6vLWc9ki2UrxvrMGBr6VYvWewQK62z6Q4 1
```
twice in a row.
With delay of 5 seconds
The first TX is going to fail and block is produced, but alice's nonce is not updated. The 2nd tx doesn't get into a block and no new blocks produced.

Seems the issue is with the guard `tx_nonce(...)` that prevents the 2nd transaction to be added to the pool, since it has the same nonce.

We either have to update nonce on alice account even if the transaction has failed, or tx_nonce should only guard after the transaction succeeded.

**Comment by nearmax** [comment]
What is `tx_nonce` guard?

**Comment by evgenykuzyakov** [comment]
It's used here: https://github.com/nearprotocol/nearcore/blob/b57d4a56e523df3b728ca766cfffde5b285771d5/core/mempool/src/lib.rs#L114

**Comment by evgenykuzyakov** [comment]
The issue is related to nonce not being updated to failed transactions.
