### ISSUE TITLE
ETHash API in WASM runtime

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#832]
Implement a `check_ethash(mining_hash, nonce, difficulty, mix_hash) -> bool` API that is surfaced in the WASM.

Find ethash rust cargo (https://docs.rs/ethash/0.3.1/ethash/), and use it.
Calculate cache once and use it across any calls.

Acceptance criteria:
 - Unit tests for runtime.
 - Rust smart contract test.
 - Integration test, that adds a function in the `tests/hello/main.ts` that receives Ethereum header and is able to verify it's validity and a test that calls it.

General procedure:
```
def check_pow(block_number: int,
              mining_hash: Hash32,
              mix_hash: Hash32,
              nonce: bytes,
              difficulty: int) -> None:
    validate_length(mix_hash, 32, title="Mix Hash")
    validate_length(mining_hash, 32, title="Mining Hash")
    validate_length(nonce, 8, title="POW Nonce")
    cache = get_cache(block_number)
    mining_output = hashimoto_light(
        block_number, cache, mining_hash, big_endian_to_int(nonce))
    if mining_output[b'mix digest'] != mix_hash:
        raise ValidationError("mix hash mismatch; {0} != {1}".format(
            encode_hex(mining_output[b'mix digest']), encode_hex(mix_hash)))
    result = big_endian_to_int(mining_output[b'result'])
    validate_lte(result, 2**256 // difficulty, title="POW Difficulty")
```

Reference
---
 - https://github.com/ethereum/wiki/wiki/Ethash

**Comment by evgenykuzyakov** [comment]
Can it be implemented entirely in WASM?

**Comment by vgrichina** [comment]
@evgenykuzyakov I think crypto ideally should be outside of WASM cause it benefits from SIMD (unless we somehow provide safe SIMD in WASM).

**Comment by evgenykuzyakov** [comment]
Outside of WASM requires us to correctly account for gas. Inside WASM we can benefit from this being done automatically. Plus there are less security issues if it's part of WASM.

**Comment by ilblackdragon** [comment]
@evgenykuzyakov main constraint is computation of relatively large cache (25MB) that ideally should just persist between invocations.
