### ISSUE TITLE
Use `Box<std::error::Error>` instead of `String` wherever makes sense

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#846]

**Comment by evgenykuzyakov** [comment]
Is this just for better readability?

**Comment by nearmax** [comment]
For better compatibility `Box<std::error::Error>` is a trait object `String` is an object, which means wherever there is some function that returns String as error but invokes internally a function that returns std::io::Error (or some other specific error type) the casting or conversion is required. It basically replaces static-dispatch with dynamic dispatch, which is slower, but it only matters when the error occurs.

**Comment by ilblackdragon** [comment]
Mostly done.
