### ISSUE TITLE
`LocalNodeConfig` cleanup

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#847]
`LocalNodeConfig` has some fields that are only used by thread node or only by process node. `peer_id_seed` should not be passed there and instead we should allow passing peer id through the command line.
`proxy_handlers` only make sense for thread node.

**Comment by bowenwang1996** [comment]
I made those fields optional.

**Comment by nearmax** [comment]
`peer_id_seed` is still redundant, because this information should be passed through `NetworkConfig`.
I will get rid of `LocalNodeConfig` because thread and process node have different configurations, specifically process node does not use `proxy_handlers`.

**Comment by bowenwang1996** [comment]
Sure. I hope I'll still be able to merge :(

**Comment by nearmax** [comment]
I'll wait for you then.

**Comment by bowenwang1996** [comment]
Well it will take me at least one more day. So go ahead.

**Comment by ilblackdragon** [comment]
Seems outdated.
