### ISSUE TITLE
[pynear] Doesn't work with server url without http

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#856]
For example `pynear view_latest_beacon_block -u 35.236.60.217:3030` returns error, but 
`pynear view_latest_beacon_block -u http://35.236.60.217:3030/` works

**Comment by nearmax** [comment]
The following will not work either:
`pynear view_latest_beacon_block -u http://35.236.60.217:3030`

**Comment by ilblackdragon** [comment]
Moving pynear to separate repo
