### ISSUE TITLE
TestNet crashes under load

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#873]
To reproduce:
1. Modify `ops/deploy_alphanet.sh` so that `PREFIX` is different, e.g.:
```bash
PREFIX=${2:-test<datetime>}
```
2. Run `ops/deploy_alphanet.sh`.
3. Wait for nodes to launch (there is no need to wait for studio though);
4. Write down the list of the external IP addresses of the nodes either from the output of the command line or from gcloud;
5. Run the commands to generate keys:
```bash
cargo run --package keystore --bin keystore keygen --test-seed near.0 -p /tmp/keys/
cargo run --package keystore --bin keystore keygen --test-seed near.1 -p /tmp/keys/
cargo run --package keystore --bin keystore keygen --test-seed near.2 -p /tmp/keys/
cargo run --package keystore --bin keystore keygen --test-seed near.3 -p /tmp/keys/
```
6. Launch load tester, e.g.:
```bash
cargo run --package loadtester --bin loadtester \
-- --key-files-path /tmp/keys 
--addresses 35.236.2.108:3030 35.236.51.32:3030 35.236.42.85:3030 35.236.71.129:3030 \
--public-keys 82M8LNM7AzJHhHKn6hymVW1jBzSwFukHp1dycVcU7MD CTVkQMjLyr4QzoXrTDVzfCUp95sCJPwLJZ34JTiekxMV EJ1DMa6s2ngC5GtZb3Z2DZzat2xFZ34j15VLY37dcdXX 3DToePHssYc75SsxZgzgVLwXE8XQXKjdpdL7CT7D34UE 
--account-ids near.0 near.1 near.2 near.3 
```
where IP addresses are replaced by the ip addresses of node 0, node 1, node 2, node 3 (order is important).
7. Observe that the loadtester outputs TPS and blocks are created. Observe that after several seconds no new blocks are created;
8. Go to Gcloud console. SSH to any node;
9. Get docker id by running inside the node:
```bash
sudo docker ps
```
(ignore id that does not correspond to the node)
10. Connect to the node:
```bash
sudo docker exec -ti <id>
```
11. Read `output.log`:
```bash
vim /output.log
```
Observe that the node stopped at the following warn message:
```
WARN  coroutines::client_task] Fail to add missing payload: Some transaction is missing from the response
```

**Comment by evgenykuzyakov** [comment]
@bowenwang1996 It's super stable, right?

**Comment by nearmax** [comment]
@ailisp to verify whether this still happens.

**Comment by ailisp** [comment]
@nearmax There isn't a deploy_alphanet.sh here or in near-ops, means an updated ops/start_testnet.sh?

**Comment by nearmax** [comment]
What I mean is that the results of your loadtesting will show whether testnet still crashes under load.

**Comment by ilblackdragon** [comment]
Closing as stale.
