### ISSUE TITLE
Full JSONRPC implementation

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#880]
A clean-up of #869 
I suggest we reuse the following code, that implements JSON RPC standard already:
My modifications:
https://github.com/nearmax/tokio-jsonrpc/blob/master/src/message.rs
Original repo, the author is a major Rust contributor:
https://github.com/vorner/tokio-jsonrpc/blob/master/src/message.rs

It has the following benefits:

* It implements full JSON RPC standard, including Batch and Notification;
* It takes care of parsing errors in a nice way. Notice, how it is uses expressiveness of serde to handle different types of errors here: https://github.com/vorner/tokio-jsonrpc/blob/master/src/message.rs#L308 It can differentiate, invalid JSON, invalid JSONRPC 2.0 format, and invalid params (see below);
* It allows typed function calls, see example: https://github.com/vorner/tokio-jsonrpc/blob/master/examples/time_server.rs#L83
We can either import the crate our carve out the `message.rs` and `jsonrpc_params!` macro.

**Comment by ilblackdragon** [comment]
Closing this, as current #928 implements proper JSON RPC (took the messages.rs file from that module).
