### ISSUE TITLE
better differentiation of TransactionBody

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#93]
right now, we do some pretty arbitrary branching logic when [we apply a transaction](https://github.com/nearprotocol/nearcore/blob/master/node/runtime/src/lib.rs#L146). is there a better way to represent transactions so that we can represent them as different types throughout the code base in order to make it easier to reason about what is going on?

@ilblackdragon @bowenwang1996

**Comment by ilblackdragon** [comment]
@azban what I really want is that sending money is just a function call on the account smart contract. But there were some concerns from @evgenykuzyakov around cross-shard so we need first to figure that out.

**Comment by azban** [comment]
ok we still have issues around deploying then

**Comment by azban** [comment]
discussed with @nearmax .. going to try to use enums for this.

**Comment by azban** [comment]
he mentioned as a further optimization we could use dynamic structs
