### ISSUE TITLE
Return more helpful error message for error code -32603

### ISSUE THREAD

**Issue by janedegtiareva** [nearprotocol/nearcore#949]
-32603
data: "Tx (EA4D0CD7D5BD7C507E0D8F18B4ECAE32A1564C452B02A342B396393240603497) not found"
message: "Internal error"

**Comment by bowenwang1996** [comment]
This is the error message returned by tendermint core and we cannot control it. You can see more helpful error messages from nearcore if you use the debug log level.

**Comment by ilblackdragon** [comment]
Also would be helpful to know what is the input.
For now closing as we going to switch to 2.0 instead of fixing tendermint errors.
