### ISSUE TITLE
getTransactionStatus ('tx' TPC) doesn't return proper status on error

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/nearcore#956]
This has consequence of every failing smart contract call looping waiting for completion until it times out.

See an example below

`code: 2` means `'Started'` status on nearlib side. `code: 1` is expected for failures.

```
{ hash:
   'ECB188A06F2D10BEC4563141BF084A043C34AF9E1806350821D253C0C725DCBB',
  height: '2646',
  index: 0,
  tx_result:
   { code: 2,
     log:
      'Runtime error: Account alice.near tries to create new account with 1000000000, but only has 0' },
  tx:
   'CkAAgNhKWN+1QO6o0pXbztAOLi+8nXFmSk0qPzVYamGhFjCe9r242ApBosZx/sfaFchIt0YsixHfKueBcQWy+3EAEj8IHRIKYWxpY2UubmVhchoHYmF6aW5nYSCAlOvcAyogRkc0j5L8VFQeN4SywByOxVQ19BzTgI0pPu2dYbp3Ie5SIgogD1al8CjfwInsfDnBGDsyG02Pibpb7J4XYoA8wkkfbvg=' }
```

**Comment by nearmax** [comment]
On nearcore side `2` is also used for `Started`, see: https://github.com/nearprotocol/nearcore/blob/fa72ab10df22e9acb5f9516c52edb2d8e49d1b97/runtime/primitives/src/transaction.rs#L906

That's some nearcore bug.
