### ISSUE TITLE
CI too slow

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#96]
We shouldn't wait 20 minutes for CI to finish. It seems that the cache is not working properly.

**Comment by azban** [comment]
@bowenwang1996 do you want to try disabling the cache via .gitlab-ci.yml and pushing up a branch and seeing what the improvements are?

**Comment by ilblackdragon** [comment]
Step 1. Spun up our own Kubernetes with ok machines.
31m -> 24m30s
