### ISSUE TITLE
Economics unit tests

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#972]
Unit tests to check that balances are correctly deducted for both accounts and access keys for various operations that require fees.

**Comment by ilblackdragon** [comment]
@nearmax @evgenykuzyakov this is done, right?

**Comment by nearmax** [comment]
I think we have a decent coverage now, especially with https://github.com/nearprotocol/nearcore/blob/master/runtime/runtime/src/balance_checker.rs 

The get the ultimate coverage we need to implement https://github.com/nearprotocol/nearcore/issues/1293 
I am closing this issue in favor of the one above.
