### ISSUE TITLE
Add ECDSA curve

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#979]
Support for ECDSA curves for AccessKeys is required to maintain good linking with ETH ecosystem.
Requires:
 - [x] add well supported ECDSA library (e.g. that Parity uses)
 - [x] expand our crypto wrappers to support different asymmetric curves ( in  core/primitives/src/crypto/signature.rs)
 - [x] add support for `Signer` trait and signature verification
 - [x] add test to `standard_test_cases.rs` that adds ECDSA access key to the account and sends Tx signs with it.

**Comment by vgrichina** [comment]
It likely also makes sense to support Apple's flavor of signatures:
https://github.com/agens-no/EllipticCurveKeyPair#verifying-a-signature

This will basically allow iPhone to serve as hardware wallet.

**Comment by vgrichina** [comment]
See also https://blog.enuma.io/update/2016/11/01/a-tale-of-two-curves-hardware-signing-for-ethereum.html

**Comment by ilblackdragon** [comment]
So Apple uses `NIST P-256`, which is refered to as secp256r1 and prime256v1.
So very similar to Ethereum's `secp256k1`, just different primes.

**Comment by vgrichina** [comment]
@ilblackdragon FYI Apple has completely new API these days https://developer.apple.com/documentation/cryptokit

Looks like it supports our curve.

**Comment by ilblackdragon** [comment]
Implemented.
