### ISSUE TITLE
`Account createAccount30 does not match requirements` error wording is unclear

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/nearcore#981]
Should make it clear what given requirements are and that name specifically doesn't match requirements (vs e.g. not enough balance).

Also would help to be specific during which action it happened (e.g. "Cannot create account") cause errors can be in a context without stack trace.

**Comment by vgrichina** [comment]
@potatodepaulo feel free to re-assign, but I feel it's good idea for you to be involved (cause helps with docs + you can know better which problems devs have)

**Comment by potatodepaulo** [comment]
What's actually happening with this?

**Comment by vgrichina** [comment]
@potatodepaulo realized it's probably easier for me to fix message directly.

See https://github.com/nearprotocol/nearcore/pull/992, feel free to improve message / merge.
