### ISSUE TITLE
Numbers in JSON shouldn't be bigger than 53-bit

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/nearcore#982]
Right now we have token amounts serialized to JSON as numbers. Same goes for nonce.
This is not viable cause on JS side there is only 53-bit of precision for numbers.

**Comment by ilblackdragon** [comment]
Hm, is there any way to support 128 bit numbers? We need to switch to them (I already have PR with partial switch in Core)

**Comment by bowenwang1996** [comment]
We can pass them as string as use some big number library on the JS side to parse it.

**Comment by vgrichina** [comment]
Yes, the way to support them is to use strings. 

In modern JS library isn't even needed anymore:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
Might need to ship polyfill though for older browsers, or use https://github.com/GoogleChromeLabs/jsbi

**Comment by ilblackdragon** [comment]
We should have it addressed now by storing strings: either hex or decimal.
