### ISSUE TITLE
Three failures in txflow tests

### ISSUE THREAD

**Issue by SkidanovAlex** [nearprotocol/nearcore#99]
There are three generated tests failing. Here are the tests and the reasons:

`bob_fork`

Alice approves two messages from Bob, neither shall be considered an endorsements. Carol and Dave only approve one, both such approvals shall be endorsements.

`bob_second_msg_in_kickout_epoch`

Bob has a message that approves his own kickout message in the same epoch. Rust implementation mistakenly marks such message as kickout as well.

`generated_kickouts_and_epoch_blocks_1`

For some reason Carol's message is not a representative, even though it approves the previous representative, and its own kickout message has sufficient number of endorsements.

**Comment by nearmax** [comment]
Blocked on https://github.com/nearprotocol/nearcore/issues/125

**Comment by ilblackdragon** [comment]
@SkidanovAlex @nearmax @mikhailOK  is still open?

**Comment by nearmax** [comment]
Yes. Needs new implementation by @mikhailOK

**Comment by nearmax** [comment]
TxFlow is getting removed
